<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adam Ezzat">
<meta name="dcterms.date" content="2026-05-22">
<meta name="description" content="A three-phase green-compute layer for CJC-Lang: a Runtime Policy Layer (thermal profiles, deterministic energy estimate), race-to-idle adaptive scheduling that recovers burst performance while keeping a sustained thermal bound, and fused elementwise kernels that cut memory traffic. The connective tissue is one guarantee — thread count, pool size, and schedule provably never change the answer — which is what makes an adaptive thermal scheduler safe in a deterministic language. Every number below was measured on the branch.">

<title>Adam Ezzat - Green by Construction: Thermal Bounds Without Losing a Bit</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Adam Ezzat</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../blog/index.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/AdamEzzat1" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/adamezzat" rel="" target=""><i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-problem-a-laptop-that-cooks-itself" id="toc-the-problem-a-laptop-that-cooks-itself" class="nav-link active" data-scroll-target="#the-problem-a-laptop-that-cooks-itself">The problem: a laptop that cooks itself</a></li>
  <li><a href="#the-reframe-that-makes-it-tractable" id="toc-the-reframe-that-makes-it-tractable" class="nav-link" data-scroll-target="#the-reframe-that-makes-it-tractable">The reframe that makes it tractable</a></li>
  <li><a href="#phase-1-a-runtime-policy-layer" id="toc-phase-1-a-runtime-policy-layer" class="nav-link" data-scroll-target="#phase-1-a-runtime-policy-layer">Phase 1: a Runtime Policy Layer</a>
  <ul class="collapse">
  <li><a href="#a-deterministic-energy-estimate" id="toc-a-deterministic-energy-estimate" class="nav-link" data-scroll-target="#a-deterministic-energy-estimate">A <em>deterministic</em> energy estimate</a></li>
  <li><a href="#what-the-fixed-cap-costs" id="toc-what-the-fixed-cap-costs" class="nav-link" data-scroll-target="#what-the-fixed-cap-costs">What the fixed cap costs</a></li>
  </ul></li>
  <li><a href="#phase-2-race-to-idle-adaptive-scheduling" id="toc-phase-2-race-to-idle-adaptive-scheduling" class="nav-link" data-scroll-target="#phase-2-race-to-idle-adaptive-scheduling">Phase 2: race-to-idle adaptive scheduling</a>
  <ul class="collapse">
  <li><a href="#did-it-work-two-regimes-measured" id="toc-did-it-work-two-regimes-measured" class="nav-link" data-scroll-target="#did-it-work-two-regimes-measured">Did it work? Two regimes, measured</a></li>
  <li><a href="#why-this-is-safe" id="toc-why-this-is-safe" class="nav-link" data-scroll-target="#why-this-is-safe">Why this is safe</a></li>
  </ul></li>
  <li><a href="#phase-3a-fused-kernels-cut-memory-traffic" id="toc-phase-3a-fused-kernels-cut-memory-traffic" class="nav-link" data-scroll-target="#phase-3a-fused-kernels-cut-memory-traffic">Phase 3a: fused kernels cut memory traffic</a></li>
  <li><a href="#how-unique-is-this" id="toc-how-unique-is-this" class="nav-link" data-scroll-target="#how-unique-is-this">How unique is this?</a></li>
  <li><a href="#what-i-measured-vs.-what-i-estimated" id="toc-what-i-measured-vs.-what-i-estimated" class="nav-link" data-scroll-target="#what-i-measured-vs.-what-i-estimated">What I measured vs.&nbsp;what I estimated</a></li>
  <li><a href="#verification" id="toc-verification" class="nav-link" data-scroll-target="#verification">Verification</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Green by Construction: Thermal Bounds Without Losing a Bit</h1>
<p class="subtitle lead">How I made CJC-Lang thermally bounded and more memory-efficient — while keeping output bit-identical.</p>
  <div class="quarto-categories">
    <div class="quarto-category">CJC-Lang</div>
    <div class="quarto-category">performance</div>
    <div class="quarto-category">determinism</div>
    <div class="quarto-category">green-computing</div>
    <div class="quarto-category">energy</div>
    <div class="quarto-category">architecture</div>
  </div>
  </div>

<div>
  <div class="description">
    A three-phase green-compute layer for CJC-Lang: a Runtime Policy Layer (thermal profiles, deterministic energy estimate), race-to-idle adaptive scheduling that recovers burst performance while keeping a sustained thermal bound, and fused elementwise kernels that cut memory traffic. The connective tissue is one guarantee — thread count, pool size, and schedule provably never change the answer — which is what makes an adaptive thermal scheduler safe in a deterministic language. Every number below was measured on the branch.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Adam Ezzat </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 22, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">May 22, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="reading-time">
🕑 ~13 min read
</div>
<div class="stats-row">
<div class="stat">
<span class="number">3</span><span class="stat-label">thermal profiles</span>
</div>
<div class="stat">
<span class="number">80</span><span class="stat-label">new tests</span>
</div>
<div class="stat">
<span class="number">2653</span><span class="stat-label">lib tests passing</span>
</div>
<div class="stat">
<span class="number">0</span><span class="stat-label">output bits changed</span>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
TL;DR
</div>
</div>
<div class="callout-body-container callout-body">
<p>I gave <a href="../../../blog/posts/introducing-cjc/index.html">CJC-Lang</a> a green-compute layer in three phases. <strong>Phase 1</strong> is a Runtime Policy Layer: <code>--profile cool|balanced|max-perf</code> bounds how much CPU a run uses, plus a <em>deterministic</em> energy estimate. <strong>Phase 2</strong> is race-to-idle adaptive scheduling — full speed for short bursts, throttle only when load is sustained — which recovered ~1.8× of the throughput the fixed cap cost, while keeping the sustained thermal bound. <strong>Phase 3a</strong> is fused elementwise kernels that eliminate intermediate tensor allocations. The whole thing rests on one invariant: <strong>thread count, pool size, and the adaptive schedule provably never change the output.</strong> Same seed, same bits — across every profile, thread count, and both executors. That’s what makes an <em>adaptive</em> thermal knob safe in a language whose entire pitch is reproducibility.</p>
</div>
</div>
<section id="the-problem-a-laptop-that-cooks-itself" class="level2">
<h2 class="anchored" data-anchor-id="the-problem-a-laptop-that-cooks-itself">The problem: a laptop that cooks itself</h2>
<p>CJC-Lang’s core promise is <em>same seed, same output, always</em>. To get there it already does the unglamorous work: ordered collections, Kahan/binned summation, a seeded RNG, and — critically for this story — <strong>no FMA in the SIMD kernels</strong>, so a multiply-then-add rounds the same way every time.</p>
<p>But nothing in the runtime bounded <em>how hard</em> it pushed the machine. The parallel matmul and reduction kernels ran on Rayon’s default global pool — every core, all the time. On a laptop, a training loop would peg all 8 cores, spin the fans up, and eventually thermal-throttle: the CPU gets hot enough that the firmware <em>lowers</em> the clock to protect itself, and you end up slower than if you’d never saturated it.</p>
<p>I wanted an explicit, deterministic answer to “how much machine may this run use?” — without the OS power governor’s opacity, and without breaking the reproducibility contract.</p>
</section>
<section id="the-reframe-that-makes-it-tractable" class="level2">
<h2 class="anchored" data-anchor-id="the-reframe-that-makes-it-tractable">The reframe that makes it tractable</h2>
<p>Here’s the mental model I kept coming back to:</p>
<blockquote class="blockquote">
<p><strong>Energy = power × time.</strong> Capping cores cuts power but <em>raises</em> time. On a short burst that’s often a wash — you run cooler but longer. The levers that recover performance <em>and</em> save energy attack the other terms: total work (fewer cycles), memory traffic (the dominant energy term), and <em>when</em> you spend the thermal budget.</p>
</blockquote>
<p>Crucially: <strong>bursts don’t overheat — only sustained load does.</strong> Thermal time constants are seconds to tens of seconds, so a sub-second burst at full tilt never heat-soaks the package. A fixed thread cap pays the throttle tax on <em>every</em> operation, including the short interactive runs that were never going to overheat.</p>
<p>And the linchpin that makes all of this safe: in CJC-Lang, <strong>thread count never changes the result.</strong> The parallel reductions sum in a fixed chunk order with Kahan/binned accumulators, so the numeric output is identical no matter how many workers are live. That single guarantee is what lets me treat parallelism as a pure heat/speed knob — and even make it <em>adaptive</em> — without ever risking the answer.</p>
</section>
<section id="phase-1-a-runtime-policy-layer" class="level2">
<h2 class="anchored" data-anchor-id="phase-1-a-runtime-policy-layer">Phase 1: a Runtime Policy Layer</h2>
<p>The first piece is a <code>RuntimePolicy</code> — the green-compute control surface. It lives in a thread-local in <code>cjc-runtime</code>, mirroring the existing profiler sink.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode rust code-with-copy"><code class="sourceCode rust"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">pub</span> <span class="kw">struct</span> RuntimePolicy <span class="op">{</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> determinism<span class="op">:</span> Determinism<span class="op">,</span>   <span class="co">// Strict</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> numeric_mode<span class="op">:</span> NumericMode<span class="op">,</span>  <span class="co">// Kahan | Binned | FixedTree</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> thermal_mode<span class="op">:</span> ThermalMode<span class="op">,</span>  <span class="co">// Cool | Balanced | MaxPerf</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> max_threads<span class="op">:</span> <span class="dt">usize</span><span class="op">,</span>         <span class="co">// 0 = auto (derive from thermal_mode)</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> batch_size<span class="op">:</span> <span class="dt">usize</span><span class="op">,</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> audit_mode<span class="op">:</span> AuditMode<span class="op">,</span>      <span class="co">// Summary | Full | Forensic</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> adaptive<span class="op">:</span> <span class="dt">bool</span><span class="op">,</span>             <span class="co">// race-to-idle (Phase 2)</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Three thermal profiles, exposed as CLI flags applied once at startup so they cover <code>run</code>, <code>bench</code>, and every command:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Profile</th>
<th>Threads (8-core host)</th>
<th>Batch</th>
<th>Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>cool</code></td>
<td>≈ ¼ cores → <strong>2</strong></td>
<td>32</td>
<td>laptop, edge, gentle</td>
</tr>
<tr class="even">
<td><code>balanced</code> (default)</td>
<td>≈ ½ cores → <strong>4</strong></td>
<td>128</td>
<td>normal — leaves headroom</td>
</tr>
<tr class="odd">
<td><code>max-perf</code></td>
<td>all → <strong>8</strong></td>
<td>512</td>
<td>benchmarking</td>
</tr>
</tbody>
</table>
<p>The default is <strong><code>balanced</code></strong>, deliberately not “all cores forever.”</p>
<section id="a-deterministic-energy-estimate" class="level3">
<h3 class="anchored" data-anchor-id="a-deterministic-energy-estimate">A <em>deterministic</em> energy estimate</h3>
<p>Most energy tools (CodeCarbon, Scaphandre, RAPL counters) <em>measure</em> power from hardware — which is non-deterministic and machine-specific. I wanted energy to be a number you can assert in a test. So <code>energy_estimate</code> is a pure function of the workload, never of wall-clock time:</p>
<pre class="text"><code>joules ≈ flops × 1e-10  +  bytes × 1e-10
         (~100 pJ/flop)     (~100 pJ/byte, DRAM-ish)</code></pre>
<p>The two terms are computed in separate bindings so the compiler can’t fuse them into an FMA — the same no-FMA discipline as the SIMD kernels. Same program, same seed → same FLOP count → same joules, bit-for-bit. On the branch, <code>energy_estimate(1000000, 2000)</code> returns <code>0.00010020000000000001</code> — <em>identical</em> under every profile, thread count, and both executors. The absolute number is an order-of-magnitude estimate; the <strong>ratio</strong> between two runs is the meaningful, reproducible figure.</p>
</section>
<section id="what-the-fixed-cap-costs" class="level3">
<h3 class="anchored" data-anchor-id="what-the-fixed-cap-costs">What the fixed cap costs</h3>
<p>Measured on an 8-core machine, release build, <code>cjcl bench</code> (10 runs) on a 1024×1024 matmul:</p>
<table class="table">
<thead>
<tr class="header">
<th>Profile</th>
<th>Threads</th>
<th>Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>--threads 1</code></td>
<td>1</td>
<td>628 ms</td>
</tr>
<tr class="even">
<td><code>cool</code></td>
<td>2</td>
<td>468 ms</td>
</tr>
<tr class="odd">
<td><code>balanced</code> (default)</td>
<td>4</td>
<td>268 ms</td>
</tr>
<tr class="even">
<td><code>max-perf</code></td>
<td>8</td>
<td>210 ms</td>
</tr>
</tbody>
</table>
<p>So the cap genuinely throttles (max-perf is ~3× faster than single-threaded) — and the laptop-safe default costs ~27% versus all-out. That cost is real, and Phase 2 is about clawing most of it back.</p>
</section>
</section>
<section id="phase-2-race-to-idle-adaptive-scheduling" class="level2">
<h2 class="anchored" data-anchor-id="phase-2-race-to-idle-adaptive-scheduling">Phase 2: race-to-idle adaptive scheduling</h2>
<p>A fixed cap throttles short and long workloads alike. Race-to-idle fixes that: <strong>run at full width during a burst, and throttle to the cap only once load is sustained</strong> (a 2-second window; a ½-second idle gap resets it).</p>
<p>The mechanism is the interesting part. Rayon’s global pool can only be configured once, so I <em>don’t</em> shrink it — I leave it at full size so bursts can use every core. Throttling happens per-operation: when a workload has been busy past the window, the kernel’s parallel section is <code>install</code>-ed into a cached, cap-sized pool. Inside that pool <code>rayon::current_num_threads()</code> reports the cap, so the existing band/row/chunk splitters auto-scale — no per-kernel rewrites.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode rust code-with-copy"><code class="sourceCode rust"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">pub</span> <span class="kw">fn</span> run_parallel<span class="op">&lt;</span>R<span class="op">:</span> <span class="bu">Send</span><span class="op">&gt;</span>(work<span class="op">:</span> <span class="kw">impl</span> <span class="bu">FnOnce</span>() <span class="op">-&gt;</span> R <span class="op">+</span> <span class="bu">Send</span>) <span class="op">-&gt;</span> R <span class="op">{</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="pp">rayon::</span>current_thread_index()<span class="op">.</span>is_some() <span class="op">{</span> <span class="cf">return</span> work()<span class="op">;</span> <span class="op">}</span> <span class="co">// nested → inline</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">let</span> cap <span class="op">=</span> effective_threads(<span class="op">&amp;</span>get()<span class="op">,</span> detect_cores())<span class="op">;</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> cap <span class="op">&gt;=</span> detect_cores() <span class="op">{</span> <span class="cf">return</span> work()<span class="op">;</span> <span class="op">}</span>                   <span class="co">// no cap</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">let</span> throttle <span class="op">=</span> <span class="cf">if</span> get()<span class="op">.</span>adaptive <span class="op">{</span> is_sustained_now() <span class="op">}</span> <span class="cf">else</span> <span class="op">{</span> <span class="cn">true</span> <span class="op">};</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="op">!</span>throttle <span class="op">{</span> <span class="cf">return</span> work()<span class="op">;</span> <span class="op">}</span>                               <span class="co">// burst → full pool</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">match</span> capped_pool(cap) <span class="op">{</span> <span class="cn">Some</span>(p) <span class="op">=&gt;</span> p<span class="op">.</span>install(work)<span class="op">,</span> <span class="cn">None</span> <span class="op">=&gt;</span> work() <span class="op">}</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The four parallel kernels (large/medium/batch matmul, SIMD elementwise) wrap their bodies in <code>run_parallel</code>.</p>
<section id="did-it-work-two-regimes-measured" class="level3">
<h3 class="anchored" data-anchor-id="did-it-work-two-regimes-measured">Did it work? Two regimes, measured</h3>
<p><strong>Short workload</strong> (one 1024² matmul, finishes inside the burst window), minimum of 9 <code>--time</code> runs:</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>cool fixed</th>
<th><strong>cool adaptive</strong></th>
<th>max-perf</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>time</td>
<td>0.353 s</td>
<td><strong>0.196 s</strong></td>
<td>0.153 s</td>
</tr>
</tbody>
</table>
<p>Adaptive-cool recovered ~<strong>1.8×</strong> (0.353 → 0.196 s) — landing within fixed startup overhead of max-perf. The short, interactive case now runs at full speed <em>and</em> never trips the cap.</p>
<p><strong>Sustained workload</strong> (25× 1024² matmuls, ~runs well past the 2 s window):</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>cool fixed</th>
<th><strong>cool adaptive</strong></th>
<th>max-perf</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>time</td>
<td>16.7 s</td>
<td><strong>10.8 s</strong></td>
<td>4.2 s</td>
</tr>
</tbody>
</table>
<p>This is the part I care about most: adaptive-cool (10.8 s) sits <em>between</em> fixed-cool and max-perf. It is <strong>not</strong> near max-perf (4.2 s) — meaning it genuinely throttled after the burst. The thermal bound held; the burst just bought back the first couple of seconds. Exactly the goal: fast when it’s safe, bounded when it matters.</p>
</section>
<section id="why-this-is-safe" class="level3">
<h3 class="anchored" data-anchor-id="why-this-is-safe">Why this is safe</h3>
<p>The burst-vs-throttle decision reads the wall clock, so the <em>schedule</em> is non-deterministic run-to-run. But the <em>output</em> isn’t, because the choice only changes how many bands run concurrently — never the per-element math. To prove it rather than assert it: a 256×256 matrix product (a real parallel reduction over varied values) hashed <strong>byte-identical</strong> across <code>--threads 1</code>, <code>cool</code>, <code>balanced</code>, <code>max-perf</code>, adaptive on/off, <em>and</em> both the AST and MIR executors:</p>
<pre class="text"><code>threads=1  (eval)    : 79aaf9931d2b6c2004a20cdf5d5bd434
threads=8  (eval)    : 79aaf9931d2b6c2004a20cdf5d5bd434
cool (adaptive burst): 79aaf9931d2b6c2004a20cdf5d5bd434
cool --no-adaptive   : 79aaf9931d2b6c2004a20cdf5d5bd434
max-perf             : 79aaf9931d2b6c2004a20cdf5d5bd434
MIR cool (adaptive)  : 79aaf9931d2b6c2004a20cdf5d5bd434</code></pre>
<p>For reproducible benchmarking — where you <em>want</em> a fixed schedule — <code>--no-adaptive</code> applies the cap uniformly.</p>
</section>
</section>
<section id="phase-3a-fused-kernels-cut-memory-traffic" class="level2">
<h2 class="anchored" data-anchor-id="phase-3a-fused-kernels-cut-memory-traffic">Phase 3a: fused kernels cut memory traffic</h2>
<p>The third lever is memory. A plain <code>a*b + c</code> allocates an intermediate: <code>mul</code> → a fresh tensor, then <code>add</code> → another. That’s two allocations and ~5N words of traffic for an N-element result. A fused single-pass kernel does it in <strong>one allocation and one pass</strong> (~4N words).</p>
<p>I added three, joining the existing <code>broadcast_fma</code>:</p>
<table class="table">
<thead>
<tr class="header">
<th>Builtin</th>
<th>Computes</th>
<th>Replaces</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>fused_axpy(α, x, y)</code></td>
<td><code>α·x + y</code></td>
<td>scalar-mul + add (BLAS axpy)</td>
</tr>
<tr class="even">
<td><code>fused_mul_sub(a, b, c)</code></td>
<td><code>a·b − c</code></td>
<td>mul + sub</td>
</tr>
<tr class="odd">
<td><code>fused_sub_sq(a, b)</code></td>
<td><code>(a−b)²</code></td>
<td>sub + mul (MSE/variance/distance)</td>
</tr>
</tbody>
</table>
<p>The subtle bit is <em>why this is free</em>: <code>a*b + c</code> in Rust compiles to a <strong>separate</strong> multiply then add — it does <strong>not</strong> contract into a hardware FMA unless you call <code>.mul_add()</code> explicitly. So the fused loop produces bit-identical results to the two-pass version while eliminating the intermediate. I pinned that with property tests asserting <code>fused == unfused</code> byte-for-byte over 256 random cases each.</p>
<p>And this <em>compounds</em> with Phase 2: lighter work finishes inside the burst window, so the cap engages even less. Memory efficiency and the adaptive scheduler reinforce each other instead of trading off.</p>
</section>
<section id="how-unique-is-this" class="level2">
<h2 class="anchored" data-anchor-id="how-unique-is-this">How unique is this?</h2>
<p>Honest answer: the individual pieces all exist somewhere. Thread caps are everywhere (Rayon, OpenMP, <code>GOMAXPROCS</code>). OS governors and RAPL do power capping. Race-to-idle is textbook power management. CodeCarbon and friends estimate energy. Intel MKL has reproducible-numerics modes.</p>
<p>What I haven’t seen packaged together is the <strong>combination at the language-runtime level with a determinism guarantee</strong>: a thermal/energy policy where the knobs are <em>provably</em> result-invariant, paired with an adaptive scheduler and a reproducible energy estimate. In most stacks, changing thread count <em>can</em> change floating-point results; here it provably can’t, which is the whole reason an adaptive thermal scheduler is even safe to ship. It’s most at home in the niche CJC-Lang targets — reproducible scientific, regulated, and edge computing — not hyperscale throughput.</p>
</section>
<section id="what-i-measured-vs.-what-i-estimated" class="level2">
<h2 class="anchored" data-anchor-id="what-i-measured-vs.-what-i-estimated">What I measured vs.&nbsp;what I estimated</h2>
<p>In keeping with the project’s ethos, the honest accounting:</p>
<ul>
<li><strong>Measured:</strong> all the wall-clock numbers (release <code>cjcl bench</code> / <code>--time</code>), the determinism hashes, the test counts. These are real and on the branch.</li>
<li><strong>A proxy, not a measurement:</strong> I measured wall-clock and active-core counts, <em>not</em> watts or junction temperature. Fewer active cores means less package power, but I don’t have hardware sensors in the loop — treat the thermal claims as a well-founded proxy, not a power reading.</li>
<li><strong>Analytical, not benchmarked:</strong> the fused-kernel traffic reduction (~5N → ~4N words, two allocations → one) is from counting, not a wall-clock microbenchmark. What I <em>did</em> verify is that the output is bit-identical to the unfused path.</li>
<li><strong>Deferred:</strong> the data-DSL group-by/join memory work (Phase 3b) is not in this post. The obvious approach turned out to change output <em>order</em> (the streaming path sorts keys; the materializing path preserves first-occurrence order), which would break determinism — so I stopped rather than ship a correctness regression. It needs an order-preserving design, which is its own phase.</li>
</ul>
</section>
<section id="verification" class="level2">
<h2 class="anchored" data-anchor-id="verification">Verification</h2>
<p>Every claim above is backed by tests on the branch: <strong>80 new tests</strong> for this work (20 unit + 43 integration for the policy/scheduling layer; 17 for the fused kernels), the dual-executor parity gate at 10/10, and the full workspace library suite at <strong>2653 passing, 0 failures</strong>. No determinism gate moved.</p>
<p>The throughline: you don’t have to choose between <em>fast</em>, <em>reproducible</em>, and <em>cool</em>. You can have a thermal bound that adapts to your workload, energy you can reason about, and lower memory traffic — and still get the same bits out every single time. In a deterministic language, that last clause isn’t a nice-to-have. It’s the whole point.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© 2026 Adam Ezzat. Built with <a href="https://quarto.org/">Quarto</a>.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>