<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adam Ezzat">
<meta name="dcterms.date" content="2026-05-28">
<meta name="description" content="Phase 0.10 returns to UCI Diabetes 130-US Hospitals with both ABNG and Locke. Tuning K_ROUTING=2 + stronger BLR prior + the full 101,766 rows lifts held-out test AUC to 0.6645 ± 0.0018 across 3 seeds — in the strong-published-model band (0.64–0.68) without any architectural change, still on the linear BLR head. The route the handoff predicted to get there (Locke surfaces leakage → drop death-discharge rows → AUC up) did not work — Locke’s E9063 detector didn’t fire on the per-level leakage, and applying the prune via domain knowledge hurt AUC by 0.0118 because it shifted MI-selected routing features. Five commits, every chain head reproducible, six section outputs, a published role-by-role assessment of where each tool actually helped.">

<title>Adam Ezzat - Diabetes-130 Revisited: ABNG Climbs Into the Strong-Model Band — and an Honest Account of What Locke Did (and Didn’t)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Adam Ezzat</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../blog/index.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/AdamEzzat1" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/adamezzat" rel="" target=""><i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#whats-new-since-round-one" id="toc-whats-new-since-round-one" class="nav-link active" data-scroll-target="#whats-new-since-round-one">1. What’s new since Round One</a></li>
  <li><a href="#the-dataset-briefly-why-its-still-hard" id="toc-the-dataset-briefly-why-its-still-hard" class="nav-link" data-scroll-target="#the-dataset-briefly-why-its-still-hard">2. The dataset, briefly — why it’s still hard</a></li>
  <li><a href="#landing-the-tuned-config-the-first-0.05-auc" id="toc-landing-the-tuned-config-the-first-0.05-auc" class="nav-link" data-scroll-target="#landing-the-tuned-config-the-first-0.05-auc">3. Landing the tuned config — the first 0.05 AUC</a>
  <ul class="collapse">
  <li><a href="#what-the-change-did-at-20k" id="toc-what-the-change-did-at-20k" class="nav-link" data-scroll-target="#what-the-change-did-at-20k">What the change did at 20K</a></li>
  </ul></li>
  <li><a href="#lockes-audit-142-findings-one-critical-negative-result" id="toc-lockes-audit-142-findings-one-critical-negative-result" class="nav-link" data-scroll-target="#lockes-audit-142-findings-one-critical-negative-result">4. Locke’s audit — 142 findings, one critical negative result</a>
  <ul class="collapse">
  <li><a href="#e9004-the-leakage-hole-the-first-post-missed" id="toc-e9004-the-leakage-hole-the-first-post-missed" class="nav-link" data-scroll-target="#e9004-the-leakage-hole-the-first-post-missed">4.1 E9004 — the leakage hole the first post missed</a></li>
  <li><a href="#e9063-the-predicted-leakage-finding-that-didnt-fire" id="toc-e9063-the-predicted-leakage-finding-that-didnt-fire" class="nav-link" data-scroll-target="#e9063-the-predicted-leakage-finding-that-didnt-fire">4.2 E9063 — the predicted leakage finding that didn’t fire</a></li>
  <li><a href="#we-applied-the-prune-anyway-and-auc-dropped" id="toc-we-applied-the-prune-anyway-and-auc-dropped" class="nav-link" data-scroll-target="#we-applied-the-prune-anyway-and-auc-dropped">4.3 We applied the prune anyway — and AUC dropped</a></li>
  </ul></li>
  <li><a href="#full-101k-multi-seed-the-headline" id="toc-full-101k-multi-seed-the-headline" class="nav-link" data-scroll-target="#full-101k-multi-seed-the-headline">5. Full 101K, multi-seed — the headline</a>
  <ul class="collapse">
  <li><a href="#single-seed-at-full-scale" id="toc-single-seed-at-full-scale" class="nav-link" data-scroll-target="#single-seed-at-full-scale">5.1 Single seed at full scale</a></li>
  <li><a href="#routing-columns-flipped-at-full-scale" id="toc-routing-columns-flipped-at-full-scale" class="nav-link" data-scroll-target="#routing-columns-flipped-at-full-scale">5.2 Routing columns flipped at full scale</a></li>
  <li><a href="#three-seeds-putting-an-error-bar-on-the-headline" id="toc-three-seeds-putting-an-error-bar-on-the-headline" class="nav-link" data-scroll-target="#three-seeds-putting-an-error-bar-on-the-headline">5.3 Three seeds — putting an error bar on the headline</a></li>
  <li><a href="#the-honest-comparison-vs-the-first-post" id="toc-the-honest-comparison-vs-the-first-post" class="nav-link" data-scroll-target="#the-honest-comparison-vs-the-first-post">5.4 The honest comparison vs the first post</a></li>
  </ul></li>
  <li><a href="#the-locke--sentinel-saga-and-4.d" id="toc-the-locke--sentinel-saga-and-4.d" class="nav-link" data-scroll-target="#the-locke--sentinel-saga-and-4.d">6. The Locke <code>?</code>-sentinel saga and §4.D</a>
  <ul class="collapse">
  <li><a href="#locke-didnt-see-as-missing" id="toc-locke-didnt-see-as-missing" class="nav-link" data-scroll-target="#locke-didnt-see-as-missing">6.1 Locke didn’t see <code>?</code> as missing</a></li>
  <li><a href="#the-fix-nullmaskmap-plumbing" id="toc-the-fix-nullmaskmap-plumbing" class="nav-link" data-scroll-target="#the-fix-nullmaskmap-plumbing">6.2 The fix — <code>NullMaskMap</code> plumbing</a></li>
  <li><a href="#the-deeper-problem-leaves-clustered-at-uniform-belief" id="toc-the-deeper-problem-leaves-clustered-at-uniform-belief" class="nav-link" data-scroll-target="#the-deeper-problem-leaves-clustered-at-uniform-belief">6.3 The deeper problem — leaves clustered at uniform belief</a></li>
  <li><a href="#part-2-deferred-for-a-real-reason" id="toc-part-2-deferred-for-a-real-reason" class="nav-link" data-scroll-target="#part-2-deferred-for-a-real-reason">6.4 Part 2 — deferred for a real reason</a></li>
  </ul></li>
  <li><a href="#c-mlp-heads-design-only" id="toc-c-mlp-heads-design-only" class="nav-link" data-scroll-target="#c-mlp-heads-design-only">7. §4.C MLP heads — design only</a></li>
  <li><a href="#abng-architectural-fingerprint-what-carried-this" id="toc-abng-architectural-fingerprint-what-carried-this" class="nav-link" data-scroll-target="#abng-architectural-fingerprint-what-carried-this">8. ABNG architectural fingerprint — what carried this</a>
  <ul class="collapse">
  <li><a href="#the-φ-vs-routing-feature-split" id="toc-the-φ-vs-routing-feature-split" class="nav-link" data-scroll-target="#the-φ-vs-routing-feature-split">8.1 The φ-vs-routing feature split</a></li>
  <li><a href="#pre-fixed-mi-selected-routing" id="toc-pre-fixed-mi-selected-routing" class="nav-link" data-scroll-target="#pre-fixed-mi-selected-routing">8.2 Pre-fixed MI-selected routing</a></li>
  <li><a href="#per-leaf-bayesian-linear-regression-with-conjugate-updates" id="toc-per-leaf-bayesian-linear-regression-with-conjugate-updates" class="nav-link" data-scroll-target="#per-leaf-bayesian-linear-regression-with-conjugate-updates">8.3 Per-leaf Bayesian linear regression with conjugate updates</a></li>
  <li><a href="#sha-256-audit-chain-over-training-events" id="toc-sha-256-audit-chain-over-training-events" class="nav-link" data-scroll-target="#sha-256-audit-chain-over-training-events">8.4 SHA-256 audit chain over training events</a></li>
  <li><a href="#bit-identical-replay" id="toc-bit-identical-replay" class="nav-link" data-scroll-target="#bit-identical-replay">8.5 Bit-identical replay</a></li>
  </ul></li>
  <li><a href="#honest-assessment-what-locke-did-and-didnt" id="toc-honest-assessment-what-locke-did-and-didnt" class="nav-link" data-scroll-target="#honest-assessment-what-locke-did-and-didnt">9. Honest assessment — what Locke did, and didn’t</a>
  <ul class="collapse">
  <li><a href="#net-assessment" id="toc-net-assessment" class="nav-link" data-scroll-target="#net-assessment">Net assessment</a></li>
  </ul></li>
  <li><a href="#honest-limitations" id="toc-honest-limitations" class="nav-link" data-scroll-target="#honest-limitations">10. Honest limitations</a></li>
  <li><a href="#whats-next" id="toc-whats-next" class="nav-link" data-scroll-target="#whats-next">11. What’s next</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility">12. Reproducibility</a>
  <ul class="collapse">
  <li><a href="#figures" id="toc-figures" class="nav-link" data-scroll-target="#figures">Figures</a></li>
  </ul></li>
  <li><a href="#the-honest-summary" id="toc-the-honest-summary" class="nav-link" data-scroll-target="#the-honest-summary">13. The honest summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Diabetes-130 Revisited: ABNG Climbs Into the Strong-Model Band — and an Honest Account of What Locke Did (and Didn’t)</h1>
<p class="subtitle lead">A second pass on the UCI Diabetes-130 dataset with both the Adaptive Belief Network Graph and Locke, the determinism-first data-quality layer. Headline AUC moved from 0.611 to 0.6645 ± 0.0018 across 3 seeds at full 101,766 rows — into the strong-published-model band (0.64–0.68), still on a linear-BLR model, no MLP heads. The reason is data scale and configuration. Locke contributed structurally (E9004 patient-leak; <code>?</code>-sentinel detector gap; proposed E9064) but did <em>not</em> directly drive the AUC headline. The handoff’s flagship ‘Locke prune → AUC up’ hypothesis falsified itself — and that’s its own publishable finding.</p>
  <div class="quarto-categories">
    <div class="quarto-category">CJC-Lang</div>
    <div class="quarto-category">ABNG</div>
    <div class="quarto-category">Locke</div>
    <div class="quarto-category">medical</div>
    <div class="quarto-category">diabetes</div>
    <div class="quarto-category">calibration</div>
    <div class="quarto-category">determinism</div>
    <div class="quarto-category">experimental</div>
  </div>
  </div>

<div>
  <div class="description">
    Phase 0.10 returns to UCI Diabetes 130-US Hospitals with both ABNG and Locke. Tuning K_ROUTING=2 + stronger BLR prior + the full 101,766 rows lifts held-out test AUC to 0.6645 ± 0.0018 across 3 seeds — in the strong-published-model band (0.64–0.68) without any architectural change, still on the linear BLR head. The route the handoff predicted to get there (Locke surfaces leakage → drop death-discharge rows → AUC up) did not work — Locke’s E9063 detector didn’t fire on the per-level leakage, and applying the prune via domain knowledge <em>hurt</em> AUC by 0.0118 because it shifted MI-selected routing features. Five commits, every chain head reproducible, six section outputs, a published role-by-role assessment of where each tool actually helped.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Adam Ezzat </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 28, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">May 28, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="reading-time">
🕑 ~30 min read
</div>
<div class="stats-row">
<div class="stat">
<span class="number">0.6645 ± 0.0018</span><span class="stat-label">AUC, n=3 seeds, 101K rows</span>
</div>
<div class="stat">
<span class="number">142</span><span class="stat-label">Locke findings emitted</span>
</div>
<div class="stat">
<span class="number">629/629</span><span class="stat-label">determinism canaries unmoved</span>
</div>
<div class="stat">
<span class="number">0</span><span class="stat-label">MLP layers used</span>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
TL;DR
</div>
</div>
<div class="callout-body-container callout-body">
<p>A second pass on UCI Diabetes 130-US Hospitals — the same 101,766-encounter readmission dataset from <a href="../../../blog/posts/abng-diabetes-readmission/index.html">the first ABNG post</a> — with two changes:</p>
<ol type="1">
<li><strong>Land the validation-tuned config</strong> (<code>K_ROUTING = 2</code>, stronger BLR prior) that the first post’s sweep identified but never committed back to source.</li>
<li><strong>Run the full dataset at multiple seeds</strong> instead of a 20K sub-sample at a single seed.</li>
</ol>
<p>Held-out test AUC moves <strong>0.611 → 0.6312 → 0.6621 → 0.6645 ± 0.0018</strong>: tuned config at 20K, then full 101K single-seed, then 3-seed variance. <strong>0.6645 is in the strong-published-model band (0.64–0.68)</strong> — the band the first post said required nonlinear MLP heads. It turns out the linear BLR + good config + full data was enough.</p>
<p>Locke (the <a href="../../../blog/posts/cjc-locke-v0.1-released/index.html">determinism-first data-quality layer</a>) ran the audit. <strong>It did not drive the AUC headline.</strong> The handoff predicted E9063 multi-class leakage would fire on <code>discharge_disposition_id</code> (death/hospice codes deterministically predict <code>readmitted=NO</code>); it didn’t, because per-feature ROC-AUC misses per-<em>level</em> deterministic outcomes. Applying the prune anyway via domain knowledge <em>dropped</em> AUC by 0.0118 — a confounded experiment, because the prune also shifted MI-selected routing features. Locke’s actual contributions this session were structural: surfacing a patient-encounter leakage hole the first post missed (E9004), exposing its own <code>?</code>-sentinel blindness on medical CSVs, and pinning a concrete failure mode for a proposed E9064 detector. <strong>AUC was ABNG’s win; the systems / detector-roadmap axis was Locke’s.</strong></p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Prototype disclaimer
</div>
</div>
<div class="callout-body-container callout-body">
<p>ABNG and Locke are both research-stage prototypes built on <strong>CJC-Lang</strong>, a research compiler that is itself pre-1.0. All three are under active development. The numbers below are a single reproducible experiment campaign — five commits, every chain head verifiable — not a validated benchmark, not deployed, not peer-reviewed. Read as honest exploratory engineering.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Where this sits
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><a href="../../../blog/posts/abng-architecture/index.html">ABNG: Treating Belief States as First-Class Citizens</a> — the architecture this post measures.</li>
<li><a href="../../../blog/posts/abng-diabetes-readmission/index.html">ABNG on Real Clinical Data — The Diabetes-130 Readmission Task</a> — <strong>Round One.</strong> The first post’s AUC 0.611 is the baseline this post improves on.</li>
<li><a href="../../../blog/posts/cjc-locke-v0.1-released/index.html">Locke v0.1.10: An Epistemic Layer for Data Validation</a> — Locke’s framing as evidence-aware, determinism-first audit.</li>
<li><a href="../../../blog/posts/abng-benchmarks/index.html">Benchmarks Part I</a> / <a href="../../../blog/posts/abng-benchmarks-part-2/index.html">Part II</a> — controlled-data baselines.</li>
<li><strong>This post</strong> — Round Two of the same dataset, now with both tools in the loop, and an honest dissection of what each one actually contributed.</li>
</ul>
</div>
</div>
<section id="whats-new-since-round-one" class="level2">
<h2 class="anchored" data-anchor-id="whats-new-since-round-one">1. What’s new since Round One</h2>
<p>The <a href="../../../blog/posts/abng-diabetes-readmission/index.html">first diabetes-130 post</a> ended with three explicit “still on the bench” items:</p>
<ol type="1">
<li>Nonlinear leaf heads (MLP) — to see if the <em>ranking</em> ceiling moved.</li>
<li>The full 101,766-row run at the tuned configuration.</li>
<li>Multi-seed variance.</li>
</ol>
<p>Round Two lands items <strong>2 and 3</strong>, leaves item <strong>1</strong> as a design doc, and adds two new ones that the first post didn’t anticipate:</p>
<ol start="4" type="1">
<li><strong>Locke pre-training audit.</strong> Run <code>cjcl locke validate</code> on the full CSV, see what the determinism-first data-quality layer surfaces, and act on it.</li>
<li><strong>Belief-weighted per-leaf priors.</strong> Use Locke’s per-leaf <code>BeliefScore</code> to weight per-leaf BLR regularization — the directional hypothesis from <a href="https://github.com/AdamEzzat1/CJC/blob/master/docs/locke/ABNG_PER_LEAF_BELIEF.md"><code>docs/locke/ABNG_PER_LEAF_BELIEF.md</code></a>.</li>
</ol>
<p>That’s the plan. The result is more interesting than the plan, because items <strong>1, 4, and 5 did not work the way the brief expected</strong> — and item <strong>1 turned out to be unnecessary</strong> for the headline. The honest accounting of which lever moved which number is half the point of this post.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What carries forward unchanged
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Determinism contract, audit chain, evaluation protocol — all unchanged.</strong> The 70/15/20-style stratified split, fit-on-train-only categorical transform, validation-set-only tuning, single test-set touch, deterministic SplitMix64 RNG, Kahan summation, BTreeMap iteration — all the discipline the first post’s §2 spelled out remains. 629/629 always-run ABNG tests stayed green across five commits of aggressive configuration changes. Every chain head in this post is bit-reproducible. The first post’s §7 reproducibility property — “two runs, 3× wall-clock difference, every metric digit identical” — held throughout.</p>
</div>
</div>
</section>
<section id="the-dataset-briefly-why-its-still-hard" class="level2">
<h2 class="anchored" data-anchor-id="the-dataset-briefly-why-its-still-hard">2. The dataset, briefly — why it’s still hard</h2>
<p>The first post’s §1 walked through the dataset in detail. The short version, because the difficulty profile matters for reading the rest of this post:</p>
<p>UCI <strong>Diabetes 130-US Hospitals (1999–2008)</strong> — 101,766 hospital encounters, 50 columns, deeply heterogeneous. By ML standards it’s genuinely difficult:</p>
<ul>
<li><strong>101,766 rows × 50 columns</strong>. 13 numeric, 23 medication categoricals (one per drug — <code>metformin</code>, <code>insulin</code>, <code>glipizide</code>, etc.), three ICD-9 diagnosis-code columns with <strong>700+ distinct levels each</strong>, demographics, admission / discharge / source codes.</li>
<li><strong>Missingness sentinel is <code>?</code></strong> (literal string), not NaN. <code>weight</code> is 96.9% missing. <code>payer_code</code> and <code>medical_specialty</code> are heavily missing. Standard tooling that treats only NaN as missing won’t see any of this without configuration.</li>
<li><strong>Longitudinal structure.</strong> 16,773 patients have multiple encounters (30,248 duplicate <code>patient_nbr</code> values). Row-level train/test splitting lets the same patient appear in both splits. The first post used row-level splitting; we’ll come back to this in §5.</li>
<li><strong>3-class target</strong> (<code>NO</code> / <code>&lt;30</code> / <code>&gt;30</code> days to readmission), binarised to <code>&lt;30 vs rest</code>. <strong>11.16% positive class</strong> — predicting <code>NO</code> for everyone scores ~89% accuracy with zero learning. Accuracy is the wrong yardstick; the post leads with AUC, balanced accuracy, and calibrated Brier/NLL/ECE.</li>
<li><strong>Hard target.</strong> Strong published models band at <strong>AUC 0.64–0.68</strong>. The ceiling is <em>irreducible noise</em> — readmission depends on post-discharge factors (social support, follow-up care, medication adherence) not in the data. A model claiming AUC 0.9 here would be suspect, not impressive.</li>
</ul>
<div id="fig-missingness" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/traditional/per_column_missingness.png" class="img-fluid figure-img" alt="Horizontal bar chart of 7 columns with non-zero ?-rates. weight stands out at 96.9% in red. medical_specialty and payer_code at 49.1% and 39.6% in orange. race, diag_3, diag_2, diag_1 are tiny purple bars (<3%). A pale green band highlights the >50% missing zone with the label 'drop or impute'."></p>
<figcaption class="figure-caption">Figure&nbsp;1: Per-column <code>?</code>-sentinel missingness across the 50 diabetes-130 columns. Only 7 columns contain any <code>?</code> values, and the first three carry essentially all of the missingness: <code>weight</code> at <strong>96.9%</strong> (effectively useless as a feature), <code>medical_specialty</code> at 49.1%, and <code>payer_code</code> at 39.6%. The green band marks the “≥50% missing — drop or impute” zone. This concentration explains why Locke’s default missingness detector returning <code>missingness_score = 1.0</code> is so misleading on this dataset (see §6) — almost all the missingness is hiding in three columns that don’t fire under the NaN-only default config.</figcaption>
</figure>
</div>
<p>It’s exactly the kind of dataset where the easy wins (high raw accuracy) are traps, the obvious leakages (death-discharge codes deterministically predicting “no readmission”) hide at the level not the column, and the structural issues (repeated patients) don’t show up in any single AUC number.</p>
</section>
<section id="landing-the-tuned-config-the-first-0.05-auc" class="level2">
<h2 class="anchored" data-anchor-id="landing-the-tuned-config-the-first-0.05-auc">3. Landing the tuned config — the first 0.05 AUC</h2>
<p>The first post’s §5 ran a validation sweep over <code>K_ROUTING ∈ {2, 3, 4}</code> × BLR prior precision <code>∈ {0.05, 0.1, 0.5}</code> and concluded:</p>
<blockquote class="blockquote">
<p><strong>K = 2 won, decisively.</strong> With ~14,000 training rows, K=2 gives 16 leaves (~875 rows each), while K=4 gives 256 leaves (~55 rows each). Deeper routing buys “specialization” but starves every leaf of the data it needs. (Stronger prior regularization also helped, monotonically.)</p>
</blockquote>
<p>But the harness’s source code (in <code>tests/abng/dataset_a_diabetes130.rs</code>) still had <code>K_ROUTING = 3</code> and <code>BLR_PRIOR_PRECISION = 0.1</code>. The sweep result lived in the blog post; it never came home to the harness.</p>
<p>§4.A landed the validated config:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode rust code-with-copy"><code class="sourceCode rust"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">const</span> K_ROUTING<span class="op">:</span> <span class="dt">usize</span> <span class="op">=</span> <span class="dv">2</span><span class="op">;</span>           <span class="co">// was 3</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="kw">const</span> BLR_PRIOR_PRECISION<span class="op">:</span> <span class="dt">f64</span> <span class="op">=</span> <span class="dv">0.5</span><span class="op">;</span> <span class="co">// was 0.1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Two constants. No new mechanisms.</p>
<section id="what-the-change-did-at-20k" class="level3">
<h3 class="anchored" data-anchor-id="what-the-change-did-at-20k">What the change did at 20K</h3>
<p>The 20K trial (same stratified sub-sample as the first post, seed 42, 80/20 train/test) moved as expected:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Before (K=3, prior=0.1)</th>
<th>After (K=2, prior=0.5)</th>
<th>First post (K=2, calibrated)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AUC</td>
<td>0.5760</td>
<td><strong>0.6312</strong></td>
<td>0.6107</td>
</tr>
<tr class="even">
<td>Brier</td>
<td>0.1049</td>
<td>0.0979</td>
<td>0.0980</td>
</tr>
<tr class="odd">
<td>NLL</td>
<td>0.5259</td>
<td>0.3666</td>
<td>0.3435</td>
</tr>
<tr class="even">
<td>ECE</td>
<td>0.0573</td>
<td>0.0279</td>
<td>0.0101</td>
</tr>
<tr class="odd">
<td>Populated/total leaves</td>
<td>45 / 64</td>
<td>12 / 16</td>
<td>—</td>
</tr>
<tr class="even">
<td>Min/mean/max rows per leaf</td>
<td>1 / 355.5 / 1,583</td>
<td>428 / 1,333.2 / 3,462</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Routing cols (MI top-K)</td>
<td><code>[17, 9, 21]</code></td>
<td><code>[17, 9]</code></td>
<td>—</td>
</tr>
</tbody>
</table>
<div id="fig-auc-trajectory" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/traditional/auc_trajectory.png" class="img-fluid figure-img" alt="Bar chart showing AUC trajectory from 0.5760 (first post raw 20K) through 0.6107 (first post calibrated), 0.6312 (§4.A tuned), 0.6194 (§4.B pruned — negative result in red), 0.6621 (§4.E full 101K) to 0.6645 (§4.F 3-seed mean). Strong-published-model band (0.64-0.68) shaded in green; final two bars cross into it."></p>
<figcaption class="figure-caption">Figure&nbsp;2: Held-out test AUC across the full Round Two trajectory. The dashed grey line marks the first post’s calibrated 0.611; the green shaded band marks the strong-published-model band (0.64–0.68); the §4.B “negative result” bar (red/orange in cyberpunk) is the Locke-driven prune that <em>dropped</em> AUC; the final §4.F bar is the 3-seed mean with a ± std error bar (in green). The headline shifted from “tuned config helped” (§4.A) to “scale + config together cleared the strong-model band” (§4.E/F).</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The 20K result is <em>higher</em> than the first post’s
</div>
</div>
<div class="callout-body-container callout-body">
<p>The raw AUC 0.6312 is <strong>+0.020 above the first post’s published 0.6107</strong>. Two candidate causes:</p>
<ol type="1">
<li><strong>Different split protocol.</strong> The harness uses 80/20 train/test (n_train ≈ 15,999). The first post used 70/15/20 train/val/test (n_train ≈ 14,000). More training data → slightly higher AUC.</li>
<li><strong>Stratified sub-sample RNG path.</strong> The harness’s stratified-by-class sub-sample and the first post’s may differ in iteration order; same seed, different exact rows.</li>
</ol>
<p>This is itself instructive: <strong>the first post’s headline 0.611 is not the harness’s ceiling at that config.</strong> It was a defensible number under that protocol, but the same model with a different valid evaluation protocol lands higher.</p>
</div>
</div>
<p>Leaf utilisation is much better too: 12/16 populated (vs 45/64 = 70% before), and the smallest populated leaf has 428 rows (vs 1 — a single-row leaf where a BLR has essentially no information). The mean rises from 355 to 1,333 — every leaf now has enough data to train a meaningful posterior.</p>
<p><code>time_in_hospital</code> and <code>num_inpatient</code> are the MI-selected routing features at 20K. We’ll come back to that in §5 — they don’t stay the winners at full scale.</p>
</section>
</section>
<section id="lockes-audit-142-findings-one-critical-negative-result" class="level2">
<h2 class="anchored" data-anchor-id="lockes-audit-142-findings-one-critical-negative-result">4. Locke’s audit — 142 findings, one critical negative result</h2>
<p>Before scaling up the data, the brief said: <strong>run Locke</strong>. Audit the full 101,766-row CSV. Use the findings to drop leakage rows before training. Expected AUC bump: 0.62–0.63 from the prune alone.</p>
<p>The Locke run is one CLI invocation:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">./target/release/cjcl.exe</span> locke validate <span class="dt">\</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    tests/data/diabetes_130/diabetic_data.csv <span class="dt">\</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">--target</span> readmitted <span class="dt">\</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">--primary-key</span> patient_nbr <span class="dt">\</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">--save-json</span> bench_results/diabetes_phase_0_10_section_4b/diabetes_locke_baseline.json <span class="dt">\</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">--html</span>        bench_results/diabetes_phase_0_10_section_4b/diabetes_locke_baseline.html</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>It emits 142 findings:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Severity</th>
<th>Count</th>
<th>Worth acting on this session?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Error</td>
<td>1</td>
<td>YES (see §4.1 below — but it’s a structural concern, not a row filter)</td>
</tr>
<tr class="even">
<td>Warning</td>
<td>8</td>
<td>NO (E9082 near-duplicate categorical labels — <code>[0-25)</code> vs <code>[50-75)</code> etc.; real distinctions)</td>
</tr>
<tr class="odd">
<td>Notice</td>
<td>75</td>
<td>One worth acting on: E9072 ID-like cardinality (already handled by <code>Ignore</code> role)</td>
</tr>
<tr class="even">
<td>Info</td>
<td>58</td>
<td>E9002 type-only diagnostics</td>
</tr>
</tbody>
</table>
<div id="fig-findings-sunburst" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/traditional/locke_findings_sunburst.png" class="img-fluid figure-img" alt="Sunburst chart of 142 Locke findings. Centre ring divided into 4 wedges by severity (error tiny, warning small, notice largest, info large). Outer ring shows individual E-codes within each severity wedge — E9002 dominates info, E9073 dominates notice. E9063 absent."></p>
<figcaption class="figure-caption">Figure&nbsp;3: Sunburst of all 142 Locke findings. Inner ring: 4 severity levels (error 1, warning 8, notice 75, info 58). Outer ring: the 15 unique E-codes within each severity. <strong><code>notice</code> dominates by area</strong> — 75 findings, almost all of them E9073 (×44, duplicate-key disagreements — a single column’s worth of disagreement counted ~40 times across 40 columns) and E9011 (×15, high-cardinality categoricals). The single <code>error</code> (E9004) is the patient_nbr duplicate-key finding called out in §4.1. <strong>E9063 (multi-class leakage on <code>discharge_disposition_id</code>) is <em>not</em> in the sunburst</strong> — it never fired, which is itself the post’s load-bearing Locke finding.</figcaption>
</figure>
</div>
<div id="fig-locke-heatmap" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/traditional/locke_pearson_heatmap.png" class="img-fluid figure-img" alt="Pearson r heatmap, 6x6 grid of numeric columns: encounter_id, patient_nbr, admission_type_id, discharge_disposition_id, num_lab_procedures, diag_1. Diagonal cells are 1.00 in bold pink. The encounter_id × patient_nbr cell shows r=0.512 in lighter pink, called out with an arrow. All other off-diagonals are near-zero in dark teal."></p>
<figcaption class="figure-caption">Figure&nbsp;4: Pearson |r| heatmap — themed Plotly recreation of the actual SVG Locke emitted (raw verbatim version preserved at <a href="figures/locke/pearson_heatmap_raw.svg"><code>figures/locke/pearson_heatmap_raw.svg</code></a> for verification). The Pearson values are byte-identical to what <code>cjcl locke validate</code> produced. The only off-diagonal correlation that pops is <code>encounter_id</code> × <code>patient_nbr</code> (r = 0.512) — the patient-encounter overlap that E9004 separately flagged. Everything else is &lt; 0.16 in absolute value, consistent with the rest of the dataset’s heterogeneity.</figcaption>
</figure>
</div>
<p>The single Error is interesting and the negative result is more interesting. Let’s take them in order.</p>
<section id="e9004-the-leakage-hole-the-first-post-missed" class="level3">
<h3 class="anchored" data-anchor-id="e9004-the-leakage-hole-the-first-post-missed">4.1 E9004 — the leakage hole the first post missed</h3>
<pre class="text"><code>code=E9004 severity=error column=patient_nbr
  message: key column `patient_nbr` has 30248 duplicate values
           across 16773 groups
  evidence:
    - duplicate_keys=30248
    - duplicate_groups=16773</code></pre>
<p><strong>30,248 duplicate <code>patient_nbr</code> values across 16,773 groups</strong> — i.e.&nbsp;16,773 patients had multiple hospital encounters in the dataset. This is correct medical data (real patients return), but it creates a leakage path: if the train/test split is <em>row-level</em> (encounter-level), the same patient can appear in both splits. The model can then learn features about that patient and “look up” their outcome in the test set.</p>
<p>The first post used row-level splitting. So did this Round Two. <strong>A truly leakage-free protocol would split by <code>patient_nbr</code></strong>, which would reduce effective training data (more conservative splits typically do) but would tighten the leakage story.</p>
<p>Locke surfaced this without running a single model. AUC numbers wouldn’t have shown it. Whether the encounter-level result is “real signal” or “partial patient-memorisation” can only be decided by re-running with a patient-level split — recorded as future work in §10.</p>
</section>
<section id="e9063-the-predicted-leakage-finding-that-didnt-fire" class="level3">
<h3 class="anchored" data-anchor-id="e9063-the-predicted-leakage-finding-that-didnt-fire">4.2 E9063 — the predicted leakage finding that didn’t fire</h3>
<p>The handoff predicted that <strong>E9063 (multi-class target leakage)</strong> would fire on <code>discharge_disposition_id</code>. The reasoning: codes 11, 13, 14, 19, 20, 21 in that column correspond to <em>death</em> and <em>hospice</em> outcomes. A dead patient can’t be readmitted by construction; those rows are deterministically <code>readmitted = NO</code>. Leakage.</p>
<p>E9063 did not fire. Looking at the detector’s logic (<a href="https://github.com/AdamEzzat1/CJC/blob/master/crates/cjc-locke/src/leakage.rs">crates/cjc-locke/src/leakage.rs:229</a>), the reason becomes clear: E9063 uses <strong>per-feature ROC-AUC</strong> (max one-vs-rest) against the multi-class target. Death codes (11, 13, 14, 19, 20, 21) sit <em>interspersed</em> in the numeric range with non-death codes (12, 15, 16, 17, 18). So the column-wide rank statistic doesn’t separate cleanly — most non-death codes also predict <code>NO</code> (89% base rate), so the AUC stays below the 0.85 warning threshold.</p>
<p><strong>The leakage exists at the level — “code 11 → NO with probability ~1.0” — not at the column.</strong> ROC-AUC can’t see level-by-level conditional probability.</p>
<p>This is itself a publishable Locke result. A concrete detector gap, pinned to a concrete real-world example:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Proposed E9064 — per-level conditional-probability leakage detector
</div>
</div>
<div class="callout-body-container callout-body">
<p>For each <code>(column, level, target_class)</code> triple, compute P(target = class | column = level). Flag when:</p>
<ul>
<li><code>P(class \| level) ≥ 0.99</code> with at least N supports</li>
<li>And <code>P(class)</code> (unconditional) <code>&lt; 0.99</code> — i.e.&nbsp;the level adds <em>new</em> information</li>
</ul>
<p>This would catch the discharge-code pattern and analogous per-level deterministic-outcome leakages: specific procedure codes that always predict survival, specific lab values that always predict a diagnosis, specific zip codes that always predict insurance class, etc. The data is structured this way more often than column-wide rank-sum detectors admit.</p>
<p>Recorded as a Locke roadmap item with this dataset as the canonical motivating example.</p>
</div>
</div>
</section>
<section id="we-applied-the-prune-anyway-and-auc-dropped" class="level3">
<h3 class="anchored" data-anchor-id="we-applied-the-prune-anyway-and-auc-dropped">4.3 We applied the prune anyway — and AUC dropped</h3>
<p>Domain knowledge still says drop the death-discharge rows. The detector missed; we know better; filter and retry.</p>
<p>Added <code>filter_out_death_discharges</code> in the harness — drops rows where <code>discharge_disposition_id ∈ {11, 13, 14, 19, 20, 21}</code>. That’s <strong>2,423 of 101,766 rows (2.38%)</strong>, all <code>readmitted = NO</code>. After the filter, the positive-class proportion rises slightly (11.16% → 11.43%).</p>
<p>Re-ran the 20K trial at the same config (K=2, prior=0.5, seed 42):</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>§4.A (no prune)</th>
<th>§4.B (with prune)</th>
<th>Δ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AUC</td>
<td><strong>0.6312</strong></td>
<td><strong>0.6194</strong></td>
<td><strong>−0.0118</strong></td>
</tr>
<tr class="even">
<td>Brier</td>
<td>0.0979</td>
<td>0.0993</td>
<td>+0.0014</td>
</tr>
<tr class="odd">
<td>NLL</td>
<td>0.3666</td>
<td>0.3680</td>
<td>+0.0014</td>
</tr>
<tr class="even">
<td>ECE</td>
<td>0.0279</td>
<td>0.0229</td>
<td>−0.0050</td>
</tr>
<tr class="odd">
<td>Bal. accuracy</td>
<td>0.5084</td>
<td>0.5094</td>
<td>+0.0010</td>
</tr>
<tr class="even">
<td><strong>Routing cols (MI top-K)</strong></td>
<td><strong><code>[17, 9]</code></strong></td>
<td><strong><code>[17, 16]</code></strong></td>
<td><strong>CHANGED</strong></td>
</tr>
<tr class="odd">
<td>Populated leaves</td>
<td>12 / 16</td>
<td>6 / 16</td>
<td>−6</td>
</tr>
<tr class="even">
<td>Mean rows/leaf</td>
<td>1,333</td>
<td>2,667</td>
<td>+1,334</td>
</tr>
</tbody>
</table>
<p><strong>Removing leakage rows hurt the model.</strong> That looks paradoxical until you read the bottom of the table: the MI-selected routing columns changed. Before the prune, the top-K=2 routing features were <code>[17, 9]</code> = <code>num_inpatient</code> + <code>time_in_hospital</code>. After the prune, they shifted to <code>[17, 16]</code> = <code>num_inpatient</code> + <code>number_emergency</code>. <code>time_in_hospital</code> was a stronger routing feature than <code>number_emergency</code> at 20K — when the prune removes the correlation between <code>time_in_hospital</code> and the target (death patients had specific hospital-stay durations), the MI selector picks the next best feature, which happens to be less useful.</p>
<p>This is a <strong>confounded experiment</strong>. The §4.B intervention affects both (i) leakage row removal and (ii) downstream routing-feature selection. To isolate (i), you’d need to <em>force</em> the same routing columns across both configs — override the MI selector. That’s not in §4.B’s scope; this is now a documented finding for the next experiment campaign.</p>
<div id="fig-confounded-flow" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/traditional/confounded_experiment_flow.png" class="img-fluid figure-img" alt="Flow diagram. Top yellow box: §4.B intervention (drop discharge codes 11,13,14,19,20,21, −2,423 rows). Two arrows branch down to: green Effect A box (Leakage rows removed) and orange Effect B box (MI re-selects routing features, time_in_hospital → number_emergency). Both arrows converge into a bottom orange Net Effect box (AUC drops 0.6312 → 0.6194, routing-feature loss > leakage-removal gain, marked as confounded experiment)."></p>
<figcaption class="figure-caption">Figure&nbsp;5: §4.B confounded-experiment flow. The prune does two things at once: <strong>Effect A</strong> removes the leakage rows (which would help on its own), but <strong>Effect B</strong> shifts the MI-selected routing-feature pair from <code>[num_inpatient, time_in_hospital]</code> to <code>[num_inpatient, number_emergency]</code> — a strictly weaker top-K=2 pair at 20K. The downstream MI shift dominated the leakage-removal gain. The footnote captures the deeper insight: the same MI pair <code>[num_inpatient, number_emergency]</code> wins at 101K scale anyway (§5.2), so Effect B was about to happen as data scaled. §4.B surfaced it early.</figcaption>
</figure>
</div>
<p>But there’s a more interesting insight in the routing change: <code>[17, 16]</code> is the <em>same</em> routing pair the model picks at full 101K scale (§5 below). Removing the leakage rows at 20K shifts MI in the same direction <em>scaling up</em> shifts it. The §4.B negative result is, in part, MI selection drift that was about to happen anyway.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What this means for the handoff hypothesis
</div>
</div>
<div class="callout-body-container callout-body">
<p>The handoff said “Locke surfaces E9063 → drop death rows → AUC up to 0.62–0.63.” Of the three steps:</p>
<ul>
<li><strong>Locke surfaces E9063</strong> — didn’t happen (§4.2; the detector misses this pattern).</li>
<li><strong>Drop death rows</strong> — happened anyway via domain knowledge.</li>
<li><strong>AUC up to 0.62–0.63</strong> — didn’t happen; AUC went <em>down</em> by 0.012.</li>
</ul>
<p>Three falsified predictions chained — each one its own finding. The chain doesn’t work in this form on this dataset. Whether it works at all on this model class is an open question — see §10.</p>
</div>
</div>
</section>
</section>
<section id="full-101k-multi-seed-the-headline" class="level2">
<h2 class="anchored" data-anchor-id="full-101k-multi-seed-the-headline">5. Full 101K, multi-seed — the headline</h2>
<p>The first post left “the full 101,766-row run at the tuned configuration” as future work. §4.E delivers it.</p>
<section id="single-seed-at-full-scale" class="level3">
<h3 class="anchored" data-anchor-id="single-seed-at-full-scale">5.1 Single seed at full scale</h3>
<p>One call to the existing <code>diabetes130_full_run</code> test (which uses <code>budget = usize::MAX</code>, i.e.&nbsp;the entire dataset). Wall clock 213.84 s (≈ 3.6 min). Seed 42.</p>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>§4.E (full 101K)</th>
<th>§4.A (20K)</th>
<th>First post (calibrated, 20K)</th>
<th>Strong-model band</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>AUC</strong></td>
<td><strong>0.6621</strong></td>
<td>0.6312</td>
<td>0.611</td>
<td>0.64–0.68 ✓</td>
</tr>
<tr class="even">
<td>Brier</td>
<td><strong>0.0953</strong></td>
<td>0.0979</td>
<td>0.098</td>
<td>—</td>
</tr>
<tr class="odd">
<td>NLL</td>
<td><strong>0.3349</strong></td>
<td>0.3666</td>
<td>0.344</td>
<td>—</td>
</tr>
<tr class="even">
<td>ECE</td>
<td><strong>0.0044</strong></td>
<td>0.0279</td>
<td>0.010</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Balanced accuracy</td>
<td>0.5012</td>
<td>0.5084</td>
<td>~0.58</td>
<td>—</td>
</tr>
<tr class="even">
<td>F1 @ threshold = 0.5</td>
<td>0.0061</td>
<td>0.0385</td>
<td>~0.24</td>
<td>—</td>
</tr>
<tr class="odd">
<td>n_train</td>
<td>81,412</td>
<td>15,999</td>
<td>~14,000</td>
<td>—</td>
</tr>
<tr class="even">
<td>Chain head</td>
<td><code>56af1961…b3233b6</code></td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><strong>AUC 0.6621 — in the strong-published-model band (0.64–0.68)</strong>. Without any architectural change. Without calibration. Still on the linear BLR head.</p>
<p>The calibration metrics (Brier 0.0953, NLL 0.3349, ECE 0.0044) are all <strong>better than the first post’s <em>calibrated</em> values</strong> (0.098 / 0.344 / 0.010) — and that comparison is against post-Platt numbers, while these are <em>raw</em>. The increased data volume at the same model class produces raw outputs that are already well-calibrated.</p>
<p>The first post predicted: “Calibration is a monotonic transform, so it <em>cannot</em> change the ranking, and it didn’t… A nonlinear MLP-leaf-head variant is the next experiment — it may lift AUC, or may need a lot of tuning.”</p>
<p>The implication was that <strong>AUC ≥ 0.64 required the MLP</strong>. It did not. Data scale was enough.</p>
</section>
<section id="routing-columns-flipped-at-full-scale" class="level3">
<h3 class="anchored" data-anchor-id="routing-columns-flipped-at-full-scale">5.2 Routing columns flipped at full scale</h3>
<p>The MI-selected routing features at full 101K are <code>[17, 16]</code> — <code>num_inpatient</code> + <code>number_emergency</code>. Not <code>[17, 9]</code> (which won at 20K).</p>
<div id="fig-mi-routing" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/traditional/mi_routing_scale.png" class="img-fluid figure-img" alt="Two horizontal bar charts side by side. Left: 20K trial ranks num_inpatient and time_in_hospital as the top 2 selected features. Right: 101K full ranks num_inpatient and number_emergency as the top 2; time_in_hospital drops to position 3 and is not selected."></p>
<figcaption class="figure-caption">Figure&nbsp;6: MI-ranked routing features at 20K (§4.A) and 101K (§4.E). At 20K, <code>time_in_hospital</code> is ranked #2 — selected. At 101K, <code>number_emergency</code> overtakes it for the #2 slot and <code>time_in_hospital</code> falls to #3 — <em>not</em> selected. <code>num_inpatient</code> holds the #1 slot across both scales. This is the architecture’s MI selector doing automatic feature adaptation — no human tuning, just more data revealing a different optimal feature pair.</figcaption>
</figure>
</div>
<p>The flip happens because <code>time_in_hospital</code>’s MI advantage over <code>number_emergency</code> is small at 20K and disappears with more data:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Scale</th>
<th>Routing cols (MI top-2)</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>20K, no prune</td>
<td><code>[17, 9]</code></td>
<td>time_in_hospital edges out at small scale</td>
</tr>
<tr class="even">
<td>20K, with prune (§4.B)</td>
<td><code>[17, 16]</code></td>
<td>Removing death rows kills time_in_hospital’s MI</td>
</tr>
<tr class="odd">
<td><strong>101K, full</strong></td>
<td><strong><code>[17, 16]</code></strong></td>
<td>At scale, number_emergency wins on its own</td>
</tr>
</tbody>
</table>
<p><strong>This is the architecture’s MI selector doing real work.</strong> It picked a different feature pair at a different scale, automatically, no human intervention. Whether <code>time_in_hospital</code> would re-emerge at, say, 50K is an interesting probe — the threshold at which the two cross over is measurable.</p>
</section>
<section id="three-seeds-putting-an-error-bar-on-the-headline" class="level3">
<h3 class="anchored" data-anchor-id="three-seeds-putting-an-error-bar-on-the-headline">5.3 Three seeds — putting an error bar on the headline</h3>
<p>A single-seed result is dangerous. §4.F ran the same full-101K pipeline at seeds 42, 43, 44. Wall clock 610.77 s for three runs (~10 min total).</p>
<table class="table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Mean ± Std (n=3)</th>
<th>seed 42</th>
<th>seed 43</th>
<th>seed 44</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>AUC</strong></td>
<td><strong>0.6645 ± 0.0018</strong></td>
<td>0.6621</td>
<td>0.6664</td>
<td>0.6649</td>
</tr>
<tr class="even">
<td>Brier</td>
<td>0.0950 ± 0.0002</td>
<td>0.0953</td>
<td>0.0948</td>
<td>0.0950</td>
</tr>
<tr class="odd">
<td>NLL</td>
<td>0.3346 ± 0.0004</td>
<td>0.3349</td>
<td>0.3340</td>
<td>0.3347</td>
</tr>
<tr class="even">
<td>ECE</td>
<td>0.0038 ± 0.0006</td>
<td>0.0044</td>
<td>0.0030</td>
<td>0.0041</td>
</tr>
<tr class="odd">
<td>Bal. accuracy</td>
<td>0.5019 ± 0.0008</td>
<td>0.5012</td>
<td>0.5015</td>
<td>0.5030</td>
</tr>
<tr class="even">
<td>F1 @ 0.5</td>
<td>0.0087 ± 0.0031</td>
<td>0.0061</td>
<td>0.0070</td>
<td>0.0130</td>
</tr>
</tbody>
</table>
<p>The variance is <strong>tiny — 0.0018 = 0.27% of the AUC mean</strong>. The seed-42 single-seed result (0.6621) was actually <em>below</em> the 3-seed mean (0.6645). Without the multi-seed pass, the single-seed headline understated the model.</p>
<p>All three seeds picked the <strong>same routing pair</strong> (<code>[17, 16]</code>). Structural decisions are pinned by scale; the per-seed noise is purely the held-out-test stratified sample.</p>
<div id="fig-multi-seed" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/traditional/multi_seed_variance.png" class="img-fluid figure-img" alt="Six-panel grid showing per-metric multi-seed variance. AUC, Brier, NLL, ECE, Bal. accuracy, F1 @ 0.5. Each panel shows 3 seed points + mean line + shaded ± std band. Variances are tight on AUC/Brier/NLL/ECE/Bal.acc and looser on F1."></p>
<figcaption class="figure-caption">Figure&nbsp;7: Multi-seed variance — six panels, one per reported metric. Each panel shows three coloured dots (one per seed: 42 pink, 43 orange, 44 green-ish), the dashed mean line, and a shaded ± std band. AUC’s tight 0.0018 std (0.27% of mean) is the headline — seed 42 (the §4.E single-seed result) was actually <em>below</em> the 3-seed mean by half a sigma. F1 at fixed threshold 0.5 has the noisiest relative variance (36% of mean) — a threshold-sensitivity artifact, not a model issue.</figcaption>
</figure>
</div>
<p>Each seed’s chain head is reproducible bit-for-bit:</p>
<pre class="text"><code>seed 42: chain = 56af19614b4dfff6 df97c53949668765 acdc045e316e4fed 087a8a5d9b3233b6
seed 43: chain = 590c3fb936cec418 91576128b82e7243 dc399d6ca49a845c 87bb7392ddb45f7d
seed 44: chain = 89e02f56dadbb651 39418e0ecd3536c0 096b4851ae099694 f3736912ecde2bb2</code></pre>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
On F1’s higher relative variance
</div>
</div>
<div class="callout-body-container callout-body">
<p>F1 has the noisiest std (36% of mean — 0.0087 ± 0.0031), and the absolute number is low (0.0087 vs the first post’s calibrated 0.24). Both come from the fixed decision threshold (0.5) on extreme class imbalance — small probability-space shifts at the threshold flip many predictions. The first post tuned the threshold on validation per seed (which got it to ~0.24); we didn’t redo that this session. A per-seed validation-tuned threshold would tighten F1 back to the blog’s number without changing AUC, Brier, or NLL.</p>
<p><strong>This is a reporting choice, not an architectural one.</strong> F1 at threshold-0.5 is honest but unflattering; the per-seed-tuned version is honest <em>and</em> the right operating-point report. Both are valid; we deferred the threshold tuning to keep §4.F’s wall clock manageable.</p>
</div>
</div>
</section>
<section id="the-honest-comparison-vs-the-first-post" class="level3">
<h3 class="anchored" data-anchor-id="the-honest-comparison-vs-the-first-post">5.4 The honest comparison vs the first post</h3>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>First post (calibrated, 20K, seed 42)</th>
<th>This post (raw, 101K, 3-seed mean)</th>
<th>Δ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AUC</td>
<td>0.611</td>
<td><strong>0.6645 ± 0.0018</strong></td>
<td><strong>+0.054</strong></td>
</tr>
<tr class="even">
<td>Brier</td>
<td>0.098</td>
<td><strong>0.0950 ± 0.0002</strong></td>
<td>−0.003</td>
</tr>
<tr class="odd">
<td>NLL</td>
<td>0.344</td>
<td><strong>0.3346 ± 0.0004</strong></td>
<td>−0.009</td>
</tr>
<tr class="even">
<td>ECE</td>
<td>0.010</td>
<td><strong>0.0038 ± 0.0006</strong></td>
<td>−0.006</td>
</tr>
</tbody>
</table>
<p>The new numbers beat the first post on every probabilistic axis <em>without</em> Platt calibration. The +0.054 AUC lift is the main story; it puts ABNG in the strong-published-model band on its linear-only configuration.</p>
<div id="fig-calibration" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/traditional/calibration_first_vs_round_two.png" class="img-fluid figure-img" alt="Three side-by-side bar charts: Brier, NLL, ECE. Each compares First post (Platt calibrated, 20K) in grey vs Round Two (raw, 101K, n=3) in blue. Round Two beats first post in all three panels. Base-rate baseline shown with dashed line on Brier and NLL panels; both bars beat the base rate."></p>
<figcaption class="figure-caption">Figure&nbsp;8: Round Two’s raw calibration metrics vs the first post’s <em>Platt-calibrated</em> metrics. In all three panels, Round Two beats the first post — Brier 0.0950 vs 0.0980, NLL 0.3346 vs 0.3435, ECE 0.0038 vs 0.0101 — <em>without applying any calibration step</em>. The dashed orange line marks the base-rate predictor (output the 11.2% positive rate for everyone); both bars beat it on Brier and NLL. The increased data volume produces raw outputs that are already well-calibrated, so Platt scaling is no longer required for “beats base-rate” honesty.</figcaption>
</figure>
</div>
<p>The first post said:</p>
<blockquote class="blockquote">
<p>A nonlinear MLP-leaf-head variant is the next experiment — it may lift AUC, or may need a lot of tuning.</p>
</blockquote>
<p>It turns out the <strong>bigger lever was data scale, not architecture</strong>. We’ll come back to that in §9.</p>
</section>
</section>
<section id="the-locke--sentinel-saga-and-4.d" class="level2">
<h2 class="anchored" data-anchor-id="the-locke--sentinel-saga-and-4.d">6. The Locke <code>?</code>-sentinel saga and §4.D</h2>
<p>Section 4 of the brief asked for a different Locke contribution: <strong>belief-weighted per-leaf BLR priors</strong>. The hypothesis (from <a href="https://github.com/AdamEzzat1/CJC/blob/master/docs/locke/ABNG_PER_LEAF_BELIEF.md"><code>docs/locke/ABNG_PER_LEAF_BELIEF.md</code></a>): score each leaf with Locke’s <code>BeliefScore</code> and weight the per-leaf prior accordingly — strong belief → light regularization, weak belief → tight regularization. Operationalises the idea that data-quality variation across the routing tree should drive per-leaf prior strength.</p>
<p>Two blockers surfaced. Part 1 fixed one of them. Part 2 needs ABNG changes that didn’t happen this session.</p>
<section id="locke-didnt-see-as-missing" class="level3">
<h3 class="anchored" data-anchor-id="locke-didnt-see-as-missing">6.1 Locke didn’t see <code>?</code> as missing</h3>
<p>Running the existing per-leaf belief experiment (<code>tests/abng/per_leaf_belief_diabetes130.rs</code>) produced a per-leaf BeliefScore CSV where <strong>every leaf had <code>missingness_score = 1.0000</code></strong>:</p>
<pre class="csv"><code>leaf_id,n_rows,overall,schema,missingness,drift,leakage,lineage,sample,duplication,constraint
1,9617,0.902500,0.340000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.880000
2,6215,0.905000,0.360000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.880000
3,2545,0.902500,0.360000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.860000
4,1623,0.902500,0.360000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.860000</code></pre>
<p>Locke is saying: <strong>no missingness detected on any leaf</strong>. On a dataset where <code>weight</code> is 96.9% <code>?</code>.</p>
<p>The cause is in Locke’s default <code>ValidationConfig</code>: it treats only <strong>f64::NAN</strong> as missing for Float columns and produces info-only diagnostics for Str columns (they get an E9002 <code>no null mask supplied</code> notice). Diabetes-130 stores its missing values as the literal string <code>?</code> — Locke doesn’t see them without explicit configuration.</p>
</section>
<section id="the-fix-nullmaskmap-plumbing" class="level3">
<h3 class="anchored" data-anchor-id="the-fix-nullmaskmap-plumbing">6.2 The fix — <code>NullMaskMap</code> plumbing</h3>
<p>§4.D Part 1 added a harness-side helper that scans every <code>Str</code> column for <code>?</code> and builds a <code>NullMaskMap</code>:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode rust code-with-copy"><code class="sourceCode rust"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">fn</span> build_question_mark_null_masks(df<span class="op">:</span> <span class="op">&amp;</span>DataFrame) <span class="op">-&gt;</span> NullMaskMap <span class="op">{</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">let</span> <span class="kw">mut</span> out <span class="op">=</span> <span class="pp">NullMaskMap::</span>new()<span class="op">;</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (name<span class="op">,</span> col) <span class="kw">in</span> df<span class="op">.</span>columns<span class="op">.</span>iter() <span class="op">{</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="kw">let</span> <span class="pp">Column::</span><span class="bu">Str</span>(values) <span class="op">=</span> col <span class="op">{</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>            <span class="kw">let</span> null_rows<span class="op">:</span> <span class="dt">Vec</span><span class="op">&lt;</span><span class="dt">usize</span><span class="op">&gt;</span> <span class="op">=</span> values<span class="op">.</span>iter()<span class="op">.</span>enumerate()</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>                <span class="op">.</span>filter_map(<span class="op">|</span>(i<span class="op">,</span> v)<span class="op">|</span> <span class="cf">if</span> v <span class="op">==</span> <span class="st">"?"</span> <span class="op">{</span> <span class="cn">Some</span>(i) <span class="op">}</span> <span class="cf">else</span> <span class="op">{</span> <span class="cn">None</span> <span class="op">}</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                <span class="op">.</span>collect()<span class="op">;</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="op">!</span>null_rows<span class="op">.</span>is_empty() <span class="op">{</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>                out<span class="op">.</span>insert(name<span class="op">.</span>clone()<span class="op">,</span> <span class="pp">NullMask::</span>from_indices(null_rows))<span class="op">;</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>            <span class="op">}</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>        <span class="op">}</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="op">}</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    out</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Then thread it through <code>ValidateOptions.null_masks</code>. Re-ran the per-leaf belief:</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Naive (no null masks)</th>
<th><code>?</code>-aware</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>weight</code> recognised as <code>?</code>-heavy</td>
<td>NO</td>
<td>YES (96.9% rate)</td>
</tr>
<tr class="even">
<td>Columns flagged with <code>?</code></td>
<td>0</td>
<td>7</td>
</tr>
<tr class="odd">
<td>Min per-leaf <code>missingness_score</code></td>
<td>1.0000</td>
<td><strong>0.9613</strong></td>
</tr>
<tr class="even">
<td>Min per-leaf <code>overall</code></td>
<td>0.9025</td>
<td>0.8977</td>
</tr>
</tbody>
</table>
<p>The belief vector is now informative. Seven columns are correctly flagged as <code>?</code>-bearing, including <code>weight</code> at 96.9% — matching the first post’s “weight is ~97% missing” observation.</p>
<div id="fig-belief-radar" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/traditional/per_leaf_belief_radar.png" class="img-fluid figure-img" alt="Polar radar chart with 8 axes (schema, missingness, drift, leakage, lineage, sample, duplication, constraint). Two overlapping filled polygons: naive Locke (grey) and ?-aware (blue). The polygons overlap almost entirely except at the missingness axis, where the blue ?-aware polygon dents inward (0.9621) while the grey naive one stays at 1.0. The schema axis at the right shows a deep concave (0.34) on both polygons — Locke's schema_score is genuinely low on this dataset."></p>
<figcaption class="figure-caption">Figure&nbsp;9: §4.D Part 1’s effect on leaf 1’s 8-axis BeliefScore vector (n=9,617 rows, the largest leaf). The naive Locke polygon (grey, with default <code>ValidationConfig</code>) is mostly perfect — <code>missingness</code> at the top sits at the outermost ring (1.0 = “no missingness detected”). The <code>?</code>-aware polygon (blue) is <em>identical</em> on every axis except <code>missingness</code>, where it dents inward to 0.9621 — Locke now sees <code>?</code> strings as missing. That dent is the §4.D Part 1 fix made visible: targeted (one axis), not noisy (other axes unmoved). The deep concave at the right (<code>schema = 0.34</code>) is real Locke schema-concern data, present on both polygons.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A Locke roadmap item, concretely motivated
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Locke should auto-detect common missing-value sentinels.</strong> <code>?</code>, <code>NA</code>, <code>-</code>, <code>NULL</code>, empty string — these are common conventions in medical, financial, and scientific CSVs. Requiring every harness to build a <code>NullMaskMap</code> manually is friction; the cost of false-positive sentinel detection is low (the user can override) and the cost of false-negative is what this section just walked through (a 97%-missing column treated as perfectly clean).</p>
<p>The §4.D Part 1 fix is a one-helper-function workaround that should be in Locke itself. Recorded as a roadmap item.</p>
</div>
</div>
</section>
<section id="the-deeper-problem-leaves-clustered-at-uniform-belief" class="level3">
<h3 class="anchored" data-anchor-id="the-deeper-problem-leaves-clustered-at-uniform-belief">6.3 The deeper problem — leaves clustered at uniform belief</h3>
<p>With <code>?</code>-handling fixed, the per-leaf belief vector is informative <em>per axis</em>, but <strong>all four leaves cluster at near-identical missingness_score</strong>:</p>
<div id="fig-per-leaf-belief" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/traditional/per_leaf_belief_question_marks.png" class="img-fluid figure-img" alt="Grouped bar chart, 4 leaves × 2 bars each. Grey bars (Naive Locke default): all four leaves show missingness_score = 1.0000. Blue bars (?-aware with NullMaskMap): leaves at 0.9621, 0.9624, 0.9621, 0.9613. A green dashed line at y=1.0 labels 'Perfect (no missingness detected)'."></p>
<figcaption class="figure-caption">Figure&nbsp;10: §4.D Part 1 — Locke per-leaf <code>missingness_score</code> with default config (grey, all 1.0000 — meaning “no missingness detected, all clean”) vs with the <code>?</code>-aware <code>NullMaskMap</code> threaded in (blue, 0.961–0.962). The fix gives Locke an informative signal on this dataset. The remaining problem is visible in the bars: spread across leaves is only ~0.001, because the simple 1-D codebook over <code>time_in_hospital</code> doesn’t separate leaves on data quality — the 97% <code>?</code> rate in <code>weight</code> is roughly uniform across hospital-stay durations.</figcaption>
</figure>
</div>
<table class="table">
<thead>
<tr class="header">
<th>leaf_id</th>
<th>n_rows</th>
<th>missingness_score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>9,617</td>
<td>0.9621</td>
</tr>
<tr class="even">
<td>2</td>
<td>6,215</td>
<td>0.9624</td>
</tr>
<tr class="odd">
<td>3</td>
<td>2,545</td>
<td>0.9621</td>
</tr>
<tr class="even">
<td>4</td>
<td>1,623</td>
<td>0.9613</td>
</tr>
</tbody>
</table>
<p><strong>Spread: 0.001.</strong> All four leaves are within one-tenth of a percent. That’s because the routing column (<code>time_in_hospital</code>, in this simplified 1-D codebook) doesn’t correlate with data-quality variation. The 97% <code>?</code> rate in <code>weight</code> is roughly uniform across hospital-stay durations.</p>
<p>For §4.D Part 2 (the actual belief-weighted prior experiment) to <em>do anything</em>, the leaves need to <em>differ</em> on belief. They don’t, on this routing. The directional hypothesis from <code>ABNG_PER_LEAF_BELIEF.md</code> is operationally a no-op when all leaves get the same belief multiplier.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Routing-vs-belief alignment — a research question
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Target-MI routing optimises for predictive separation.</strong> It picks the features that most reduce uncertainty about the target.</p>
<p><strong>Data-quality routing would optimise for belief separation.</strong> It would pick features that most stratify by data quality — different missingness profiles, different correlation structures, different conditional drift.</p>
<p><strong>These are not the same objective.</strong> §4.D Part 2 implicitly assumes they align. On this dataset they don’t. Whether they align in general is an open question — it might be that some datasets have data-quality variation that <em>also</em> predicts the target (e.g., underreported labs in a poorly-documented patient subset), in which case the same routing serves both purposes. Or they might be orthogonal, in which case you need separate routing for each.</p>
<p>This is a research-direction question Locke and ABNG together can answer, but neither can answer alone. <strong>It needs ABNG to expose a per-leaf prior API and a way to feed belief into routing decisions.</strong> Both are multi-session architectural work.</p>
</div>
</div>
</section>
<section id="part-2-deferred-for-a-real-reason" class="level3">
<h3 class="anchored" data-anchor-id="part-2-deferred-for-a-real-reason">6.4 Part 2 — deferred for a real reason</h3>
<p>§4.D Part 2 (apply the belief-weighted prior) requires changes to ABNG’s <code>set_blr_prior</code>:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode rust code-with-copy"><code class="sourceCode rust"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">// Current API — graph-wide, one-shot, must be called before any add_node.</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="kw">pub</span> <span class="kw">fn</span> set_blr_prior(</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="op">&amp;</span><span class="kw">mut</span> <span class="kw">self</span><span class="op">,</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    precision<span class="op">:</span> <span class="dt">f64</span><span class="op">,</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    a<span class="op">:</span> <span class="dt">f64</span><span class="op">,</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    b<span class="op">:</span> <span class="dt">f64</span><span class="op">,</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> <span class="dt">Result</span><span class="op">&lt;</span>()<span class="op">,</span> GraphError<span class="op">&gt;</span> <span class="op">{</span> <span class="op">...</span> <span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>There’s no <code>set_blr_prior_for_node(node_id, precision, a, b)</code>. Adding one would touch:</p>
<ol type="1">
<li>Public API surface (new method on <code>AdaptiveBeliefGraph</code>).</li>
<li>Lifecycle relaxation (must work after <code>add_node</code>, not before).</li>
<li>A new <code>AuditKind::BlrLeafPriorOverride</code> variant for the audit chain.</li>
<li>New SHA-256 canary locks for that event type.</li>
</ol>
<p>Multi-session work, at the same scope as §4.C MLP heads. <strong>Deferred — see §10.</strong></p>
<p>The §4.D Part 1 work is still a real Locke contribution: it makes the per-leaf belief informative on <code>?</code>-sentinel datasets. The pre-blocker is resolved. The actual experiment (Part 2) is waiting on ABNG architecture work plus the routing-vs-belief alignment question being settled.</p>
</section>
</section>
<section id="c-mlp-heads-design-only" class="level2">
<h2 class="anchored" data-anchor-id="c-mlp-heads-design-only">7. §4.C MLP heads — design only</h2>
<p>The first post named <strong>nonlinear MLP leaf heads</strong> as the explicit “ranking ceiling” lever. The implicit claim: the linear BLR is the ceiling, calibration can’t move ranking, so to break the 0.611 AUC ceiling you need an MLP head.</p>
<p>§5 of this post already invalidated that framing — full data scale moved AUC into the strong band on the linear head. But MLP heads would still plausibly push higher (0.66 → ~0.68). So the brief asked to <em>start</em> §4.C this session.</p>
<p>The exploration produced a <a href="https://github.com/AdamEzzat1/CJC/blob/master/docs/abng/PHASE_0_10_SECTION_4C_DESIGN.md">design doc</a> and one critical finding: <strong>the MLP forward infrastructure already exists in cjc-abng.</strong></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode rust code-with-copy"><code class="sourceCode rust"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">// crates/cjc-abng/src/leaf_head.rs:30</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="kw">pub</span> <span class="kw">struct</span> LeafHead <span class="op">{</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> input_dim<span class="op">:</span> <span class="dt">u32</span><span class="op">,</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> hidden_dims<span class="op">:</span> <span class="dt">Vec</span><span class="op">&lt;</span><span class="dt">u32</span><span class="op">&gt;,</span>   <span class="co">// ← already supports MLP layers</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> output_dim<span class="op">:</span> <span class="dt">u32</span><span class="op">,</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> activation<span class="op">:</span> Activation<span class="op">,</span>  <span class="co">// ← Tanh/Sigmoid/Relu/None/Gelu/Silu/Elu/Selu/SinAct</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="kw">pub</span> config_hash<span class="op">:</span> [<span class="dt">u8</span><span class="op">;</span> <span class="dv">32</span>]<span class="op">,</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><code>LeafHead::new(in_dim, hidden_dims, out_dim, activation)</code> accepts a <code>Vec&lt;u32&gt;</code> of hidden layer widths. The harness’s call is <code>set_leaf_head(phi_width, vec![], 1, Activation::None)</code> — <strong>empty hidden_dims</strong>, so the BLR sits directly on raw φ. Setting <code>vec![32]</code> and <code>Activation::Relu</code> would build a 2-layer MLP.</p>
<p><code>leaf_forward(node_id, x_idx)</code> (<a href="https://github.com/AdamEzzat1/CJC/blob/master/crates/cjc-abng/src/graph.rs">graph.rs:1386</a>) already runs the MLP forward inside a <code>cjc-ad::GradGraph</code>, walking layers and applying <code>g.mlp_layer(input, w, b, activation)</code> per layer. <code>leaf_set_param</code> and <code>leaf_set_params_batch</code> already exist for writing trained weights back, and they’re already canary-locked under the existing audit chain.</p>
<p>What’s <em>missing</em>: a training driver. The harness’s <code>train_step</code> (<a href="https://github.com/AdamEzzat1/CJC/blob/master/crates/cjc-abng/src/graph.rs">graph.rs:1678</a>) calls <code>blr.update(phi, y)</code> directly — it doesn’t run the MLP forward first. To use an MLP head, you’d need to either:</p>
<ol type="1">
<li>Write a parallel <code>train_step_with_mlp_forward</code> method on <code>AdaptiveBeliefGraph</code>, or</li>
<li>Do the MLP forward/backward orchestration in the harness, then call the existing <code>train_step</code> with the <em>penultimate features</em> as φ.</li>
</ol>
<p>Option 2 is ~250 LOC of test-side surgery with no ABNG changes. The design doc spells it out. <strong>Probably no new AuditKind variant is required</strong> — <code>LeafSetParam</code>/<code>LeafSetParamBatch</code> are already canary-locked.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
A scope reframe
</div>
</div>
<div class="callout-body-container callout-body">
<p>The first post said §4.C was “the ranking-ceiling lever — needed to break the 0.61 ceiling.” That framing is now wrong:</p>
<ul>
<li>We’re at AUC 0.6645 ± 0.0018 <em>without</em> MLP. The “ceiling” wasn’t where the framing implied.</li>
<li>§4.C’s plausible delta is now ~+0.02 (0.66 → ~0.68), not ~+0.05 (0.61 → 0.66).</li>
<li>§4.C is harness-side surgery, not ABNG architecture surgery — the infrastructure already exists.</li>
</ul>
<p>Recommend Phase 0.11 or a future focused session. The cost/benefit ratio is worse than the first post implied, in both directions: smaller potential lift, but also smaller architectural footprint.</p>
</div>
</div>
</section>
<section id="abng-architectural-fingerprint-what-carried-this" class="level2">
<h2 class="anchored" data-anchor-id="abng-architectural-fingerprint-what-carried-this">8. ABNG architectural fingerprint — what carried this</h2>
<p>The work this post describes uses a <em>purely linear</em> ABNG: BLR heads on raw φ, no nonlinear layers. The result (AUC 0.6645) is, on its face, a result a linear model produced. So a reasonable reader asks: <em>was ABNG architecturally unique on this run, or was it just a linear ensemble in fancy clothes?</em></p>
<div id="fig-abng-architecture" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="figures/traditional/abng_architecture.png" class="img-fluid figure-img" alt="Architecture flow diagram. Top: Row goes through CategoricalTransform to produce (x, φ, y). Two branches: one to Root BLR (purple, posterior on all data), one to Routing decision (orange, K=2 MI-selected features). Routing fans out to 4 Leaf BLR boxes (blue). All five — root and 4 leaves — converge into a bottom Ensemble box (green): Ensemble = 0.5 × root + 0.5 × routed leaf. Footnote: K=1 shown for legibility; actual K=2 means 16 leaves."></p>
<figcaption class="figure-caption">Figure&nbsp;11: ABNG’s per-leaf BLR ensemble structure. Each input row passes through the <code>CategoricalTransform</code> to become <code>(x, φ, y)</code> — <code>x</code> routes; <code>φ</code> predicts. The <strong>root BLR</strong> has its own conjugate posterior trained on all rows. The <strong>routing decision</strong> is frozen at graph-build time using the top-K=2 MI-scored columns. Each row then trains exactly <em>one</em> leaf’s BLR, again with closed-form conjugate updates. At predict time, the ensemble is <code>0.5 × root_mean + 0.5 × routed_leaf_mean</code>. The schematic shows K=1 (4 leaves) for legibility — diabetes-130 actually uses K=2, fanning into 16 leaves. The audit chain SHA-256 hash advances per <code>train_step</code>, binding (row, leaf, posterior state) into one chained event.</figcaption>
</figure>
</div>
<p>The honest answer is that even without MLP, ABNG has an architectural fingerprint that <strong>none of scikit-learn’s <code>LogisticRegression</code>, an XGBoost model, or a single per-leaf logistic regression in a tree carries</strong>. Five things that mattered on this dataset:</p>
<section id="the-φ-vs-routing-feature-split" class="level3">
<h3 class="anchored" data-anchor-id="the-φ-vs-routing-feature-split">8.1 The φ-vs-routing feature split</h3>
<p>ABNG’s categorical transform produces two outputs per row: <code>x</code> (low-dim integer buckets for routing) and <code>phi</code> (high-dim one-hot for the BLR head). The schema’s <code>CategoricalPhiOnly</code> role marks columns as <strong>“contribute to φ but never to routing”</strong>.</p>
<p>On diabetes-130, that’s what makes the 23 medication columns and 3 ICD-9 codes (700+ levels each) usable. They participate in prediction (φ width stays ≤ 266 across all configs) without exploding the routing tree (which would otherwise need 4^700 leaves). Trees and forests don’t cleanly separate “what splits” from “what predicts” — every feature is a split candidate or excluded. ABNG’s split is at the schema layer, before routing.</p>
</section>
<section id="pre-fixed-mi-selected-routing" class="level3">
<h3 class="anchored" data-anchor-id="pre-fixed-mi-selected-routing">8.2 Pre-fixed MI-selected routing</h3>
<p>Greedy tree learners pick splits locally — each split optimises against the current data subset. ABNG picks routes <em>globally, once</em>, before any training: score every column’s mutual information against the target, take the top K, build a fixed codebook. The structure is then frozen; training only fills in the per-leaf heads.</p>
<p>This session showed this lever doing real work: at 20K it picked <code>[num_inpatient, time_in_hospital]</code>, at 101K it picked <code>[num_inpatient, number_emergency]</code> — <strong>automatically, no human tuning</strong>. And at 101K all three §4.F seeds picked the same pair: structural decisions are pinned by scale, with seed-to-seed noise concentrated entirely in the per-leaf parameters.</p>
</section>
<section id="per-leaf-bayesian-linear-regression-with-conjugate-updates" class="level3">
<h3 class="anchored" data-anchor-id="per-leaf-bayesian-linear-regression-with-conjugate-updates">8.3 Per-leaf Bayesian linear regression with conjugate updates</h3>
<p>Each leaf is a full Bayesian regression: precision matrix, posterior mean, predictive variance — all updated in closed form per training row. <strong>No SGD. No learning rate. No early stopping.</strong> O(d²) per step, where d ≈ 266 here.</p>
<p>The root + leaf ensemble (predicted prob = 0.5 × leaf_posterior_mean + 0.5 × root_posterior_mean) is the model that produces 0.6645. Bayesian forests and BART share parts of this idea; the combination of conjugate per-leaf BLRs with frozen pre-MI routing is, as far as I know, ABNG-specific.</p>
</section>
<section id="sha-256-audit-chain-over-training-events" class="level3">
<h3 class="anchored" data-anchor-id="sha-256-audit-chain-over-training-events">8.4 SHA-256 audit chain over training events</h3>
<p>Every <code>train_step</code> appends an event to a hash chain. End-state chain head is byte-reproducible. Merkle root verifies. <strong>This is the property no commodity ML system carries.</strong></p>
<p>In this session: five commits, each carrying a chain head. Aggressive config changes throughout — constants flipped, new tests added, a new filter applied, multi-seed runs. The 28 SHA-256 determinism canaries didn’t move once, because nothing they cover was touched. The work was <em>safe to be exploratory</em> in a way most ML harnesses don’t permit.</p>
</section>
<section id="bit-identical-replay" class="level3">
<h3 class="anchored" data-anchor-id="bit-identical-replay">8.5 Bit-identical replay</h3>
<p>The first post’s reproducibility evidence (“Run 1 / Run 2 — every metric digit identical, 3× wall-clock difference”) held throughout Round Two. The §4.F std of 0.0018 is direct evidence: variance comes entirely from seed-driven sub-sample / split / training-order permutations, not from numerical noise. Kahan summation, BTreeMap iteration (not HashMap), no FMA in SIMD kernels, deterministic SplitMix64 RNG — the determinism contract is a system-wide invariant.</p>
<p>The five chain heads from this session — <code>8897c2dd…</code> (before), <code>57463728…</code> (§4.A after), <code>78a63f56…</code> (§4.B pruned), <code>56af1961…</code> (§4.E full), and the three §4.F seeds — are durable artifacts. Anyone with the codebase, the seed, and the dataset can rerun and confirm bit-identity.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What the MLP would have <em>added</em>
</div>
</div>
<div class="callout-body-container callout-body">
<p>One thing: <strong>nonlinearity inside each leaf</strong>. The linear leaf head can only fit linear relationships between φ and the target <em>within</em> its routing slice. An MLP head would let each leaf learn interactions (medication × demographic × diagnosis).</p>
<p>But the routing tree itself is already a form of nonlinearity — splitting the data into 16 leaves by <code>num_inpatient × number_emergency</code> means each leaf sees a piecewise-linear slice of the data. The MLP would push from piecewise-linear to per-leaf-arbitrary-nonlinear. The §4.C design doc estimates that buys ~0.02 AUC (0.66 → ~0.68) — a real but bounded lift.</p>
<p>The architectural fingerprint above (φ-routing split, frozen MI routing, conjugate BLR heads, audit chain, bit-replay) <strong>doesn’t depend on the MLP</strong> — it’s the <em>substrate</em> the MLP would sit on. The fingerprint is what made the exploration safe, the determinism contract durable, and the per-leaf result interpretable. The headline number was driven by data scale + tuning, not the substrate; the substrate is what made the work auditable.</p>
</div>
</div>
</section>
</section>
<section id="honest-assessment-what-locke-did-and-didnt" class="level2">
<h2 class="anchored" data-anchor-id="honest-assessment-what-locke-did-and-didnt">9. Honest assessment — what Locke did, and didn’t</h2>
<p>If §8 is “ABNG worked end-to-end,” this section is the matching honest accounting for Locke. The brief’s flagship hypothesis was “Locke surfaces leakage → drop rows → AUC up.” That didn’t happen. So <em>what did Locke contribute</em>?</p>
<p>Six roles, six honest takes (from the <a href="https://github.com/AdamEzzat1/CJC/blob/master/docs/abng/PHASE_0_10_SESSION_NOTES.md">session notes</a>):</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Numerical Computing axis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Locke did not directly drive the AUC bump.</strong> Every gain — §4.A’s +0.055, §4.E’s +0.031, §4.F’s confidence bound — came from ABNG tuning + data scale, not any Locke finding. The flagship §4.B hypothesis (Locke surfaces E9063 → drop death rows → AUC up) didn’t pan out: E9063 didn’t fire, and the domain-knowledge prune we applied anyway <em>hurt</em> AUC by 0.0118.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Lead Architect axis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Locke surfaced its own detector ceiling, which is a publishable finding in itself.</strong> E9063 is per-feature ROC-AUC; it misses per-level deterministic leakage. The diabetes-130 dataset is the kind of medical data where leakage hides at the <em>level</em> (discharge code 11 = expired), not the column. The proposed <strong>E9064 per-level conditional-probability detector</strong> is now a concrete Locke roadmap item, bound to a real-world example.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Determinism Auditor axis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Locke’s determinism contract held — <code>cjcl locke verify --runs N</code> would still pass on every artifact produced.</strong> The 142 findings and their content-addressed IDs are reproducible. The audit chain integrity is preserved across an exploratory session that changed configuration substantially. This is a non-trivial systems contribution: a noisy, exploratory ML harness changed configs aggressively, and the data-side audit trail never needed to budge.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Pipeline Engineer axis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Locke’s CLI surface worked exactly as designed.</strong> <code>--target readmitted --primary-key patient_nbr --save-json --html</code> ran to completion, produced structured JSON, and emitted a navigable HTML report with the Pearson correlation heatmap. The plumbing is solid. No CLI or schema issues.</p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Runtime Systems axis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Locke’s findings flagged structural concerns AUC numbers couldn’t see.</strong> Two examples:</p>
<ol type="1">
<li><strong>E9004 on <code>patient_nbr</code></strong> — 30,248 duplicate keys across 16,773 groups. Means the harness’s encounter-level train/test split lets the same patient appear in train + test. AUC won’t show it; Locke surfaced it without running a single model.</li>
<li><strong>E9082 on <code>weight</code> / <code>medical_specialty</code> / <code>max_glu_serum</code></strong> — near-duplicate category strings. Some are real distinctions (<code>[0-25)</code> vs <code>[50-75)</code>), but the warning forces a deliberate “yes these are different, not typos” review.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
QA Automation axis
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Locke’s null result on missingness was the most actionable finding.</strong> Default config doesn’t recognise <code>?</code>, so a 97%-missing column shows up as “missingness_score = 1.0 (perfect)” in per-leaf BeliefScore output. This is a Locke configuration gap that medical CSVs commonly trigger. The fix is either auto-detect common sentinels (<code>?</code> / <code>NA</code> / <code>-</code> / <code>NULL</code>), or make the <code>null_masks</code> workflow more discoverable. <strong>Pre-blocked §4.D from being useful as the handoff defined it</strong> — if the belief vector isn’t informative, weighting per-leaf priors by it can’t help.</p>
</div>
</div>
<section id="net-assessment" class="level3">
<h3 class="anchored" data-anchor-id="net-assessment">Net assessment</h3>
<p>Locke <em>did</em> help — but on the <strong>systems / determinism / detector-roadmap</strong> axis, not directly on the <strong>AUC-bump</strong> axis. The brief implicitly assumed Locke would surface a leakage pattern that, when filtered, would lift AUC. What actually happened: Locke surfaced detector limits and structural issues that <em>will</em> drive future Phase 0.11 work but didn’t move <em>this</em> session’s number. The §4.B negative result is the most valuable Locke output of the session — it pins a concrete failure mode (E9063 misses per-level outcomes) and points at a concrete fix (E9064 conditional-probability detector).</p>
<p><strong>ABNG, by contrast, <em>was</em> the lever.</strong> The K=2 / prior=0.5 config + full data + 3-seed variance is what produces AUC 0.6645 ± 0.0018. ABNG’s audit chain, BLR conjugate update, deterministic stratified sub-sample, and MI-based routing selection all carried this session. The cost in code: two constants and three new test functions.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Two roadmap items, both pinned to this dataset
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><p><strong>Locke E9064 — per-level conditional-probability leakage detector.</strong> Catches “specific column level deterministically predicts class” patterns that per-feature ROC-AUC misses. Diabetes-130’s discharge-code death pattern is the canonical example.</p></li>
<li><p><strong>Locke auto-detect missing sentinels.</strong> <code>?</code> / <code>NA</code> / <code>-</code> / <code>NULL</code> should be detected by default. The current <code>null_masks</code> workflow is a one-off helper every harness has to write; should live in Locke. Diabetes-130’s <code>weight</code> column (96.9% <code>?</code>) is the canonical example.</p></li>
</ol>
<p>Both are concrete, both are motivated by a real dataset, both produce immediate value on the next medical CSV that lands.</p>
</div>
</div>
</section>
</section>
<section id="honest-limitations" class="level2">
<h2 class="anchored" data-anchor-id="honest-limitations">10. Honest limitations</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What Round Two did <em>not</em> land
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>A patient-level train/test split.</strong> E9004 surfaced the 16,773-patient encounter overlap; we left the row-level split in place. The first post used row-level; this one does too. Whether AUC 0.6645 is “real signal” or “partial patient-memorisation” can only be settled by re-running with <code>patient_nbr</code>-level splitting. Recorded for Phase 0.11.</li>
<li><strong>MLP leaf heads.</strong> §4.C is a design doc, not code. The lift would plausibly be ~+0.02 (0.66 → ~0.68); the work is harness-side surgery, not ABNG architecture surgery (the LeafHead infrastructure is MLP-ready). Recommended for a focused future session.</li>
<li><strong>§4.D Part 2 — belief-weighted per-leaf priors.</strong> Needs ABNG to expose <code>set_blr_prior_for_node</code> + a new audit kind + canary lock. Multi-session ABNG work. Also pre-blocked by the routing-vs-belief alignment question — on the simple routing we tried, all leaves had uniform belief; the experiment is operationally meaningless until you can route on data-quality dimensions or force per-leaf differential.</li>
<li><strong>Per-seed validation-tuned decision threshold.</strong> The first post tuned this on validation to get F1 ≈ 0.24; we left it at 0.5 and reported F1 ≈ 0.0087 ± 0.0031. A reporting choice, not a model issue.</li>
<li><strong>Beyond n=3 seeds.</strong> Three seeds is the minimum for a meaningful std. The 0.0018 spread suggests further seeds would tighten the 4th decimal but not change the headline. Extend to n=10 only if a tighter band is needed for publication.</li>
</ul>
</div>
</div>
</section>
<section id="whats-next" class="level2">
<h2 class="anchored" data-anchor-id="whats-next">11. What’s next</h2>
<p>In rough priority order, given that §4.E + §4.F already cleared the brief’s stretch goal:</p>
<ol type="1">
<li><strong>Patient-level train/test split.</strong> Most defensibility per unit work. The first post and this post both report encounter-level numbers; a patient-level run would settle whether the 0.66 is signal or memorisation.</li>
<li><strong>§4.C MLP heads.</strong> Implementation is harness-side (~250 LOC). Expected lift +0.02. Not architecturally risky; the substrate is already MLP-ready.</li>
<li><strong>Locke E9064 detector.</strong> Catches per-level deterministic leakage. Would have flagged the discharge-code pattern that §4.B applied via domain knowledge.</li>
<li><strong>Locke <code>?</code>-sentinel auto-detection.</strong> Removes the harness-side <code>NullMaskMap</code> workflow §4.D Part 1 had to write. Would also unblock per-leaf belief on most medical CSVs by default.</li>
<li><strong>§4.D Part 2.</strong> Belief-weighted per-leaf priors, <em>only</em> once (i) <code>set_blr_prior_for_node</code> ships in ABNG and (ii) the routing-vs-belief alignment question is settled with a data-quality-aware routing or a per-leaf-differential experiment.</li>
</ol>
</section>
<section id="reproducibility" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility">12. Reproducibility</h2>
<p>The result is deterministic. Five commits on <code>claude/adoring-shtern-01c720</code>:</p>
<pre class="text"><code>a239e94  docs(phase 0.10): §4.C MLP-head design doc + final session notes
c66e74c  abng: Phase 0.10 §4.D Part 1 — Locke `?`-sentinel blindness fixed
3d84a85  docs(phase 0.10): 'has Locke helped' role-by-role assessment
5b65be2  abng: Phase 0.10 §4.F — AUC 0.6645 ± 0.0018 at full Diabetes-130 (n=3 seeds)
d61c88a  abng: Phase 0.10 §4.A/B/E — AUC 0.6621 at full Diabetes-130, in strong-published-model band</code></pre>
<p>Re-run the full pipeline from a clean checkout:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Clone the CJC-Lang repo.</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> clone https://github.com/AdamEzzat1/CJC.git</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> CJC</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="fu">git</span> checkout claude/adoring-shtern-01c720</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Fetch the dataset (UCI dataset 296). Untracked — `.gitignore`'d.</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> tests/data</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="at">-sSL</span> <span class="at">-o</span> diabetes_130.zip <span class="dt">\</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"https://archive.ics.uci.edu/static/public/296/diabetes+130-us+hospitals+for+years+1999-2008.zip"</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="fu">unzip</span> diabetes_130.zip <span class="at">-d</span> diabetes_130</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="bu">cd</span> ../..</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Workspace release build (~10 min, LTO on).</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="ex">cargo</span> build <span class="at">--workspace</span> <span class="at">--release</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Always-run gates — 629/629 should pass.</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a><span class="ex">cargo</span> test <span class="at">--test</span> abng <span class="at">--release</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. §4.A tuned 20K trial (~40 s).</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a><span class="ex">cargo</span> test <span class="at">--test</span> abng diabetes130_subsample_trial <span class="at">--release</span> <span class="dt">\</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">--</span> <span class="at">--ignored</span> <span class="at">--nocapture</span></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="co"># 6. §4.B Locke-pruned trial (~40 s).</span></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="ex">cargo</span> test <span class="at">--test</span> abng diabetes130_subsample_trial_locke_pruned <span class="at">--release</span> <span class="dt">\</span></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">--</span> <span class="at">--ignored</span> <span class="at">--nocapture</span></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a><span class="co"># 7. §4.E full 101K headline (~3.6 min).</span></span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="ex">cargo</span> test <span class="at">--test</span> abng diabetes130_full_run <span class="at">--release</span> <span class="dt">\</span></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">--</span> <span class="at">--ignored</span> <span class="at">--nocapture</span></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a><span class="co"># 8. §4.F multi-seed variance (~10.2 min, 3 × full_run).</span></span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a><span class="ex">cargo</span> test <span class="at">--test</span> abng diabetes130_multi_seed_variance_full <span class="at">--release</span> <span class="dt">\</span></span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">--</span> <span class="at">--ignored</span> <span class="at">--nocapture</span></span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a><span class="co"># 9. Locke audit on the full CSV.</span></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a><span class="ex">./target/release/cjcl.exe</span> locke validate <span class="dt">\</span></span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>    tests/data/diabetes_130/diabetic_data.csv <span class="dt">\</span></span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a>    <span class="at">--target</span> readmitted <span class="at">--primary-key</span> patient_nbr <span class="dt">\</span></span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">--save-json</span> bench_results/diabetes_locke_baseline.json <span class="dt">\</span></span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>    <span class="at">--html</span>        bench_results/diabetes_locke_baseline.html</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a><span class="co"># 10. §4.D Part 1 `?`-aware per-leaf belief.</span></span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a><span class="ex">cargo</span> test <span class="at">--test</span> abng diabetes130_per_leaf_belief_with_question_marks <span class="dt">\</span></span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">--release</span> <span class="at">--</span> <span class="at">--ignored</span> <span class="at">--nocapture</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Build fingerprint: Rust stable, Diabetes-130 dataset SHA-256 verified by the harness’s <code>raw_dataset_hash</code>, seeds 42 / 43 / 44, the full 101,766-row dataset. The five chain heads above must reproduce bit-for-bit.</p>
<p>Detailed session artifacts:</p>
<ul>
<li><a href="https://github.com/AdamEzzat1/CJC/blob/master/docs/abng/PHASE_0_10_SESSION_NOTES.md"><code>docs/abng/PHASE_0_10_SESSION_NOTES.md</code></a> — full session notes including the six-axis “has Locke helped” assessment.</li>
<li><a href="https://github.com/AdamEzzat1/CJC/blob/master/docs/abng/PHASE_0_10_SECTION_4C_DESIGN.md"><code>docs/abng/PHASE_0_10_SECTION_4C_DESIGN.md</code></a> — MLP-head design doc.</li>
<li><code>bench_results/diabetes_phase_0_10_section_{4a,4b,4d,4e,4f}/SUMMARY.md</code> — per-section result summaries with chain heads.</li>
</ul>
<section id="figures" class="level3">
<h3 class="anchored" data-anchor-id="figures">Figures</h3>
<p>Every chart in this post was rendered from the actual session data via <a href="generate_figures.py"><code>generate_figures.py</code></a> (Plotly + kaleido). Two themes are saved alongside:</p>
<ul>
<li><strong>Traditional</strong> (used in the body above): <code>figures/traditional/&lt;name&gt;.png</code></li>
<li><strong>Cyberpunk</strong>: <code>figures/cyberpunk/&lt;name&gt;.png</code></li>
</ul>
<p>Interactive HTML versions (hover for exact values, zoom, pan) live under <code>figures/interactive/&lt;theme&gt;/&lt;name&gt;.html</code>.</p>
<p>The Locke Pearson |r| heatmap (<a href="figures/locke/pearson_heatmap_actual.svg"><code>figures/locke/pearson_heatmap_actual.svg</code></a>) is extracted verbatim from the actual <code>cjcl locke validate</code> HTML report via <a href="extract_locke_heatmap.py"><code>extract_locke_heatmap.py</code></a> — no recreation, no theme override. It’s the literal Locke artifact, content-addressed and deterministic.</p>
</section>
</section>
<section id="the-honest-summary" class="level2">
<h2 class="anchored" data-anchor-id="the-honest-summary">13. The honest summary</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Round Two in one paragraph
</div>
</div>
<div class="callout-body-container callout-body">
<p>The Adaptive Belief Network Graph crossed into the strong-published-model band on UCI Diabetes-130 — <strong>AUC 0.6645 ± 0.0018 across 3 seeds at the full 101,766 rows</strong> — without any architectural change, still on the linear BLR head. The decisive lever was <strong>data scale + the validation-tuned config the first post identified</strong>, not the MLP heads the first post predicted would be needed. <strong>Calibration metrics (Brier 0.0950, NLL 0.3346, ECE 0.0038) all beat the first post’s <em>calibrated</em> values without any Platt step</strong>, because at full scale the raw outputs were already well-calibrated. The Locke audit ran end-to-end (142 findings, 1 error, fully content-addressed) and surfaced a structural patient-encounter leakage hole the first post missed (E9004), exposed its own configuration gap on <code>?</code>-sentinel medical CSVs (which §4.D Part 1 patched), and pinned a concrete detector failure mode for a proposed E9064 conditional-probability leakage check. <strong>The Locke-driven prune experiment falsified the handoff’s hypothesis — applying it actually <em>hurt</em> AUC by 0.0118</strong> because the prune confounded with MI routing-feature selection, which is itself a finding worth recording. Five commits, every chain head reproducible, the 629 determinism canaries unmoved throughout. <strong>ABNG drove the AUC headline; Locke drove the systems / detector-roadmap axis. Both contributions are real; they just sit on different axes than the brief originally assumed.</strong></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>ABNG lives at <a href="https://github.com/AdamEzzat1/CJC/tree/master/crates/cjc-abng"><code>crates/cjc-abng/</code></a> and Locke at <a href="https://github.com/AdamEzzat1/CJC/tree/master/crates/cjc-locke"><code>crates/cjc-locke/</code></a> in the CJC-Lang repository. The Diabetes-130 harness is in <a href="https://github.com/AdamEzzat1/CJC/blob/master/tests/abng/dataset_a_diabetes130.rs"><code>tests/abng/dataset_a_diabetes130.rs</code></a>. This post is Round Two of an ongoing campaign — see <a href="../../../blog/posts/abng-diabetes-readmission/index.html">Round One</a> for the methodology + baseline.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© 2026 Adam Ezzat. Built with <a href="https://quarto.org/">Quarto</a>.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>