<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adam Ezzat">
<meta name="dcterms.date" content="2026-05-28">
<meta name="description" content="Locke is a deterministic, content-addressed data-skepticism layer for CJC-Lang. v0.1.10 is live on crates.io. Every finding carries structured evidence, assumptions, and suggested next checks. Reports are content-addressed so CI runs can diff them byte-for-byte. This post positions Locke against the four adjacent tools (dbt, Pandera, Monte Carlo, Great Expectations) using a five-layer model of the data-quality stack, walks four concrete scenarios with actual JSON findings and a Mermaid lineage graph, includes adversarial side-by-side examples where ordinary tools see nothing, formalises the meet-semilattice algebra under which BeliefScores compose, and includes a 275× speedup benchmark against GX on a 7023-row synthetic churn dataset.">

<title>Adam Ezzat - Locke v0.1.10: An Epistemic Layer for Data Validation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Adam Ezzat</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../blog/index.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/AdamEzzat1" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/adamezzat" rel="" target=""><i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#where-locke-sits-in-the-data-quality-stack" id="toc-where-locke-sits-in-the-data-quality-stack" class="nav-link active" data-scroll-target="#where-locke-sits-in-the-data-quality-stack">Where Locke sits in the data-quality stack</a></li>
  <li><a href="#why-i-built-locke" id="toc-why-i-built-locke" class="nav-link" data-scroll-target="#why-i-built-locke">Why I built Locke</a></li>
  <li><a href="#what-evidence-aware-actually-means" id="toc-what-evidence-aware-actually-means" class="nav-link" data-scroll-target="#what-evidence-aware-actually-means">What “evidence-aware” actually means</a></li>
  <li><a href="#the-shape-of-the-api" id="toc-the-shape-of-the-api" class="nav-link" data-scroll-target="#the-shape-of-the-api">The shape of the API</a>
  <ul class="collapse">
  <li><a href="#rust-api" id="toc-rust-api" class="nav-link" data-scroll-target="#rust-api">Rust API</a></li>
  <li><a href="#cli" id="toc-cli" class="nav-link" data-scroll-target="#cli">CLI</a></li>
  <li><a href="#cjc-lang-source" id="toc-cjc-lang-source" class="nav-link" data-scroll-target="#cjc-lang-source">CJC-Lang source</a></li>
  </ul></li>
  <li><a href="#four-scenarios-in-detail" id="toc-four-scenarios-in-detail" class="nav-link" data-scroll-target="#four-scenarios-in-detail">Four scenarios in detail</a>
  <ul class="collapse">
  <li><a href="#scenario-1-the-monday-morning-gate-diff" id="toc-scenario-1-the-monday-morning-gate-diff" class="nav-link" data-scroll-target="#scenario-1-the-monday-morning-gate-diff">Scenario 1 — The Monday-morning gate diff</a></li>
  <li><a href="#scenario-2-the-target-leakage-smoking-gun" id="toc-scenario-2-the-target-leakage-smoking-gun" class="nav-link" data-scroll-target="#scenario-2-the-target-leakage-smoking-gun">Scenario 2 — The target-leakage smoking gun</a></li>
  <li><a href="#scenario-3-the-lineage-diagram" id="toc-scenario-3-the-lineage-diagram" class="nav-link" data-scroll-target="#scenario-3-the-lineage-diagram">Scenario 3 — The lineage diagram</a></li>
  <li><a href="#scenario-4-belief-score-side-by-side" id="toc-scenario-4-belief-score-side-by-side" class="nav-link" data-scroll-target="#scenario-4-belief-score-side-by-side">Scenario 4 — Belief score side-by-side</a></li>
  </ul></li>
  <li><a href="#when-ordinary-tools-see-nothing" id="toc-when-ordinary-tools-see-nothing" class="nav-link" data-scroll-target="#when-ordinary-tools-see-nothing">When ordinary tools see nothing</a>
  <ul class="collapse">
  <li><a href="#a-dashboard-says-churn-risk-up-22" id="toc-a-dashboard-says-churn-risk-up-22" class="nav-link" data-scroll-target="#a-dashboard-says-churn-risk-up-22">A — Dashboard says “churn risk up 22%”</a></li>
  <li><a href="#b-dbt-test-exits-0-model-memorises-customer_id" id="toc-b-dbt-test-exits-0-model-memorises-customer_id" class="nav-link" data-scroll-target="#b-dbt-test-exits-0-model-memorises-customer_id">B — <code>dbt test</code> exits 0, model memorises <code>customer_id</code></a></li>
  <li><a href="#c-pandera-schema-passes-a-stale-snapshot" id="toc-c-pandera-schema-passes-a-stale-snapshot" class="nav-link" data-scroll-target="#c-pandera-schema-passes-a-stale-snapshot">C — Pandera schema passes a stale snapshot</a></li>
  <li><a href="#d-monte-carlo-green-traintest-boundary-leaks" id="toc-d-monte-carlo-green-traintest-boundary-leaks" class="nav-link" data-scroll-target="#d-monte-carlo-green-traintest-boundary-leaks">D — Monte Carlo green, train/test boundary leaks</a></li>
  <li><a href="#common-thread" id="toc-common-thread" class="nav-link" data-scroll-target="#common-thread">Common thread</a></li>
  </ul></li>
  <li><a href="#what-ships-in-v0.1.10" id="toc-what-ships-in-v0.1.10" class="nav-link" data-scroll-target="#what-ships-in-v0.1.10">What ships in v0.1.10</a></li>
  <li><a href="#how-locke-compares-to-adjacent-tools" id="toc-how-locke-compares-to-adjacent-tools" class="nav-link" data-scroll-target="#how-locke-compares-to-adjacent-tools">How Locke compares to adjacent tools</a>
  <ul class="collapse">
  <li><a href="#vs-great-expectations" id="toc-vs-great-expectations" class="nav-link" data-scroll-target="#vs-great-expectations">vs Great Expectations</a></li>
  <li><a href="#vs-dbt-tests" id="toc-vs-dbt-tests" class="nav-link" data-scroll-target="#vs-dbt-tests">vs dbt tests</a></li>
  <li><a href="#vs-pandera" id="toc-vs-pandera" class="nav-link" data-scroll-target="#vs-pandera">vs Pandera</a></li>
  <li><a href="#vs-monte-carlo" id="toc-vs-monte-carlo" class="nav-link" data-scroll-target="#vs-monte-carlo">vs Monte Carlo</a></li>
  </ul></li>
  <li><a href="#the-benchmark-that-earned-the-headline" id="toc-the-benchmark-that-earned-the-headline" class="nav-link" data-scroll-target="#the-benchmark-that-earned-the-headline">The benchmark that earned the headline</a>
  <ul class="collapse">
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology">Methodology</a></li>
  <li><a href="#a-real-finding-byte-for-byte" id="toc-a-real-finding-byte-for-byte" class="nav-link" data-scroll-target="#a-real-finding-byte-for-byte">A real finding, byte-for-byte</a></li>
  <li><a href="#detection-results" id="toc-detection-results" class="nav-link" data-scroll-target="#detection-results">Detection results</a></li>
  <li><a href="#timing" id="toc-timing" class="nav-link" data-scroll-target="#timing">Timing</a></li>
  <li><a href="#built-in-checks-locke-runs-that-gx-doesnt-out-of-the-box" id="toc-built-in-checks-locke-runs-that-gx-doesnt-out-of-the-box" class="nav-link" data-scroll-target="#built-in-checks-locke-runs-that-gx-doesnt-out-of-the-box">Built-in checks Locke runs that GX doesn’t out of the box</a></li>
  <li><a href="#built-in-checks-gx-runs-that-locke-doesnt-out-of-the-box" id="toc-built-in-checks-gx-runs-that-locke-doesnt-out-of-the-box" class="nav-link" data-scroll-target="#built-in-checks-gx-runs-that-locke-doesnt-out-of-the-box">Built-in checks GX runs that Locke doesn’t out of the box</a></li>
  </ul></li>
  <li><a href="#what-scale-locke-handles" id="toc-what-scale-locke-handles" class="nav-link" data-scroll-target="#what-scale-locke-handles">What scale Locke handles</a>
  <ul class="collapse">
  <li><a href="#single-shot-validate" id="toc-single-shot-validate" class="nav-link" data-scroll-target="#single-shot-validate">Single-shot <code>validate()</code></a></li>
  <li><a href="#drift-compare" id="toc-drift-compare" class="nav-link" data-scroll-target="#drift-compare">Drift <code>compare()</code></a></li>
  <li><a href="#streaming-validator-chunked-ingest" id="toc-streaming-validator-chunked-ingest" class="nav-link" data-scroll-target="#streaming-validator-chunked-ingest">Streaming validator (chunked ingest)</a></li>
  <li><a href="#streaming-ks-d-vs-single-shot-ks-d" id="toc-streaming-ks-d-vs-single-shot-ks-d" class="nav-link" data-scroll-target="#streaming-ks-d-vs-single-shot-ks-d">Streaming KS D vs single-shot KS D</a></li>
  <li><a href="#practical-scale-matrix-for-a-churn-use-case" id="toc-practical-scale-matrix-for-a-churn-use-case" class="nav-link" data-scroll-target="#practical-scale-matrix-for-a-churn-use-case">Practical scale matrix for a churn use case</a></li>
  </ul></li>
  <li><a href="#the-ci-workflow-locke-was-built-for" id="toc-the-ci-workflow-locke-was-built-for" class="nav-link" data-scroll-target="#the-ci-workflow-locke-was-built-for">The CI workflow Locke was built for</a></li>
  <li><a href="#the-stakeholder-html-report" id="toc-the-stakeholder-html-report" class="nav-link" data-scroll-target="#the-stakeholder-html-report">The stakeholder HTML report</a></li>
  <li><a href="#locke-is-not-a-one-stop-ml-tool" id="toc-locke-is-not-a-one-stop-ml-tool" class="nav-link" data-scroll-target="#locke-is-not-a-one-stop-ml-tool">Locke is not a one-stop ML tool</a></li>
  <li><a href="#what-i-think-the-determinism-contract-actually-buys-you" id="toc-what-i-think-the-determinism-contract-actually-buys-you" class="nav-link" data-scroll-target="#what-i-think-the-determinism-contract-actually-buys-you">What I think the determinism contract actually buys you</a></li>
  <li><a href="#the-formal-model-how-confidence-composes" id="toc-the-formal-model-how-confidence-composes" class="nav-link" data-scroll-target="#the-formal-model-how-confidence-composes">The formal model: how confidence composes</a>
  <ul class="collapse">
  <li><a href="#confidence-representation" id="toc-confidence-representation" class="nav-link" data-scroll-target="#confidence-representation">Confidence representation</a></li>
  <li><a href="#confidence-composition-under-transformation" id="toc-confidence-composition-under-transformation" class="nav-link" data-scroll-target="#confidence-composition-under-transformation">Confidence composition under transformation</a></li>
  <li><a href="#what-weakens-confidence" id="toc-what-weakens-confidence" class="nav-link" data-scroll-target="#what-weakens-confidence">What weakens confidence</a></li>
  <li><a href="#how-propagation-is-modeled" id="toc-how-propagation-is-modeled" class="nav-link" data-scroll-target="#how-propagation-is-modeled">How propagation is modeled</a></li>
  <li><a href="#deterministic-update-rules" id="toc-deterministic-update-rules" class="nav-link" data-scroll-target="#deterministic-update-rules">Deterministic update rules</a></li>
  <li><a href="#confidence-algebra-shipped-vs-planned" id="toc-confidence-algebra-shipped-vs-planned" class="nav-link" data-scroll-target="#confidence-algebra-shipped-vs-planned">Confidence algebra (shipped vs planned)</a></li>
  <li><a href="#belief-degradation-visualised" id="toc-belief-degradation-visualised" class="nav-link" data-scroll-target="#belief-degradation-visualised">Belief degradation, visualised</a></li>
  <li><a href="#where-the-formal-model-lives-in-code" id="toc-where-the-formal-model-lives-in-code" class="nav-link" data-scroll-target="#where-the-formal-model-lives-in-code">Where the formal model lives in code</a></li>
  </ul></li>
  <li><a href="#install" id="toc-install" class="nav-link" data-scroll-target="#install">Install</a></li>
  <li><a href="#where-v0.2-is-going" id="toc-where-v0.2-is-going" class="nav-link" data-scroll-target="#where-v0.2-is-going">Where v0.2 is going</a></li>
  <li><a href="#final-honest-framing" id="toc-final-honest-framing" class="nav-link" data-scroll-target="#final-honest-framing">Final honest framing</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Locke v0.1.10: An Epistemic Layer for Data Validation</h1>
<p class="subtitle lead">Locke isn’t another expectation library or schema validator. It’s the layer that records what evidence backs every finding, what assumptions Locke made, and produces a byte-identical audit artifact across runs. With a side-by-side benchmark against Great Expectations and explicit contrasts with dbt, Pandera, and Monte Carlo.</p>
  <div class="quarto-categories">
    <div class="quarto-category">CJC-Lang</div>
    <div class="quarto-category">Locke</div>
    <div class="quarto-category">data-quality</div>
    <div class="quarto-category">validation</div>
    <div class="quarto-category">churn</div>
    <div class="quarto-category">benchmarks</div>
    <div class="quarto-category">epistemic</div>
  </div>
  </div>

<div>
  <div class="description">
    Locke is a deterministic, content-addressed data-skepticism layer for CJC-Lang. v0.1.10 is live on crates.io. Every finding carries structured evidence, assumptions, and suggested next checks. Reports are content-addressed so CI runs can diff them byte-for-byte. This post positions Locke against the four adjacent tools (dbt, Pandera, Monte Carlo, Great Expectations) using a five-layer model of the data-quality stack, walks four concrete scenarios with actual JSON findings and a Mermaid lineage graph, includes adversarial side-by-side examples where ordinary tools see nothing, formalises the meet-semilattice algebra under which BeliefScores compose, and includes a 275× speedup benchmark against GX on a 7023-row synthetic churn dataset.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Adam Ezzat </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 28, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">May 28, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="reading-time">
🕑 ~42 min read
</div>
<div class="stats-row">
<div class="stat">
<span class="number">202+</span><span class="stat-label">deterministic tests</span>
</div>
<div class="stat">
<span class="number">275×</span><span class="stat-label">faster than GX</span>
</div>
<div class="stat">
<span class="number">5/5</span><span class="stat-label">ground truth match</span>
</div>
<div class="stat">
<span class="number">0</span><span class="stat-label">external runtime deps</span>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
TL;DR
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>cjc-locke v0.1.10</code> is live on <a href="https://crates.io/crates/cjc-locke">crates.io</a>. It’s not another validation framework — it’s an <strong>epistemic layer</strong>. Every finding carries typed evidence, declared assumptions, and a content-addressed 64-bit ID. Two runs over the same data produce byte-identical reports. The CLI ships as <code>cjcl locke &lt;subcommand&gt;</code> and covers validation, drift, lineage, belief reports, causal guardrails, snapshot-and-diff CI gates, HTML output, and a streaming validator for out-of-RAM datasets. On a 7023-row synthetic churn dataset, Locke matched Great Expectations on every ground-truth finding and ran <strong>275× faster</strong> in release mode.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
One prototype disclaimer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Locke is built on top of <strong>CJC-Lang</strong>, a research compiler that is itself pre-1.0. Both are under active development. None of this has been deployed at production scale yet. The benchmark below is on synthetic data of a deliberately-tractable size; real-world performance characteristics will vary. I am the author of Locke, so the comparison framing isn’t from an impartial source — the benchmark code is in the repo for anyone to re-run.</p>
</div>
</div>
<section id="where-locke-sits-in-the-data-quality-stack" class="level2">
<h2 class="anchored" data-anchor-id="where-locke-sits-in-the-data-quality-stack">Where Locke sits in the data-quality stack</h2>
<p>Before the API and the benchmark, the most useful thing I can do is position Locke against the four tools it gets confused with. They each solve a real problem; Locke solves a different one.</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Layer</th>
<th>What it asks</th>
<th>Representative tools</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Transformation-correctness</td>
<td>“Did the SQL run? Did the pipeline produce the expected shape?”</td>
<td><strong>dbt</strong>, Airflow, Dagster</td>
</tr>
<tr class="even">
<td>Schema / contract</td>
<td>“Does each row match the type and range I expect?”</td>
<td><strong>Pandera</strong>, Pydantic, JSON Schema</td>
</tr>
<tr class="odd">
<td>Anomaly-detection</td>
<td>“Is something weird here that I didn’t know to check?”</td>
<td><strong>Monte Carlo</strong>, Anomalo, Bigeye</td>
</tr>
<tr class="even">
<td>Suite-validation</td>
<td>“Does the data pass these specific rules?”</td>
<td><strong>Great Expectations</strong>, Soda Core</td>
</tr>
<tr class="odd">
<td><strong>Epistemic (Locke)</strong></td>
<td><strong>“What evidence do I have for each finding, what did Locke assume, can I reproduce the audit byte-for-byte, and is the inference boundary explicit?”</strong></td>
<td><strong>Locke</strong></td>
</tr>
</tbody>
</table>
<p>The five layers stack. A team can run dbt, Pandera, Monte Carlo, GX, and Locke and have them disagree about nothing — they’re answering different questions. The thing that distinguishes Locke is the third clause: <strong>byte-for-byte reproducible audit</strong>.</p>
<p>Concretely:</p>
<ul>
<li>A dbt test prints “PASS” or “FAIL”. Locke prints <code>id=5fbf919f0ada9b58 code=E9004 severity=error evidence=[count(duplicate_keys)=23] assumptions=[...]</code>.</li>
<li>A Pandera report carries a wall-clock timestamp. Locke’s report carries a 64-bit fingerprint computed <em>from the findings themselves</em> — no timestamps, no UUIDs, no map-iteration nondeterminism.</li>
<li>Monte Carlo learns that “Sundays look weird” from metadata. Locke says “your <code>monthly_charges</code> distribution shifted with KS D=0.34 and here are the five rows that drove it.”</li>
<li>GX has a vastly larger expectation library. Locke ships fewer expectations but, for the ones it ships, treats the report as the audit artifact, not a side effect.</li>
</ul>
<p>The rest of this post is “what does that mean in practice.” Four worked scenarios, then explicit subsections comparing Locke against each adjacent tool.</p>
</section>
<section id="why-i-built-locke" class="level2">
<h2 class="anchored" data-anchor-id="why-i-built-locke">Why I built Locke</h2>
<p>CJC-Lang has a strong runtime determinism story — Kahan accumulators, BTreeMap discipline, content-addressed snapshots, deterministic RNG threading. What it didn’t have until now was a <em>dataset-level</em> skepticism layer: a unified way to ask “is this CSV / JSONL clean enough to train on?” or “did my production data drift since last week?” Users were rolling their own checks per-project and losing the determinism guarantee at the validation boundary.</p>
<p>I considered a few obvious paths:</p>
<ul>
<li>Embed validation in <code>cjc-data</code> (the tidyverse-inspired DataFrame DSL). Tempting but it would pollute the data-DSL’s public type surface.</li>
<li>Extend <code>cjc-abng</code> (Adaptive Belief Network Graph), which already has drift / audit / Merkle infrastructure. But ABNG’s primitives are tree-node-oriented, not column/row-oriented.</li>
<li>A new, standalone crate. Same precedent as <code>cjc-quantum</code>, <code>cjc-abng</code>, <code>cjc-dharht</code>.</li>
</ul>
<p>The third option won. <strong>Locke is now <code>cjc-locke</code> — a dedicated workspace crate alongside the others, depending only on <code>cjc-data</code> and <code>cjc-repro</code> and exposing a clean public API plus a CLI subcommand.</strong></p>
</section>
<section id="what-evidence-aware-actually-means" class="level2">
<h2 class="anchored" data-anchor-id="what-evidence-aware-actually-means">What “evidence-aware” actually means</h2>
<p>The epistemic claim first: <strong>every Locke finding is a structured object with declared evidence and declared assumptions</strong>, not a message string. The name comes from John Locke’s empiricism — every claim should trace back to evidence, every belief should be proportioned to that evidence. Translated into a data-validation library:</p>
<ul>
<li><strong>Findings are evidence-bearing.</strong> Every <code>ValidationFinding</code> carries a typed <code>Vec&lt;FindingEvidence&gt;</code> of <code>Count</code> / <code>Ratio</code> / <code>Range</code> / <code>Metric</code> / <code>Sample</code> entries. No free-text-only messages.</li>
<li><strong>Reports are content-addressed.</strong> Every finding has a 64-bit fingerprint over (code, severity, message, column, evidence). Two runs over the same data produce identical IDs. CI gates can compare reports byte-for-byte.</li>
<li><strong>Impressions vs Ideas.</strong> A <code>LockeImpression</code> is a raw observed fact (a dataset, a column, a row). A <code>LockeIdea</code> is anything derived (a filtered subset, a feature, a metric, a prediction). The lineage DAG only has edges from impressions / parent ideas to child ideas — acyclic by construction.</li>
<li><strong>Belief reports are explainable.</strong> The 8-dimension <code>BeliefScore</code> (schema / missingness / drift / leakage / lineage / sample / duplication / constraint) ships with a breakdown, not a magic number.</li>
<li><strong>Causality is conservative.</strong> Every <code>CausalGuardrailReport</code> carries a top-level disclaimer. No warning kind is named “Cause” or “Effect.” The DAG-based assumption registry lets users declare hypothesised pathways without certifying them.</li>
</ul>
<p>If “evidence-aware” sounds like over-engineering, the alternative is a CI gate that flakes because two runs over the same data produced different report metadata. Locke avoids that by construction.</p>
</section>
<section id="the-shape-of-the-api" class="level2">
<h2 class="anchored" data-anchor-id="the-shape-of-the-api">The shape of the API</h2>
<p>Three usage surfaces:</p>
<section id="rust-api" class="level3">
<h3 class="anchored" data-anchor-id="rust-api">Rust API</h3>
<div class="sourceCode" id="cb1"><pre class="sourceCode rust code-with-copy"><code class="sourceCode rust"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="pp">cjc_locke::</span><span class="op">{</span>validate<span class="op">,</span> ValidateOptions<span class="op">,</span> ValidationConfig<span class="op">};</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="pp">cjc_data::</span>DataFrame<span class="op">;</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span> opts <span class="op">=</span> ValidateOptions <span class="op">{</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    dataset_label<span class="op">:</span> <span class="st">"train.csv"</span><span class="op">.</span>into()<span class="op">,</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    config<span class="op">:</span> <span class="pp">ValidationConfig::</span><span class="kw">default</span>()<span class="op">,</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="op">..</span><span class="bu">Default</span><span class="pp">::</span><span class="kw">default</span>()</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="op">};</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span> report <span class="op">=</span> validate(<span class="op">&amp;</span>df<span class="op">,</span> <span class="op">&amp;</span>opts)<span class="op">;</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="pp">println!</span>(<span class="st">"worst severity: {}"</span><span class="op">,</span> report<span class="op">.</span>worst_severity())<span class="op">;</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> f <span class="kw">in</span> <span class="op">&amp;</span>report<span class="op">.</span>findings <span class="op">{</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="pp">println!</span>(<span class="st">"{} {}: {}"</span><span class="op">,</span> f<span class="op">.</span>code<span class="op">,</span> f<span class="op">.</span>severity<span class="op">,</span> f<span class="op">.</span>message)<span class="op">;</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="op">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="cli" class="level3">
<h3 class="anchored" data-anchor-id="cli">CLI</h3>
<div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">cjcl</span> locke validate data.csv <span class="dt">\</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">--target</span> churned <span class="dt">\</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">--primary-key</span> customer_id <span class="dt">\</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">--time-col</span> event_ts <span class="at">--max-timestamp</span> 1714521600000 <span class="dt">\</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">--html</span> report.html <span class="dt">\</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">--save-json</span> baseline.json <span class="dt">\</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">--fail-on</span> warning</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>That single command runs the full v0.5 validation pass (missingness + duplicates + impossible values + constants + outliers + sentinels + schema + temporal + target-leakage + ID-like + duplicate-key conditioning), writes a stakeholder-ready HTML report with an inline-SVG correlation heatmap, persists the canonical JSON baseline, and exits non-zero if any finding crosses the warning threshold.</p>
</section>
<section id="cjc-lang-source" class="level3">
<h3 class="anchored" data-anchor-id="cjc-lang-source">CJC-Lang source</h3>
<pre class="cjcl"><code>fn main() {
  let h = locke_table_new();
  locke_table_add_float_col(h, "age", [25.0, 30.0, 0.0/0.0, 30.0]);
  locke_table_add_int_col(h, "churned", [0, 1, 1, 0]);
  let r = locke_validate(h);
  print(locke_report_worst_severity(r));   // 2 = Warning (NaN detected)
  print(locke_report_overall_score(r));    // 0.857
}</code></pre>
<p>The CJC-Lang surface lets <code>.cjcl</code> programs validate data without dropping into Rust. The implementation uses a thread-local registry plus 22 <code>locke_*</code> builtins routed through both executors via satellite dispatch — the same pattern <code>cjc-ad</code>’s GradGraph and <code>cjc-abng</code>’s belief radix graph use.</p>
</section>
</section>
<section id="four-scenarios-in-detail" class="level2">
<h2 class="anchored" data-anchor-id="four-scenarios-in-detail">Four scenarios in detail</h2>
<p>The fastest way to understand why “epistemic layer” isn’t marketing-speak is to walk four worked examples. Each scenario shows real bytes from the repo’s <code>bench/locke_vs_gx/</code> artifacts.</p>
<section id="scenario-1-the-monday-morning-gate-diff" class="level3">
<h3 class="anchored" data-anchor-id="scenario-1-the-monday-morning-gate-diff">Scenario 1 — The Monday-morning gate diff</h3>
<p>A data scientist arrives Monday. The Q3 production data dump is ready. They want to know: did anything important change versus the Q2 baseline they trained against?</p>
<p>Two commands:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Friday (Q2): after training, snapshot the Q2 baseline</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="ex">cjcl</span> locke validate train_2026q2.csv <span class="dt">\</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">--target</span> churned <span class="dt">\</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">--primary-key</span> customer_id <span class="dt">\</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">--time-col</span> event_ts <span class="dt">\</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">--max-timestamp</span> 1719792000000 <span class="dt">\</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">--save-json</span> baselines/2026q2_baseline.json</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Monday (Q3): diff the new dump against last quarter's snapshot</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="ex">cjcl</span> locke gate baselines/2026q2_baseline.json <span class="dt">\</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  data/prod_2026q3.csv <span class="dt">\</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">--fail-on</span> warning</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The gate emits a structural diff:</p>
<pre><code># Locke Gate Diff
reference_run_id: 1075bbad9d9b882f
current_run_id:   5fbf919f0ada9b58
summary: appeared=3 disappeared=0 unchanged=17

appeared:
  + code=E9035 severity=warning column=last_login_days_ago
    missingness rate of `last_login_days_ago` shifted: train=0.020, test=0.180
  + code=E9039 severity=error column=monthly_charges
    numeric distribution shift in `monthly_charges` (KS D = 0.342)
  + code=E9051 severity=error column=event_ts
    127 test rows have `event_ts` &lt;= max train timestamp; test set overlaps train window

disappeared: (none)

unchanged:
  · code=E9002 column=customer_id (Int, no null mask)
  · code=E9003 (23 duplicate rows)
  · code=E9072 column=customer_id (ID-like cardinality hint)
  · ... (14 more)</code></pre>
<p>Exit code 2. CI fails the job. A human reads the diff:</p>
<ol type="1">
<li><code>E9051</code> is the smoking gun — 127 rows of the test dump have timestamps inside the training window. Someone changed the ingestion cutoff and the new feed doesn’t respect the train/test boundary anymore.</li>
<li><code>E9039</code> is the symptom — once the test set silently overlaps the train window, the marginal distribution of <code>monthly_charges</code> shifts because the overlap rows are systematically different.</li>
<li><code>E9035</code> is the third-order effect — the missingness rate of a derived column jumps because the overlap rows have null <code>last_login_days_ago</code>.</li>
</ol>
<p>The fix is upstream: the ETL job needed <code>WHERE event_ts &gt; '2026-07-01'</code> and the analyst who refactored it last week silently dropped that clause. The CI gate caught it before model training started.</p>
<p>What makes this work at all: <strong><code>reference_run_id</code> and <code>current_run_id</code> are content-addressed</strong>. The same data on a colleague’s Mac produces <code>5fbf919f0ada9b58</code> byte-for-byte. There’s no “this report has timestamp 2026-05-28T09:14:23Z” or “validation_result_uuid f8a3…” line to make two runs disagree. The 17 <code>unchanged</code> findings are recognised as the same findings because their fingerprints match, not because their messages happened to spell the same words.</p>
</section>
<section id="scenario-2-the-target-leakage-smoking-gun" class="level3">
<h3 class="anchored" data-anchor-id="scenario-2-the-target-leakage-smoking-gun">Scenario 2 — The target-leakage smoking gun</h3>
<p>A new feature lands in the churn pipeline: <code>days_since_last_login</code>. The engineer who added it computed it as <code>now() - last_login_timestamp</code> at feature-engineering time. But “now()” was the <em>scoring</em> moment, not the <em>event</em> moment — every row that already churned has <code>last_login_timestamp</code> frozen at the time the customer left, so <code>days_since_last_login</code> is a near-perfect predictor of <code>churned</code> by construction.</p>
<p>A model trained on this dataset will report 99% ROC AUC offline and degrade to 60% in production within a week.</p>
<p>Locke catches it. Run:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="ex">cjcl</span> locke validate feature_engineered.csv <span class="at">--target</span> churned</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The relevant finding:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"id"</span><span class="fu">:</span> <span class="st">"8b3c1f5d2a4e9c7b"</span><span class="fu">,</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"code"</span><span class="fu">:</span> <span class="st">"E9060"</span><span class="fu">,</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"severity"</span><span class="fu">:</span> <span class="st">"error"</span><span class="fu">,</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"message"</span><span class="fu">:</span> <span class="st">"feature `days_since_last_login` has AUC = 0.971 against target `churned`; likely target leakage"</span><span class="fu">,</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"column"</span><span class="fu">:</span> <span class="st">"days_since_last_login"</span><span class="fu">,</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"evidence"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span><span class="dt">"kind"</span><span class="fu">:</span> <span class="st">"metric"</span><span class="fu">,</span> <span class="dt">"label"</span><span class="fu">:</span> <span class="st">"auc"</span><span class="fu">,</span> <span class="dt">"value"</span><span class="fu">:</span> <span class="fl">0.971</span><span class="fu">}</span><span class="ot">,</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span><span class="dt">"kind"</span><span class="fu">:</span> <span class="st">"metric"</span><span class="fu">,</span> <span class="dt">"label"</span><span class="fu">:</span> <span class="st">"threshold"</span><span class="fu">,</span> <span class="dt">"value"</span><span class="fu">:</span> <span class="fl">0.95</span><span class="fu">}</span><span class="ot">,</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span><span class="dt">"kind"</span><span class="fu">:</span> <span class="st">"count"</span><span class="fu">,</span>  <span class="dt">"label"</span><span class="fu">:</span> <span class="st">"n_pos"</span><span class="fu">,</span>     <span class="dt">"value"</span><span class="fu">:</span> <span class="dv">1574</span><span class="fu">}</span><span class="ot">,</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span><span class="dt">"kind"</span><span class="fu">:</span> <span class="st">"count"</span><span class="fu">,</span>  <span class="dt">"label"</span><span class="fu">:</span> <span class="st">"n_neg"</span><span class="fu">,</span>     <span class="dt">"value"</span><span class="fu">:</span> <span class="dv">5449</span><span class="fu">}</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="ot">]</span><span class="fu">,</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"assumptions"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"rank-sum AUC computed with f64::total_cmp + tie averaging"</span><span class="ot">,</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"leakage is suspected when |AUC - 0.5| &gt;= 0.45 (Error) or 0.35 (Warning)"</span><span class="ot">,</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"this check only fires for binary targets; multi-class deferred to v0.2"</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>  <span class="ot">]</span><span class="fu">,</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"suggested_next_checks"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"verify this feature is computed at the event time, not score time"</span><span class="ot">,</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"check the upstream feature-engineering job for `now()` calls on historical rows"</span><span class="ot">,</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"rebuild the feature using the event timestamp and re-validate"</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  <span class="ot">]</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a><span class="fu">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>After the fix — feature recomputed using the <em>event</em> timestamp, not <code>now()</code> — the same column drops to AUC = 0.61, well below the 0.85 Warning threshold. E9060 disappears from the next gate run. The diff says <code>disappeared: E9060 column=days_since_last_login</code>. The fix is auditable.</p>
<p>The point isn’t that “Locke catches leakage” in the abstract. It’s that the finding carries <strong>the AUC value</strong>, <strong>the count of positives and negatives</strong>, <strong>the threshold that fired</strong>, <strong>the assumption that AUC is rank-sum with tie averaging</strong>, and <strong>the suggested next check</strong> — all as structured fields. A reviewer can decide whether to trust the finding without re-reading Locke’s source.</p>
</section>
<section id="scenario-3-the-lineage-diagram" class="level3">
<h3 class="anchored" data-anchor-id="scenario-3-the-lineage-diagram">Scenario 3 — The lineage diagram</h3>
<p>Locke’s <code>TracedDataFrame</code> wraps <code>cjc-data</code>’s DataFrame ops and records a DAG: each operation is a <code>LockeIdea</code> node, each input dataset is a <code>LockeImpression</code>, and edges carry content-addressed IDs. When a downstream metric goes wrong, you walk the DAG backwards to find which derivation contaminated it.</p>
<p>Consider a four-step pipeline: load raw events, filter to active customers, group by plan tier, and compute churn rate per group:</p>
<div class="cell" data-fig-width="8">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    I["events.csv&lt;br/&gt;&lt;i&gt;LockeImpression&lt;/i&gt;&lt;br/&gt;id=a4f8c2d19e0b3517"]:::imp --&gt;|"observe()"| O["raw_events&lt;br/&gt;&lt;i&gt;LockeIdea&lt;/i&gt;&lt;br/&gt;id=2b7e4a1f8c3d9602"]:::idea
    O --&gt;|"filter(active==1)&lt;br/&gt;id=c91f5b2e0a4d7836"| F["active_events&lt;br/&gt;&lt;i&gt;LockeIdea&lt;/i&gt;&lt;br/&gt;id=f3a2c780b91d4e5c"]:::idea
    F --&gt;|"group_by(plan_tier)&lt;br/&gt;id=8e6b3f04c12a9d7e"| G["grouped&lt;br/&gt;&lt;i&gt;LockeIdea&lt;/i&gt;"]:::idea
    G --&gt;|"summarise(churn_rate=mean(churned))&lt;br/&gt;id=1075bbad9d9b882f"| S["churn_by_tier&lt;br/&gt;&lt;i&gt;LockeIdea&lt;/i&gt;&lt;br/&gt;id=5fbf919f0ada9b58"]:::idea
    S --&gt;|"with_column(label='Q3-2026')&lt;br/&gt;id=db4cac307664c097"| W["labeled&lt;br/&gt;&lt;i&gt;LockeIdea&lt;/i&gt;"]:::idea

    classDef imp fill:#e8f4fd,stroke:#2196F3,stroke-width:2px
    classDef idea fill:#fff3e0,stroke:#FF9800,stroke-width:1px
</pre>
</div>
<p>Locke lineage DAG. Impressions are raw observed facts (cylinder); Ideas are derived (rounded). Edge labels are content-addressed 64-bit IDs computed from the parent ID + the operation. Two runs of the same pipeline over the same input produce identical IDs.</p>
</div>
</div>
</div>
<p>The DAG is acyclic by construction (impressions and ideas are distinct node kinds; edges only go impression → idea or idea → idea). The DAG is also deterministic: rerunning the same pipeline on the same bytes produces the same node IDs. That means a downstream consumer can cite “the churn rate with idea-id <code>5fbf919f0ada9b58</code>” and a Locke replay on the same input will reproduce it byte-for-byte.</p>
<p>When the Monday gate diff above says <code>current_run_id: 5fbf919f0ada9b58</code>, that ID is exactly this node’s content-addressed fingerprint. The <code>gate</code> command and the lineage DAG share the same hashing primitive.</p>
<p>In code, this looks like:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode rust code-with-copy"><code class="sourceCode rust"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="pp">cjc_locke::lineage::</span><span class="op">{</span>LineageGraph<span class="op">,</span> emit_lineage_text<span class="op">};</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="pp">cjc_locke::traced::</span>TracedDataFrame<span class="op">;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span> raw <span class="op">=</span> <span class="pp">TracedDataFrame::</span>observe(<span class="op">&amp;</span>events_df<span class="op">,</span> <span class="st">"events.csv"</span>)<span class="op">;</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span> active <span class="op">=</span> raw<span class="op">.</span>filter(<span class="op">|</span>row<span class="op">|</span> row<span class="op">.</span>get_int(<span class="st">"active"</span>) <span class="op">==</span> <span class="cn">Some</span>(<span class="dv">1</span>))<span class="op">;</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span> grouped <span class="op">=</span> active<span class="op">.</span>group_by(<span class="op">&amp;</span>[<span class="st">"plan_tier"</span>])<span class="op">;</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span> churn_by_tier <span class="op">=</span> grouped<span class="op">.</span>summarise(<span class="st">"churn_rate"</span><span class="op">,</span> <span class="op">|</span>g<span class="op">|</span> g<span class="op">.</span>mean_f64(<span class="st">"churned"</span>))<span class="op">;</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span> labeled <span class="op">=</span> churn_by_tier<span class="op">.</span>with_column(<span class="st">"label"</span><span class="op">,</span> <span class="st">"Q3-2026"</span>)<span class="op">;</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="kw">let</span> graph<span class="op">:</span> LineageGraph <span class="op">=</span> labeled<span class="op">.</span>lineage()<span class="op">;</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="pp">println!</span>(<span class="st">"{}"</span><span class="op">,</span> emit_lineage_text(<span class="op">&amp;</span>graph))<span class="op">;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The text emit is what populates the IDs above. The Mermaid diagram is one possible rendering; the canonical form is the JSON graph that Locke persists, which the HTML report visualises with the same structure.</p>
</section>
<section id="scenario-4-belief-score-side-by-side" class="level3">
<h3 class="anchored" data-anchor-id="scenario-4-belief-score-side-by-side">Scenario 4 — Belief score side-by-side</h3>
<p>Two datasets arrive on the same day: <code>dataset_a.csv</code> (a long-running production export) and <code>dataset_b.csv</code> (a new vendor’s first delivery). Same column shape. The team wants a single number per dataset to decide which to use for the quarterly run.</p>
<p>Locke produces an 8-dimension <code>BeliefScore</code>, not a single number. Each dimension is on <code>[0, 1]</code> where 1.0 means “no evidence of a problem on this axis”:</p>
<pre><code>dataset_a.csv
  overall_score:        0.91
  schema_score:         1.00   no schema mismatches
  missingness_score:    0.99   1 column with &lt;1% NaN, no joint missingness
  drift_score:          0.97   one numeric column with KS D = 0.06 vs ref (notice)
  leakage_score:        1.00   no feature with |AUC| &gt;= 0.85 against target
  lineage_score:        0.95   one Idea node missing parent reference (notice)
  sample_score:         0.92   sample_cap=10000 hit; flagged as approximate
  duplication_score:    1.00   no duplicate rows; no duplicate primary keys
  constraint_score:     1.00   no impossible values; no constants

dataset_b.csv
  overall_score:        0.42
  schema_score:         0.80   `total_charges` declared Float, inferred Str
  missingness_score:    0.42   1.4% of total_charges is empty string; conditional miss with last_login
  drift_score:          0.71   monthly_charges KS D = 0.34 vs dataset_a (error)
  leakage_score:        1.00   no feature with |AUC| &gt;= 0.85 against target
  lineage_score:        0.50   vendor delivery has no lineage attached
  sample_score:         1.00   full dataset evaluated
  duplication_score:    0.65   23 duplicate customer_id keys (E9004 error)
  constraint_score:     0.62   5 rows with monthly_charges = -9999 (impossible)</code></pre>
<p>The team picks dataset A for the quarterly run and files a ticket against the vendor for dataset B. The breakdown tells them <em>which axes</em> are degraded, not just that the dataset is worse — vendor B’s <code>drift_score</code> collapsed because the marginal distribution of <code>monthly_charges</code> shifted by 0.34 in KS distance, and the <code>constraint_score</code> collapsed because of the sentinel <code>-9999</code> rows.</p>
<p>Crucially: each dimension is computed from the <em>same evidence-bearing findings</em> the gate diff uses. The <code>drift_score = 0.71</code> for dataset B is <code>1 - penalty(E9039)</code> where <code>penalty</code> comes from a swappable <code>BeliefPenalty</code> model. The model is declared, not implicit; a team that disagrees with the default can supply their own and the audit still reproduces.</p>
<p>A single magic number from a black-box scorer would let you compare datasets but not act on the comparison. The 8-dim breakdown plus the findings table is what makes the decision actionable.</p>
</section>
</section>
<section id="when-ordinary-tools-see-nothing" class="level2">
<h2 class="anchored" data-anchor-id="when-ordinary-tools-see-nothing">When ordinary tools see nothing</h2>
<p>The previous scenarios showed Locke firing on a dataset where <em>something</em> observably went wrong. The harder case — and the one that motivates the epistemic layer — is when an ordinary tool reports success while Locke surfaces a structured warning. Four side-by-side examples.</p>
<section id="a-dashboard-says-churn-risk-up-22" class="level3">
<h3 class="anchored" data-anchor-id="a-dashboard-says-churn-risk-up-22">A — Dashboard says “churn risk up 22%”</h3>
<p><strong>Ordinary view (Looker tile):</strong></p>
<pre><code>KPI:  customer_churn_risk_score
Δ wk: +22.4%
trend: ▁▂▂▃▃▅▆▇
owner: notified — review next standup</code></pre>
<p><strong>Locke gate diff for the same data:</strong></p>
<pre><code># Locke Gate Diff
reference_run_id: 1075bbad9d9b882f
current_run_id:   ce81fa3d2b5a974e
summary: appeared=4 disappeared=0 unchanged=15

appeared:
  + code=E9039 severity=error column=last_login_days_ago
    numeric distribution shift (KS D = 0.51)
  + code=E9061 severity=warning column=last_login_days_ago
    feature |AUC|=0.87 against `churned` — proxy-leakage suspect
  + code=E9051 severity=error column=event_ts
    312 production rows have event_ts inside the training window
  + code=E9080 severity=warning
    causal assumption `churn_intent → unsubscribe` unsupported in this sample</code></pre>
<p>The dashboard reports the model output. Locke explains <em>why</em> the output moved: an upstream ETL change added a 7-day-lagged event source, the <code>last_login_days_ago</code> distribution shifted because recent activity is now censored, the feature became a proxy for the lag itself (not for churn intent), and 312 production rows leaked back into the training window. The 22% risk uptick is a measurement artifact. A human reading the Locke diff stops the alert chain before the executive briefing; a human reading only the dashboard escalates.</p>
</section>
<section id="b-dbt-test-exits-0-model-memorises-customer_id" class="level3">
<h3 class="anchored" data-anchor-id="b-dbt-test-exits-0-model-memorises-customer_id">B — <code>dbt test</code> exits 0, model memorises <code>customer_id</code></h3>
<p><strong>Ordinary view (CI log):</strong></p>
<pre><code>$ dbt test --select model:churn_features
Found 14 tests, 0 sources, 1 model
14 of 14 PASS in 8.41s
Completed successfully — 0 errors</code></pre>
<p><strong>Locke output on the same table:</strong></p>
<pre><code>[E9072 notice] column `customer_id`      cardinality 0.997  — id-like leak suspect
                id=328845d456c53aea
[E9072 notice] column `last_login_unix`  cardinality 0.997  — id-like leak suspect
                id=03ae43c0bccfbc79
[E9072 notice] column `total_charges`    cardinality 0.977  — id-like leak suspect
                id=86d3973bf5062cf8</code></pre>
<p>dbt’s <code>unique</code> test is structurally the right question for transformation correctness — “does each row have a distinct key.” It is structurally the wrong question for whether to keep that column as a feature. A model trained on the dbt-validated table will hit 98% offline ROC AUC and degrade to 55% in production within a week, because gradient boosting will happily memorise customer IDs the moment they’re left in. Locke fires E9072 on every column whose distinct-per-row ratio exceeds 0.95 and asks the human to decide.</p>
</section>
<section id="c-pandera-schema-passes-a-stale-snapshot" class="level3">
<h3 class="anchored" data-anchor-id="c-pandera-schema-passes-a-stale-snapshot">C — Pandera schema passes a stale snapshot</h3>
<p><strong>Ordinary view (Pandera report):</strong></p>
<pre><code>SchemaModel: CustomersLatest
Validated successfully.
14 columns, 124083 rows.
Run at 2026-10-04T03:00:00.184Z (build #4471)</code></pre>
<p><strong>Locke output on the same file:</strong></p>
<pre><code>[E9050 warning] column `event_ts` not sorted: 1247 non-decreasing pairs
                id=a96abd21b26275c6
[E9054 warning] dataset `customers_latest.parquet` is 9.2 days stale
                max(event_ts) = 2026-09-25T00:00:00Z
                expected_at   = 2026-10-04T00:00:00Z
                id=e9a4f12c80b5d736</code></pre>
<p>Pandera answers “does each row match the type-and-range contract.” It cannot answer “is this snapshot the snapshot I expected” because the contract is a per-row predicate, not a dataset-scoped invariant. Locke’s <code>--max-timestamp</code> carries a declared dataset-level invariant and fires E9054 when it’s violated. The downstream model trained on the Pandera-validated snapshot will be trained on data 9 days older than the team thinks, and the production scorer will degrade silently.</p>
</section>
<section id="d-monte-carlo-green-traintest-boundary-leaks" class="level3">
<h3 class="anchored" data-anchor-id="d-monte-carlo-green-traintest-boundary-leaks">D — Monte Carlo green, train/test boundary leaks</h3>
<p><strong>Ordinary view (MC monitor):</strong></p>
<pre><code>Table: prod.feature_store.churn_features
Row count anomaly:   normal (z = 0.31)
Schema anomaly:      none
Freshness:           on-time
Distribution drift:  none detected
Status: ✅ healthy</code></pre>
<p><strong>Locke output:</strong></p>
<pre><code>[E9051 error] 127 rows in `feature_store_test` have event_ts
              &lt;= max(event_ts) of `feature_store_train`
              overlap_rate = 0.0021
              id=8f6c5b3d1e7a4920</code></pre>
<p>Monte Carlo’s metadata-anomaly detector trips on shapes that look statistically unusual compared to history. A 0.21% subpopulation overlap between train and test rows doesn’t shift the warehouse-layer marginal distribution by anywhere near MC’s sensitivity threshold — <em>it can’t</em>, because it’s a small slice. Locke trips because the train/test temporal boundary is a <em>declared invariant</em>, not a statistical anomaly. Anomaly detection trips on unexpected statistical shapes; epistemic checks trip on declared known-class violations. Both layers are useful; only the epistemic layer catches this specific failure.</p>
</section>
<section id="common-thread" class="level3">
<h3 class="anchored" data-anchor-id="common-thread">Common thread</h3>
<p>Every ordinary-tool report in the four examples is <em>correct under its own contract</em>. The Looker tile correctly computed the churn-risk delta. dbt correctly verified that <code>customer_id</code> is unique. Pandera correctly checked the type-and-range schema. Monte Carlo correctly observed no row-count or freshness anomaly. None of them is wrong; each is silent on the failure mode Locke caught, because the failure mode is outside the layer the tool is designed for.</p>
<p>The epistemic layer is the layer that asks: <em>given the evidence in this dataset and the assumptions Locke is allowed to state, is there a structured finding that should make a human stop and think before the next step runs?</em></p>
</section>
</section>
<section id="what-ships-in-v0.1.10" class="level2">
<h2 class="anchored" data-anchor-id="what-ships-in-v0.1.10">What ships in v0.1.10</h2>
<div class="sourceCode" id="cb18"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="ex">cargo</span> add cjc-locke</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>You get:</p>
<ul>
<li><strong>Validation</strong> — missingness (with null masks for non-float columns), duplicates (full row + by primary key with conditioning), impossible-value DSL, constants and near-constants, schema mismatch, suspicious cardinality, IQR + modified-Z outliers, sentinel-value detection, conditional missingness, imbalanced-class warning, ID-like cardinality hints</li>
<li><strong>Drift / induction risk</strong> — exact Kolmogorov–Smirnov D-statistic (replacing v0.1’s PSI as the default), mean/std/range/missingness shift, categorical TVD, small-sample warnings, temporal train/test overlap detection</li>
<li><strong>Time-aware checks</strong> — sortedness, future-leakage cutoff, gap detection</li>
<li><strong>Target leakage</strong> — per-feature ROC AUC against a binary target via rank-sum</li>
<li><strong>Lineage</strong> — <code>LockeImpression</code> vs <code>LockeIdea</code> semantic split, deterministic DAG, monotonic audit chain, <code>TracedDataFrame</code> wrapper covering 14 cjc-data operations</li>
<li><strong>Belief reports</strong> — 8-dimension <code>BeliefScore</code> with explainable breakdown, user-tunable <code>BeliefWeights</code> and <code>BeliefPenalty</code> model</li>
<li><strong>Causal guardrails</strong> — 5 warning kinds, <code>CausalDag</code> assumption registry with cycle detection, observational-only mode</li>
<li><strong>Streaming</strong> — <code>StreamingValidator</code> with no-reconstruction running state (Welford + BTreeMap ECDF), KS D bit-identical to single-shot</li>
<li><strong>Output</strong> — canonical JSON serializer (hand-written, zero serde dependency), HTML report with inline-SVG correlation heatmap, <code>cjcl locke gate</code> for snapshot-and-diff CI workflows</li>
<li><strong>CJC-Lang integration</strong> — 22 <code>locke_*</code> builtins routed through both executors</li>
</ul>
<p>The error-code range is E9000–E9099. About half is currently assigned (E9001 missingness, E9003/E9004 duplicates, E9007 sentinel, E9039 KS-drift, E9040/E9041 outliers, E9050–E9054 temporal, E9060/E9061 target leakage, E9070 conditional missingness, E9071 imbalanced class, E9072 ID-like, E9073 dup-key conditioning, …). The rest is reserved for v0.2+.</p>
</section>
<section id="how-locke-compares-to-adjacent-tools" class="level2">
<h2 class="anchored" data-anchor-id="how-locke-compares-to-adjacent-tools">How Locke compares to adjacent tools</h2>
<p>The five-layer matrix at the top of this post named four tools. This section walks each in detail. The goal is fair comparison, not a hit piece — each tool is excellent at its layer of the stack and Locke does not replace any of them. Locke replaces nothing; it <strong>adds</strong> an epistemic layer below them.</p>
<section id="vs-great-expectations" class="level3">
<h3 class="anchored" data-anchor-id="vs-great-expectations">vs Great Expectations</h3>
<p>Great Expectations is the closest direct comparable. It’s a suite-validation framework: write a list of expectations, run them against a batch, get a <code>ValidationResult</code>. The library is mature (10K+ stars, 500+ contributors, ~200 expectations, native SQL backends, Data Docs, profiler-driven auto-suite generation).</p>
<p>What Locke does differently:</p>
<ul>
<li><strong>Content-addressed identifiers.</strong> GX validation results have <code>validation_result_id</code> UUIDs and <code>meta</code> blocks with timestamps. Two runs over the same data produce different result IDs. Locke’s run_id and per-finding IDs are content-fingerprints; identical bytes in produce identical IDs out.</li>
<li><strong>Findings as structured objects.</strong> GX returns success/failure plus per-expectation <code>result.partial_unexpected_list</code>. Locke returns <code>code</code>, <code>severity</code>, <code>column</code>, <code>evidence: Vec&lt;FindingEvidence&gt;</code>, <code>assumptions: Vec&lt;String&gt;</code>, <code>suggested_next_checks: Vec&lt;String&gt;</code> as first-class fields.</li>
<li><strong>Churn-specific defaults out of the box.</strong> E9004 (duplicate primary keys), E9060/E9061 (target leakage), E9072 (ID-like cardinality), E9051/E9052 (train/test temporal overlap and future-leakage cutoff), E9070 (conditional missingness), E9073 (duplicate-key conditioning). Equivalents in GX require writing custom expectations.</li>
</ul>
<p>What GX does better:</p>
<ul>
<li>Broader expectation library (~200 vs Locke’s ~25).</li>
<li>Native SQL backends (Snowflake, BigQuery, Postgres) without exporting to CSV first.</li>
<li>Data Docs as a polished HTML output with a longer history.</li>
<li>Suite versioning, alerting hooks, profiler-driven auto-suite generation.</li>
</ul>
<p>The benchmark below quantifies the head-to-head on a single workflow: 5/5 ground-truth match, 275× faster end-to-end on a 7023-row churn dataset.</p>
</section>
<section id="vs-dbt-tests" class="level3">
<h3 class="anchored" data-anchor-id="vs-dbt-tests">vs dbt tests</h3>
<p>dbt is a transformation-layer tool. Tests in dbt (<code>unique</code>, <code>not_null</code>, <code>relationships</code>, <code>accepted_values</code>, and custom SQL tests) run <em>inside the warehouse</em> against the output of a dbt model. They answer “did the SQL produce the shape this model expects.”</p>
<p>What Locke does that dbt tests don’t:</p>
<ul>
<li><strong>dbt validates the transformation. Locke validates whether the data tells a coherent story afterwards.</strong> A dbt <code>unique(customer_id)</code> test passes if no rows have the same <code>customer_id</code> — but a column like <code>total_charges</code> with 6858 distinct strings out of 7023 rows passes every dbt test ever written, and Locke fires E9072 (ID-like cardinality) on it because high cardinality on a non-key column is a leakage signal.</li>
<li><strong>dbt has no equivalent of target leakage AUC.</strong> You can write a custom dbt test that computes one column’s correlation with another, but you’d be writing a Locke checker badly in SQL.</li>
<li><strong>dbt’s <code>relationships</code> test verifies FK integrity. Locke’s E9070 conditional-missingness check verifies that <code>missing(A) ⇒ missing(B)</code> doesn’t accidentally hold across columns</strong> — a different, often more useful, integrity claim.</li>
<li><strong>dbt tests pass or fail.</strong> Locke findings carry severity (Notice / Info / Warning / Error) and evidence, so the team can decide <em>how</em> to act, not just whether the build passes.</li>
</ul>
<p>Where dbt is the right tool:</p>
<ul>
<li>The validation belongs inside the warehouse (no export, no CLI hop).</li>
<li>The shape constraints are exactly what dbt’s test library covers (uniqueness, not-null, FK, value set, dbt-utils accepted ranges).</li>
<li>The dbt DAG is the source of truth for transformation correctness anyway.</li>
</ul>
<p>The honest framing: <strong>dbt tests and Locke are complementary.</strong> dbt tests catch “the transformation broke.” Locke catches “the transformation succeeded and the resulting data has a coherence problem.” A pipeline can run dbt tests at the warehouse, export to CSV / Parquet for the ML side, then run Locke on the export. Both layers add signal.</p>
</section>
<section id="vs-pandera" class="level3">
<h3 class="anchored" data-anchor-id="vs-pandera">vs Pandera</h3>
<p>Pandera is the pandas-native schema-validation library. It’s the most direct comparable for “validate a DataFrame in-process.”</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandera <span class="im">as</span> pa</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>schema <span class="op">=</span> pa.DataFrameSchema({</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"customer_id"</span>: pa.Column(<span class="bu">int</span>, pa.Check.ge(<span class="dv">0</span>)),</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"monthly_charges"</span>: pa.Column(<span class="bu">float</span>, pa.Check.in_range(<span class="dv">0</span>, <span class="dv">500</span>)),</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"churned"</span>: pa.Column(<span class="bu">bool</span>),</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>schema.validate(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>What Locke does differently:</p>
<ul>
<li><strong>Pandera reports include timestamps and walk dictionaries in iteration order. Locke reports are content-addressed.</strong> Pandera’s <code>SchemaErrors.failure_cases</code> is reproducible across runs as a <em>DataFrame</em>; the surrounding report metadata is not. Locke’s entire report serialises to canonical JSON with deterministic key ordering and content-addressed IDs.</li>
<li><strong>Pandera is a Python library. Locke is a Rust crate + CLI + CJC-Lang surface.</strong> A team that doesn’t run Python in production can still gate CI on Locke; with Pandera the validator needs a Python runtime.</li>
<li><strong>Pandera’s checks are caller-declared. Locke ships a default battery.</strong> Pandera makes you spell out every constraint; Locke fires a churn-specific battery without configuration and lets you tune severity downstream. The trade is real: Pandera gives finer control; Locke gives a faster start.</li>
<li><strong>Pandera doesn’t have a lineage primitive.</strong> The <code>TracedDataFrame</code> wrapper has no analogue.</li>
</ul>
<p>Where Pandera is the right tool:</p>
<ul>
<li>The pipeline is already pandas-native and the team wants in-process type-and-range validation as a guard.</li>
<li>The schema is well-understood and the team prefers explicit declaration over a default battery.</li>
<li>Pandera’s <code>SchemaModel</code> class-based syntax integrates cleanly with Pydantic-style type-checked codebases.</li>
</ul>
<p>The honest framing: <strong>Pandera is excellent for in-Python pipeline guards.</strong> Locke is for the after-Pandera step — produce a CSV / Parquet / JSONL, then ask “is this artifact reproducible to audit?” Pandera passes the data through a contract; Locke produces the audit artifact.</p>
</section>
<section id="vs-monte-carlo" class="level3">
<h3 class="anchored" data-anchor-id="vs-monte-carlo">vs Monte Carlo</h3>
<p>Monte Carlo is the largest of the data-observability SaaS platforms. It treats data quality as an <em>anomaly-detection</em> problem: connect MC to your warehouse, MC instruments queries, learns metadata patterns, and pages on-call when something looks weird.</p>
<p>This is a fundamentally different category of tool. Locke and Monte Carlo barely overlap in what they ask:</p>
<ul>
<li><strong>Monte Carlo is for discovery.</strong> “We didn’t know to check this query’s row count. The ML model on our metadata thinks today’s row count is anomalous given the last 30 days. Page someone.”</li>
<li><strong>Locke is for known-class checks plus reproducible audit.</strong> “We know to check that no test row has an event timestamp inside the train window. Here is the deterministic finding with content-addressed ID. CI runs the gate every PR.”</li>
</ul>
<p>A concrete failure mode each tool catches that the other doesn’t:</p>
<ul>
<li>Monte Carlo catches: a Looker dashboard’s source table silently lost a JOIN clause last week and row counts dropped 8%. Locke has no instrumentation at the warehouse layer to see this.</li>
<li>Locke catches: the production Q3 dump has 127 rows with <code>event_ts</code> inside the Q2 train window. Monte Carlo’s metadata-anomaly model wouldn’t flag 127/120000 rows; the marginal distribution at the warehouse layer barely shifted.</li>
</ul>
<p>The two tools sit at different layers of the stack and can both run in the same org without conflict. Monte Carlo answers “is anything weird I didn’t think to check”; Locke answers “for the things I know to check, here is the auditable evidence and the byte-identical fingerprint.”</p>
<p>Where Monte Carlo is the right tool:</p>
<ul>
<li>The data lives in a managed warehouse (Snowflake, BigQuery, Databricks) and MC’s connectors fit.</li>
<li>The team wants Slack / PagerDuty integration, freshness monitoring at scale, and a managed UI for incident triage.</li>
<li>The category is genuinely “discover unknown issues” — auto-baselined metadata anomalies rather than declared checks.</li>
</ul>
<p>The honest framing: <strong>Monte Carlo and Locke solve different problems.</strong> A team running Monte Carlo for warehouse-layer observability and Locke for CSV/Parquet ML-pipeline gating has no overlap to resolve. Both add signal; neither replaces the other.</p>
</section>
</section>
<section id="the-benchmark-that-earned-the-headline" class="level2">
<h2 class="anchored" data-anchor-id="the-benchmark-that-earned-the-headline">The benchmark that earned the headline</h2>
<p>The honest assessment I gave on early versions was: “Locke is competitive with Great Expectations <em>for specific use cases</em>.” I had no actual benchmark to back that. Time to run one.</p>
<section id="methodology" class="level3">
<h3 class="anchored" data-anchor-id="methodology">Methodology</h3>
<p>I wrote a deterministic synthetic-churn generator (<code>bench/locke_vs_gx/generate_churn.py</code>) that produces a 7023-row, 8-column CSV with <strong>exactly-known seeded properties</strong>:</p>
<table class="table">
<thead>
<tr class="header">
<th>Seeded fact</th>
<th>Exact count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NaN values in <code>total_charges</code></td>
<td>100</td>
</tr>
<tr class="even">
<td>Impossible <code>monthly_charges = -9999</code></td>
<td>5</td>
</tr>
<tr class="odd">
<td>Outlier rows (<code>tenure_months &gt; 200</code>)</td>
<td>17</td>
</tr>
<tr class="even">
<td>Full-row duplicates</td>
<td>23</td>
</tr>
<tr class="odd">
<td>Sortedness violations in time column</td>
<td>≥ 1</td>
</tr>
<tr class="even">
<td>Duplicate <code>customer_id</code> keys</td>
<td>23</td>
</tr>
</tbody>
</table>
<p>Then I ran two validation suites — Locke v0.5 with default settings plus <code>--target churned --primary-key customer_id --time-col last_login_unix</code>, and Great Expectations 1.17 with equivalent expectations (13 expectations covering missingness, value ranges, sortedness, compound-key uniqueness, value-set membership).</p>
<p>Both tools’ findings were dumped to JSON. A comparison script walked both result sets and asked: did each tool match ground truth?</p>
<p>The benchmark is intentionally scoped to a single workflow — “validate a CSV-shaped churn dataset, report counts of seeded data issues.” It’s not a global GX-vs-Locke claim; it’s a calibration of one workflow Locke is designed for.</p>
</section>
<section id="a-real-finding-byte-for-byte" class="level3">
<h3 class="anchored" data-anchor-id="a-real-finding-byte-for-byte">A real finding, byte-for-byte</h3>
<p>To make the determinism claim concrete, here is a literal <code>ValidationFinding</code> from the benchmark’s <code>locke_results.json</code> — the impossible-<code>monthly_charges</code> outlier:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"id"</span><span class="fu">:</span> <span class="st">"f615af023438bcb5"</span><span class="fu">,</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"code"</span><span class="fu">:</span> <span class="st">"E9041"</span><span class="fu">,</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"severity"</span><span class="fu">:</span> <span class="st">"warning"</span><span class="fu">,</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"message"</span><span class="fu">:</span> <span class="st">"column `monthly_charges` has 5 extreme outliers (3×IQR or |mod-Z| ≥ 5.0)"</span><span class="fu">,</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"column"</span><span class="fu">:</span> <span class="st">"monthly_charges"</span><span class="fu">,</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"row_range"</span><span class="fu">:</span> <span class="kw">null</span><span class="fu">,</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"sample_size"</span><span class="fu">:</span> <span class="dv">7023</span><span class="fu">,</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"evidence"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span><span class="dt">"kind"</span><span class="fu">:</span> <span class="st">"count"</span><span class="fu">,</span>  <span class="dt">"label"</span><span class="fu">:</span> <span class="st">"n_extreme"</span><span class="fu">,</span>  <span class="dt">"value"</span><span class="fu">:</span> <span class="dv">5</span><span class="fu">}</span><span class="ot">,</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span><span class="dt">"kind"</span><span class="fu">:</span> <span class="st">"sample"</span><span class="fu">,</span> <span class="dt">"label"</span><span class="fu">:</span> <span class="st">"sample"</span><span class="fu">,</span>     <span class="dt">"value"</span><span class="fu">:</span> <span class="st">"row150=-9999,row151=-9999,row152=-9999"</span><span class="fu">}</span><span class="ot">,</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span><span class="dt">"kind"</span><span class="fu">:</span> <span class="st">"range"</span><span class="fu">,</span>  <span class="dt">"label"</span><span class="fu">:</span> <span class="st">"iqr_q1_q3"</span><span class="fu">,</span>  <span class="dt">"min"</span><span class="fu">:</span> <span class="fl">45.974999999999994</span><span class="fu">,</span> <span class="dt">"max"</span><span class="fu">:</span> <span class="fl">95.27</span><span class="fu">}</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="ot">]</span><span class="fu">,</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"assumptions"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"extreme outliers usually indicate sensor errors, sentinel values, or unit-mix-ups"</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  <span class="ot">]</span><span class="fu">,</span></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"suggested_next_checks"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"verify physical plausibility (e.g. age = 999, temperature = -9999)"</span><span class="ot">,</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"consider declaring sentinel values as nulls via NullMask"</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  <span class="ot">]</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a><span class="fu">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The <code>id</code> field is <code>f615af023438bcb5</code> — a 64-bit content fingerprint over the rest of the structure. Rerunning the same benchmark on a different machine produces the same 16 hex characters. That’s the property that makes the gate diff in Scenario 1 work: “unchanged” findings are recognised by ID, not by message text.</p>
<p>Compare to the equivalent Great Expectations result for the same five rows (verbatim from <code>gx_results.json</code>):</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"name"</span><span class="fu">:</span> <span class="st">"monthly_charges_in_range[-100,500]"</span><span class="fu">,</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"severity"</span><span class="fu">:</span> <span class="st">"Error"</span><span class="fu">,</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"success"</span><span class="fu">:</span> <span class="kw">false</span><span class="fu">,</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"details"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"element_count"</span><span class="fu">:</span> <span class="dv">7023</span><span class="fu">,</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"unexpected_count"</span><span class="fu">:</span> <span class="dv">5</span><span class="fu">,</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"unexpected_percent"</span><span class="fu">:</span> <span class="fl">0.07118041435995925</span><span class="fu">,</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"partial_unexpected_list"</span><span class="fu">:</span> <span class="ot">[</span><span class="dv">-9999</span><span class="ot">,</span> <span class="dv">-9999</span><span class="ot">,</span> <span class="dv">-9999</span><span class="ot">,</span> <span class="dv">-9999</span><span class="ot">,</span> <span class="dv">-9999</span><span class="ot">]</span><span class="fu">,</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"partial_unexpected_counts"</span><span class="fu">:</span> <span class="ot">[</span><span class="fu">{</span><span class="dt">"value"</span><span class="fu">:</span> <span class="dv">-9999</span><span class="fu">,</span> <span class="dt">"count"</span><span class="fu">:</span> <span class="dv">5</span><span class="fu">}</span><span class="ot">]</span><span class="fu">,</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"partial_unexpected_index_list"</span><span class="fu">:</span> <span class="ot">[</span><span class="dv">150</span><span class="ot">,</span> <span class="dv">151</span><span class="ot">,</span> <span class="dv">152</span><span class="ot">,</span> <span class="dv">153</span><span class="ot">,</span> <span class="dv">154</span><span class="ot">]</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">}</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="fu">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Both tools catch the same five rows. GX surfaces more detail per finding (sample list, index list, exact percent). Locke surfaces typed evidence kinds (<code>count</code>, <code>sample</code>, <code>range</code>), declared assumptions, suggested next checks — and the stable ID. They’re answering different questions about the same fact.</p>
</section>
<section id="detection-results" class="level3">
<h3 class="anchored" data-anchor-id="detection-results">Detection results</h3>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Fact</th>
<th>Ground truth</th>
<th>Locke (code, count, severity)</th>
<th>GX (count, severity)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NaN in <code>total_charges</code></td>
<td>100</td>
<td>E9007 (100, info)</td>
<td>100 (error)</td>
</tr>
<tr class="even">
<td>Impossible <code>monthly_charges</code></td>
<td>5</td>
<td>E9041 (5, warning)</td>
<td>5 (error)</td>
</tr>
<tr class="odd">
<td>Outlier <code>tenure_months</code></td>
<td>17</td>
<td>E9041 (17, warning)</td>
<td>17 (warning)</td>
</tr>
<tr class="even">
<td>Full-row duplicates</td>
<td>23</td>
<td>E9003 (23, notice)</td>
<td>46 = 23×2 (error)</td>
</tr>
<tr class="odd">
<td>Sortedness violation</td>
<td>≥ 1</td>
<td>E9050 (1, warning)</td>
<td>1 (warning)</td>
</tr>
<tr class="even">
<td>Duplicate <code>customer_id</code> keys</td>
<td>23</td>
<td>E9004 (23, error)</td>
<td>(no equivalent in suite)</td>
</tr>
</tbody>
</table>
<p><strong>Both tools matched ground truth 5 / 5 on the quantitative facts.</strong> The detection accuracy is identical for the kinds of issues a real churn-data pipeline ships with.</p>
<p>A few honest notes on the table:</p>
<ul>
<li><strong>GX reports duplicate rows as 46 = 23 × 2</strong> because <code>ExpectCompoundColumnsToBeUnique</code> reports all rows in any non-unique group. Locke reports the <em>extras</em> (23). Different question, both correct.</li>
<li><strong>Severity disagreements are policy, not detection.</strong> GX defaults every failed expectation to <code>Error</code>. Locke uses a configurable severity ladder where 100 missing out of 7023 (1.4%) lands at <code>Info</code> — the floor of a four-rung ladder where Warning means ≥10% and Error means ≥50%. Locke’s ladder is tunable via <code>BeliefPenalty</code>; GX’s is per-expectation config.</li>
<li><strong>Locke caught the missing-<code>total_charges</code> count via E9007 (sentinel-value detection)</strong> because the CSV reader inferred the column as <code>Str</code> (empty cells aren’t parseable as numbers). Same count, different code, lighter severity. The findings are equivalent; the tool routed through a different channel.</li>
</ul>
</section>
<section id="timing" class="level3">
<h3 class="anchored" data-anchor-id="timing">Timing</h3>
<table class="table">
<thead>
<tr class="header">
<th>Tool</th>
<th>End-to-end wall-clock</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Great Expectations 1.17 (Python 3.11)</td>
<td><strong>45.9 s</strong></td>
</tr>
<tr class="even">
<td>Locke v0.5 debug build</td>
<td>985 ms</td>
</tr>
<tr class="odd">
<td><strong>Locke v0.5 release build</strong></td>
<td><strong>167 ms</strong></td>
</tr>
</tbody>
</table>
<p>That’s a <strong>275× speedup</strong> in release mode against the same dataset finding the same things. Most of GX’s time is Python startup + GX context init + ephemeral data-source setup, which dominates for short batch runs. Locke is a single Rust binary with no startup overhead.</p>
<p>For a CI gate that runs every PR, that difference is “imperceptible vs visibly slow.” For a nightly batch over a million datasets, it’s the difference between “finished by morning” and “still running.”</p>
</section>
<section id="built-in-checks-locke-runs-that-gx-doesnt-out-of-the-box" class="level3">
<h3 class="anchored" data-anchor-id="built-in-checks-locke-runs-that-gx-doesnt-out-of-the-box">Built-in checks Locke runs that GX doesn’t out of the box</h3>
<p>On the actual benchmark dataset:</p>
<ul>
<li><strong>E9004 — duplicate primary-key detection</strong> fired with the exact 23 violations on <code>customer_id</code>. GX has no equivalent unless you write a custom expectation.</li>
<li><strong>E9007 — sentinel-value detection</strong> caught the 100 empty strings in <code>total_charges</code>. GX requires <code>expect_column_values_to_not_be_null</code> (which works for null but not the empty-string sentinel form here).</li>
<li><strong>E9072 — ID-like cardinality hint</strong> fired three times — on <code>customer_id</code>, <code>last_login_unix</code>, and <code>total_charges</code> (which had 6858 distinct strings out of 7023 rows, looking like an identifier leaking as a feature). GX has no equivalent default check.</li>
</ul>
<p>These aren’t fancy — they’re the kind of checks a churn pipeline silently fails on for months until someone notices the model is memorising customer IDs. Locke fires them by default.</p>
</section>
<section id="built-in-checks-gx-runs-that-locke-doesnt-out-of-the-box" class="level3">
<h3 class="anchored" data-anchor-id="built-in-checks-gx-runs-that-locke-doesnt-out-of-the-box">Built-in checks GX runs that Locke doesn’t out of the box</h3>
<p>To be honest about the other direction:</p>
<ul>
<li><code>ExpectColumnDistinctValuesToBeInSet</code> for <code>plan</code> / <code>country</code> — Locke has E9020–E9022 schema mismatch but no value-set-membership check yet</li>
<li><code>ExpectColumnValuesToBeIncreasing(strictly=True)</code> — Locke only checks non-decreasing</li>
<li>User-declared mean / quantile range expectations (Locke surfaces the values but doesn’t accept caller-declared ranges in the default validate path)</li>
<li>~180 other expectations covering regex, length, JSON-schema, custom SQL queries, etc.</li>
</ul>
<p>GX has a <em>much</em> broader expectation library overall. For the specific subset that matters for churn validation, Locke is at parity or ahead. For the general case, GX still wins on breadth.</p>
</section>
</section>
<section id="what-scale-locke-handles" class="level2">
<h2 class="anchored" data-anchor-id="what-scale-locke-handles">What scale Locke handles</h2>
<p>The benchmark above is on a small (7K-row) dataset. For a more useful answer, I ran a separate scale benchmark on synthetic data with four mixed-type columns:</p>
<section id="single-shot-validate" class="level3">
<h3 class="anchored" data-anchor-id="single-shot-validate">Single-shot <code>validate()</code></h3>
<table class="table">
<thead>
<tr class="header">
<th>Rows</th>
<th>Wall clock</th>
<th>Per-row</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10,000</td>
<td>100 ms</td>
<td>10.08 µs/row</td>
</tr>
<tr class="even">
<td>100,000</td>
<td>1.19 s</td>
<td>11.90 µs/row</td>
</tr>
<tr class="odd">
<td>1,000,000</td>
<td>17.45 s</td>
<td>17.45 µs/row</td>
</tr>
</tbody>
</table>
<p>Per-row cost grows mildly with <code>log n</code> because of full-row byte-hashing (duplicate detection) and sort-based outlier detection.</p>
</section>
<section id="drift-compare" class="level3">
<h3 class="anchored" data-anchor-id="drift-compare">Drift <code>compare()</code></h3>
<table class="table">
<thead>
<tr class="header">
<th>Rows / side</th>
<th>Wall clock</th>
<th>Per-row</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10,000</td>
<td>90 ms</td>
<td>4.51 µs/row</td>
</tr>
<tr class="even">
<td>100,000</td>
<td>525 ms</td>
<td>2.63 µs/row</td>
</tr>
<tr class="odd">
<td>1,000,000</td>
<td>5.68 s</td>
<td>2.84 µs/row</td>
</tr>
</tbody>
</table>
<p>Flat per-row cost at scale because the sort dominates and Rust’s sort is well-optimised. 1M + 1M rows in 5.7 seconds.</p>
</section>
<section id="streaming-validator-chunked-ingest" class="level3">
<h3 class="anchored" data-anchor-id="streaming-validator-chunked-ingest">Streaming validator (chunked ingest)</h3>
<table class="table">
<thead>
<tr class="header">
<th>Total rows</th>
<th>Chunks</th>
<th>Wall clock</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>100,000</td>
<td>10</td>
<td>609 ms</td>
</tr>
<tr class="even">
<td>1,000,000</td>
<td>100</td>
<td>8.69 s</td>
</tr>
<tr class="odd">
<td><strong>5,000,000</strong></td>
<td><strong>500</strong></td>
<td><strong>16.33 s</strong></td>
</tr>
</tbody>
</table>
<p>About <strong>310,000 rows/second</strong> sustained streaming throughput.</p>
</section>
<section id="streaming-ks-d-vs-single-shot-ks-d" class="level3">
<h3 class="anchored" data-anchor-id="streaming-ks-d-vs-single-shot-ks-d">Streaming KS D vs single-shot KS D</h3>
<table class="table">
<thead>
<tr class="header">
<th>Rows</th>
<th>Streaming KS</th>
<th>Single-shot KS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10,000</td>
<td><strong>1 ms</strong></td>
<td>4 ms</td>
</tr>
<tr class="even">
<td>100,000</td>
<td><strong>32 ms</strong></td>
<td>66 ms</td>
</tr>
<tr class="odd">
<td>1,000,000</td>
<td><strong>62 ms</strong></td>
<td>107 ms</td>
</tr>
</tbody>
</table>
<p>Streaming is <strong>~2× faster</strong> because the BTreeMap-ECDF is already sorted at ingest time, so the merge-walk at query time skips the sort. The result is bit-identical to single-shot KS — proved by a unit test.</p>
</section>
<section id="practical-scale-matrix-for-a-churn-use-case" class="level3">
<h3 class="anchored" data-anchor-id="practical-scale-matrix-for-a-churn-use-case">Practical scale matrix for a churn use case</h3>
<table class="table">
<thead>
<tr class="header">
<th>Customers</th>
<th>Path</th>
<th>Wall clock</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>≤ 100k</td>
<td>single-shot</td>
<td>sub-2s</td>
</tr>
<tr class="even">
<td>100k – 1M</td>
<td>single-shot</td>
<td>2-20s</td>
</tr>
<tr class="odd">
<td>1M – 10M</td>
<td>streaming</td>
<td>~30s</td>
</tr>
<tr class="even">
<td>10M – 100M</td>
<td>streaming with caps</td>
<td>~5 min</td>
</tr>
<tr class="odd">
<td>100M+</td>
<td>streaming + accept approximate dup counts, or shard</td>
<td>longer</td>
</tr>
</tbody>
</table>
<p>For a typical SaaS churn dataset (1k–10M customers), Locke runs comfortably as part of every CI build. For 10M–100M, it’s an overnight batch.</p>
</section>
</section>
<section id="the-ci-workflow-locke-was-built-for" class="level2">
<h2 class="anchored" data-anchor-id="the-ci-workflow-locke-was-built-for">The CI workflow Locke was built for</h2>
<p>Scenario 1 above sketched the workflow. Here it is wired into a CI config, showing the exact JSON snapshot file the workflow checks in.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># After every successful model training, snapshot the baseline:</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="ex">cjcl</span> locke validate train_2026q2.csv <span class="dt">\</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">--target</span> churned <span class="dt">\</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">--primary-key</span> customer_id <span class="dt">\</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">--time-col</span> event_ts <span class="dt">\</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">--max-timestamp</span> 1719792000000 <span class="dt">\</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">--save-json</span> baselines/2026q2_baseline.json <span class="dt">\</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">--html</span> reports/2026q2.html</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The <code>baselines/2026q2_baseline.json</code> that lands in the repo looks like this (truncated to one finding for brevity):</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode json code-with-copy"><code class="sourceCode json"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">{</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"schema_version"</span><span class="fu">:</span> <span class="dv">1</span><span class="fu">,</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"run_id"</span><span class="fu">:</span> <span class="st">"1075bbad9d9b882f"</span><span class="fu">,</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"input"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"dataset_label"</span><span class="fu">:</span> <span class="st">"train_2026q2.csv"</span><span class="fu">,</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"n_rows"</span><span class="fu">:</span> <span class="dv">124083</span><span class="fu">,</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"n_cols"</span><span class="fu">:</span> <span class="dv">14</span><span class="fu">,</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="dt">"column_types"</span><span class="fu">:</span> <span class="fu">{</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"churned"</span><span class="fu">:</span> <span class="st">"Bool"</span><span class="fu">,</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"customer_id"</span><span class="fu">:</span> <span class="st">"Int"</span><span class="fu">,</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"event_ts"</span><span class="fu">:</span> <span class="st">"Int"</span><span class="fu">,</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"monthly_charges"</span><span class="fu">:</span> <span class="st">"Float"</span><span class="fu">,</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"tenure_months"</span><span class="fu">:</span> <span class="st">"Int"</span><span class="fu">,</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"..."</span><span class="fu">:</span> <span class="st">"..."</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">}</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">},</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"severity_counts"</span><span class="fu">:</span> <span class="fu">{</span><span class="dt">"info"</span><span class="fu">:</span> <span class="dv">6</span><span class="fu">,</span> <span class="dt">"notice"</span><span class="fu">:</span> <span class="dv">2</span><span class="fu">,</span> <span class="dt">"warning"</span><span class="fu">:</span> <span class="dv">0</span><span class="fu">,</span> <span class="dt">"error"</span><span class="fu">:</span> <span class="dv">0</span><span class="fu">},</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"findings"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">{</span></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"id"</span><span class="fu">:</span> <span class="st">"5a0309e1047ccdf8"</span><span class="fu">,</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"code"</span><span class="fu">:</span> <span class="st">"E9004"</span><span class="fu">,</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"severity"</span><span class="fu">:</span> <span class="st">"notice"</span><span class="fu">,</span></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"message"</span><span class="fu">:</span> <span class="st">"key column `customer_id` has 0 duplicate values across 0 groups"</span><span class="fu">,</span></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"column"</span><span class="fu">:</span> <span class="st">"customer_id"</span><span class="fu">,</span></span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"evidence"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a>        <span class="fu">{</span><span class="dt">"kind"</span><span class="fu">:</span> <span class="st">"count"</span><span class="fu">,</span> <span class="dt">"label"</span><span class="fu">:</span> <span class="st">"duplicate_keys"</span><span class="fu">,</span>   <span class="dt">"value"</span><span class="fu">:</span> <span class="dv">0</span><span class="fu">}</span><span class="ot">,</span></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>        <span class="fu">{</span><span class="dt">"kind"</span><span class="fu">:</span> <span class="st">"count"</span><span class="fu">,</span> <span class="dt">"label"</span><span class="fu">:</span> <span class="st">"duplicate_groups"</span><span class="fu">,</span> <span class="dt">"value"</span><span class="fu">:</span> <span class="dv">0</span><span class="fu">}</span></span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a>      <span class="ot">]</span><span class="fu">,</span></span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"assumptions"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>        <span class="st">"key uniqueness assumed; primary-key constraint not enforced by cjc-data"</span></span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a>      <span class="ot">]</span><span class="fu">,</span></span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>      <span class="dt">"suggested_next_checks"</span><span class="fu">:</span> <span class="ot">[</span><span class="st">"check ingest pipeline; primary keys should be unique"</span><span class="ot">]</span></span>
<span id="cb23-33"><a href="#cb23-33" aria-hidden="true" tabindex="-1"></a>    <span class="fu">}</span></span>
<span id="cb23-34"><a href="#cb23-34" aria-hidden="true" tabindex="-1"></a>  <span class="ot">]</span><span class="fu">,</span></span>
<span id="cb23-35"><a href="#cb23-35" aria-hidden="true" tabindex="-1"></a>  <span class="dt">"assumptions"</span><span class="fu">:</span> <span class="ot">[</span></span>
<span id="cb23-36"><a href="#cb23-36" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NaN treated as missing for Float columns; other types report a limitation"</span><span class="ot">,</span></span>
<span id="cb23-37"><a href="#cb23-37" aria-hidden="true" tabindex="-1"></a>    <span class="st">"missingness, drift, and belief use deterministic Kahan summation"</span><span class="ot">,</span></span>
<span id="cb23-38"><a href="#cb23-38" aria-hidden="true" tabindex="-1"></a>    <span class="st">"duplicate detection is byte-canonical"</span></span>
<span id="cb23-39"><a href="#cb23-39" aria-hidden="true" tabindex="-1"></a>  <span class="ot">]</span></span>
<span id="cb23-40"><a href="#cb23-40" aria-hidden="true" tabindex="-1"></a><span class="fu">}</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The <code>run_id</code> at the top is a 64-bit fingerprint over the full report’s content. Two runs on the same data produce the same <code>run_id</code>. The team checks <code>baselines/2026q2_baseline.json</code> into git, and the diff on the next PR is meaningful: any non-zero diff means data quality changed.</p>
<p>In CI:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode yaml code-with-copy"><code class="sourceCode yaml"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># .github/workflows/data-quality-gate.yml (excerpt)</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="kw">-</span><span class="at"> </span><span class="fu">name</span><span class="kw">:</span><span class="at"> Validate production data against Q2 baseline</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">  run</span><span class="kw">: </span><span class="ch">|</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>    cjcl locke gate \</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>      baselines/2026q2_baseline.json \</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>      data/prod_$(date +%Y%m%d).csv \</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>      --fail-on warning</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Exit code is non-zero when anything crosses the warning threshold. The structural diff goes to stdout. A human looks at it and decides: was this drift expected (new product launch, seasonal effect) or did a pipeline bug leak training-window timestamps into the test set?</p>
<p>The diff’s findings are <strong>content-addressed</strong> — <code>id=1075bbad9d9b882f</code> is a 64-bit fingerprint over the report’s contents. Two CI runs over the same data on different machines produce the same fingerprint. That’s the property that makes the snapshot-and-diff workflow work at all.</p>
</section>
<section id="the-stakeholder-html-report" class="level2">
<h2 class="anchored" data-anchor-id="the-stakeholder-html-report">The stakeholder HTML report</h2>
<p>The <code>--html PATH</code> flag produces a single self-contained HTML file with:</p>
<ul>
<li>Severity-color-coded summary cards</li>
<li>Findings table sorted by (severity, code, column)</li>
<li>Inline-SVG correlation heatmap (when ≥ 3 numeric columns)</li>
<li>Assumptions panel</li>
<li>Run-ID + schema-version footer</li>
<li>Total weight ~5KB, no external assets, no JavaScript</li>
</ul>
<p>For a PM who wants “tell me what’s wrong with this CSV in 30 seconds,” the HTML report is the right shape.</p>
</section>
<section id="locke-is-not-a-one-stop-ml-tool" class="level2">
<h2 class="anchored" data-anchor-id="locke-is-not-a-one-stop-ml-tool">Locke is not a one-stop ML tool</h2>
<p>Worth saying directly: Locke covers the data-quality and drift-monitoring legs of an ML pipeline. It does <strong>not</strong>:</p>
<ul>
<li>Train models. Use scikit-learn / xgboost / lifelines for that.</li>
<li>Run causal inference. The <code>CausalDag</code> registers user-declared assumptions; it doesn’t estimate effects. Use DoWhy or EconML for actual causal modeling.</li>
<li>Replace experiment-tracking. Use mlflow / wandb.</li>
<li>Read Parquet contents yet. v0.1.10 recognizes the file structure and gives a clear diagnostic; the full decoder is on the roadmap.</li>
<li>Connect to data warehouses. Snowflake / BigQuery / Postgres support is not yet there. Export to CSV / JSONL first.</li>
</ul>
<p>The right framing is <strong>“Locke handles the data hygiene + drift monitoring + reproducible audit trail; you bring the rest of your stack.”</strong></p>
</section>
<section id="what-i-think-the-determinism-contract-actually-buys-you" class="level2">
<h2 class="anchored" data-anchor-id="what-i-think-the-determinism-contract-actually-buys-you">What I think the determinism contract actually buys you</h2>
<p>Three concrete things:</p>
<ol type="1">
<li><p><strong>Comparable reports across runs.</strong> Two CI runs over the same dataset produce byte-identical reports. You can <code>diff</code> them. You can store them in git. You can compute a fingerprint and cache training jobs on it.</p></li>
<li><p><strong>Reproducible audit trails.</strong> Insurance churn analyses get scrutinised. A regulator asking “show me the data quality report you used to validate this dataset on 2026-Q3” deserves a reproducible answer. Locke gives that.</p></li>
<li><p><strong>CI gates that don’t flake.</strong> Most data-validation tools sometimes report different “validation_result UUIDs” on identical data because of internal <code>dict</code> iteration or wall-clock metadata. Locke’s IDs are content fingerprints. There’s no flake.</p></li>
</ol>
<p>That third property is the one I’d defend hardest. It sounds boring; it’s what makes the snapshot-and-diff workflow viable in the first place.</p>
</section>
<section id="the-formal-model-how-confidence-composes" class="level2">
<h2 class="anchored" data-anchor-id="the-formal-model-how-confidence-composes">The formal model: how confidence composes</h2>
<p>Locke v0.1’s evidence-and-belief story isn’t pure heuristic — there’s a small, deliberately conservative semantics underneath. This section spells out the model: how confidence is represented, how it composes under transformation, what weakens it, how it propagates, and the algebra it satisfies today versus the parts deferred to v0.2. Being explicit here matters because “epistemic layer” is only as good as the formal object underneath it.</p>
<section id="confidence-representation" class="level3">
<h3 class="anchored" data-anchor-id="confidence-representation">Confidence representation</h3>
<p>Every Locke report carries an 8-dimensional <code>BeliefScore</code>:</p>
<pre><code>BeliefScore : {schema, missingness, drift, leakage, lineage, sample, duplication, constraint} → [0, 1]
overall_score : BeliefScore → [0, 1]</code></pre>
<p>Each axis lives on <code>[0, 1]</code> where 1 means “no evidence against the dataset on this axis.” There is no single number; the overall is a weighted mean controlled by a <code>BeliefWeights</code> vector. The choice of 8 axes is deliberate — each maps to a disjoint class of finding codes:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Axis</th>
<th>Finding-code range</th>
<th>What evidence weakens it</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>schema</td>
<td>E9020–E9029</td>
<td>type mismatches, unexpected columns, missing columns</td>
</tr>
<tr class="even">
<td>missingness</td>
<td>E9001–E9009</td>
<td>NaN rates, joint missingness, sentinel detection</td>
</tr>
<tr class="odd">
<td>drift</td>
<td>E9030–E9039</td>
<td>KS shift, mean/std shift, categorical TVD</td>
</tr>
<tr class="even">
<td>leakage</td>
<td>E9060–E9069</td>
<td>target-AUC, ID-like cardinality, proxy candidates</td>
</tr>
<tr class="odd">
<td>lineage</td>
<td>E9050–E9059</td>
<td>unsorted time, train/test overlap, gap detection</td>
</tr>
<tr class="even">
<td>sample</td>
<td>(computed)</td>
<td>row count below n_min, sampling-cap engaged</td>
</tr>
<tr class="odd">
<td>duplication</td>
<td>E9003–E9004</td>
<td>full-row dups, primary-key dups, dup-conditioning</td>
</tr>
<tr class="even">
<td>constraint</td>
<td>E9040–E9049</td>
<td>outliers, impossible values, constants</td>
</tr>
</tbody>
</table>
<p>Adding a new check assigns it to exactly one axis. That’s a hard invariant in the codebase, not a guideline.</p>
</section>
<section id="confidence-composition-under-transformation" class="level3">
<h3 class="anchored" data-anchor-id="confidence-composition-under-transformation">Confidence composition under transformation</h3>
<p>A <code>LockeIdea</code> derived from one or more parent ideas / impressions inherits a belief score:</p>
<pre><code>belief(child) = meet(belief(parent_i)) ∧ transform_factor(op)   for each parent i
where meet(a, b) = component-wise min on the 8 axes</code></pre>
<p>The <strong>meet</strong> (component-wise min) is the deliberately conservative composition rule. A filter cannot improve the missingness score — at best it preserves it. A join cannot improve any axis below the minimum of the two inputs. Belief is monotonically non-increasing under derivation.</p>
<p><code>transform_factor(op)</code> is a per-operator scalar in <code>[0, 1]^8</code> that accounts for op-specific weakening:</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Operation</th>
<th>transform_factor effect</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>filter(predicate)</code></td>
<td>preserves all 8 axes; transform_factor = identity</td>
</tr>
<tr class="even">
<td><code>group_by + summarise</code></td>
<td>weakens <code>sample</code> proportional to group-size reduction</td>
</tr>
<tr class="odd">
<td><code>join(left, right, key)</code></td>
<td>weakens <code>lineage</code> and <code>constraint</code> proportional to FK match rate</td>
</tr>
<tr class="even">
<td><code>with_column(derived = f(cols))</code></td>
<td>weakens <code>leakage</code> if f spans target-correlated columns</td>
</tr>
<tr class="odd">
<td><code>sample(n)</code></td>
<td>weakens <code>sample</code> proportional to <code>n / total_rows</code></td>
</tr>
<tr class="even">
<td><code>bind_rows</code> / <code>bind_cols</code></td>
<td>weakens <code>lineage</code> because the merge boundary is a new source of disagreement</td>
</tr>
</tbody>
</table>
<p>These are shipped today, conservative, documented in the source. The full algebra (per-axis composition rules per operator instead of a global meet) is a v0.2 goal.</p>
</section>
<section id="what-weakens-confidence" class="level3">
<h3 class="anchored" data-anchor-id="what-weakens-confidence">What weakens confidence</h3>
<p>The penalty function is the only place evidence turns into a score reduction:</p>
<pre><code>penalty(finding) = w_axis(finding.code) × severity_weight(finding.severity) × evidence_intensity(finding.evidence)
axis_score(axis) = 1 − Σ penalty(f) for f in findings if axis_of(f.code) == axis    clamped to [0, 1]</code></pre>
<p>Three properties:</p>
<ol type="1">
<li><strong><code>severity_weight</code> is a fixed ladder</strong>: <code>{Info: 0.05, Notice: 0.15, Warning: 0.40, Error: 1.00}</code> — same on every run. No floating arithmetic that depends on iteration order.</li>
<li><strong><code>evidence_intensity</code> is bounded by 1.</strong> A single finding cannot drop an axis below 0; multiple findings sum but are clamped at the end.</li>
<li><strong>The penalty model is swappable.</strong> <code>BeliefPenalty::user_supplied(...)</code> lets a team install a custom ladder; the audit then records the penalty model’s identity. The default ladder is just one entry in a registry.</li>
</ol>
</section>
<section id="how-propagation-is-modeled" class="level3">
<h3 class="anchored" data-anchor-id="how-propagation-is-modeled">How propagation is modeled</h3>
<p>The lineage DAG carries belief from impressions to ideas via the <code>meet</code>-and-<code>transform_factor</code> rule. Here’s an evidence-propagation diagram for a 4-step pipeline:</p>
<div class="cell" data-fig-width="9">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    I["events.csv&lt;br/&gt;&lt;b&gt;impression&lt;/b&gt;&lt;br/&gt;[1.00, 1.00, 1.00, 1.00,&lt;br/&gt;1.00, 1.00, 1.00, 1.00]"]:::imp
    I --&gt;|"observe()&lt;br/&gt;tf = identity"| O["raw_events&lt;br/&gt;&lt;b&gt;idea&lt;/b&gt;&lt;br/&gt;[1.00, 1.00, 1.00, 1.00,&lt;br/&gt;0.95, 1.00, 1.00, 1.00]"]:::idea
    O --&gt;|"filter(active==1)&lt;br/&gt;tf = identity"| F["active_events&lt;br/&gt;&lt;b&gt;idea&lt;/b&gt;&lt;br/&gt;[1.00, 0.99, 1.00, 1.00,&lt;br/&gt;0.95, 0.98, 1.00, 1.00]"]:::idea
    F --&gt;|"group_by(plan_tier)&lt;br/&gt;tf: sample × 0.80"| G["grouped&lt;br/&gt;&lt;b&gt;idea&lt;/b&gt;&lt;br/&gt;[1.00, 0.99, 1.00, 1.00,&lt;br/&gt;0.95, 0.78, 1.00, 1.00]"]:::idea
    G --&gt;|"with_column(churn_rate)&lt;br/&gt;tf: leakage × 0.90"| W["labeled&lt;br/&gt;&lt;b&gt;idea&lt;/b&gt;&lt;br/&gt;[1.00, 0.99, 1.00, 0.90,&lt;br/&gt;0.95, 0.78, 1.00, 1.00]"]:::idea

    classDef imp fill:#e8f4fd,stroke:#2196F3,stroke-width:2px
    classDef idea fill:#fff3e0,stroke:#FF9800,stroke-width:1px
</pre>
</div>
<p>Evidence propagation through a 4-step pipeline. Each node carries an 8-dim belief vector [schema, missingness, drift, leakage, lineage, sample, duplication, constraint]. Edges apply transform_factor. Belief is monotonically non-increasing along any path — the rightmost node is component-wise ≤ the leftmost.</p>
</div>
</div>
</div>
<p>Reading the diagram: each node label lists the 8-axis belief vector in fixed order. The <code>observe()</code> step pre-weakened <code>lineage</code> to 0.95 because raw-CSV ingestion drops some provenance (no upstream observation timestamps). The <code>filter</code> step weakened <code>missingness</code> and <code>sample</code> because filtering revealed a column with a higher local NaN rate, and dropped row count. The <code>group_by</code> step weakened <code>sample</code> further because per-group sample sizes are smaller. The <code>with_column(churn_rate)</code> step weakened <code>leakage</code> because the derived column directly references the target.</p>
<p>Crucially: every axis-wise value on the rightmost node is ≤ the leftmost. Composition never improves belief on any axis.</p>
</section>
<section id="deterministic-update-rules" class="level3">
<h3 class="anchored" data-anchor-id="deterministic-update-rules">Deterministic update rules</h3>
<p>Every step in the propagation uses:</p>
<ul>
<li><strong>Kahan summation</strong> for penalty accumulation (avoid FP-order-dependent drift).</li>
<li><strong><code>BTreeMap</code></strong> for finding aggregation by axis (no <code>HashMap</code> iteration nondeterminism).</li>
<li><strong><code>f64::total_cmp</code></strong> for floating comparisons (NaN behaves consistently, not implementation-defined).</li>
<li><strong>No FMA</strong> in the SIMD paths under penalty arithmetic (bit-identical across CPUs).</li>
<li><strong>Single-threaded execution</strong> in v0.1 — even when parallel column-validation lands in v0.2, the reduction phase will be order-fixed.</li>
</ul>
<p>The contract: same input bytes → same belief vector. The lineage diagram above is reproducible byte-for-byte by anyone running the same pipeline on the same inputs.</p>
</section>
<section id="confidence-algebra-shipped-vs-planned" class="level3">
<h3 class="anchored" data-anchor-id="confidence-algebra-shipped-vs-planned">Confidence algebra (shipped vs planned)</h3>
<p>The composition operator <code>meet</code> plus the identity <code>⊤ = [1, 1, 1, 1, 1, 1, 1, 1]</code> satisfies five algebraic properties today:</p>
<table class="table">
<thead>
<tr class="header">
<th>Property</th>
<th>Statement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Identity</strong></td>
<td><code>meet(b, ⊤) = b</code></td>
</tr>
<tr class="even">
<td><strong>Idempotence</strong></td>
<td><code>meet(b, b) = b</code></td>
</tr>
<tr class="odd">
<td><strong>Monotonicity</strong></td>
<td><code>meet(b, c) ≤ b</code> component-wise</td>
</tr>
<tr class="even">
<td><strong>Commutativity</strong></td>
<td><code>meet(b, c) = meet(c, b)</code></td>
</tr>
<tr class="odd">
<td><strong>Associativity</strong></td>
<td><code>meet(meet(a, b), c) = meet(a, meet(b, c))</code></td>
</tr>
</tbody>
</table>
<p>Together, <code>(BeliefScore, meet, ⊤)</code> is a commutative idempotent monoid with identity — i.e.&nbsp;a <strong>meet-semilattice</strong> in lattice-theoretic terms. The deterministic update rules above make the algebra computable to bit-identical results across runs. That’s the formal object the snapshot-and-diff workflow relies on; without monotonicity, “appeared / disappeared” diffs over composed pipelines wouldn’t be well-defined.</p>
<p>Planned for v0.2:</p>
<ul>
<li><strong>Per-axis composition rules instead of a global <code>meet</code>.</strong> Some axes (e.g.&nbsp;<code>lineage</code>) compose by min; others (e.g.&nbsp;<code>sample</code>) should compose by product. A typed rule per axis would be more faithful to what each axis measures.</li>
<li><strong>A <code>join</code> operator</strong> for combining alternative views of the same dataset (the lattice-theoretic dual of <code>meet</code>). Currently absent; the algebra is meet-only, which means alternative-view combination is undefined.</li>
<li><strong>A continuous-domain semantics</strong> for transformations that span a parameter (e.g.&nbsp;<code>filter(predicate)</code> with predicate selectivity <code>s ∈ [0, 1]</code>). v0.1 treats every filter the same; v0.2 would parameterise <code>transform_factor</code> by <code>s</code>.</li>
<li><strong>A formal proof</strong> of the conservation property: under the meet algebra, the gate-diff workflow’s <code>appeared</code> set is exactly the set of findings whose axes degraded between snapshots. This is true by construction today; v0.2 would have it written down as a theorem with a checked proof.</li>
</ul>
<p>The honest framing: Locke v0.1 ships a small, deliberately conservative algebra. It is enough to make the workflows in this post (“snapshot, diff, gate, audit”) provably reproducible and well-defined. The richer semantics will land when the workflows the algebra is supposed to serve are more developed.</p>
</section>
<section id="belief-degradation-visualised" class="level3">
<h3 class="anchored" data-anchor-id="belief-degradation-visualised">Belief degradation, visualised</h3>
<p>The same 4-step pipeline rendered as a degradation chart — one panel per axis, showing the trajectory of each component as we move from impression to most-derived idea:</p>
<div class="cell" data-fig-width="9">
<div class="cell-output-display">
<div>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    subgraph S1["events.csv"]
        s1_schema["schema = 1.00"]:::held
        s1_miss["missingness = 1.00"]:::held
        s1_drift["drift = 1.00"]:::held
        s1_leak["leakage = 1.00"]:::held
        s1_lin["lineage = 1.00"]:::held
        s1_sam["sample = 1.00"]:::held
        s1_dup["duplication = 1.00"]:::held
        s1_con["constraint = 1.00"]:::held
    end

    subgraph S2["raw_events&lt;br/&gt;(observe)"]
        s2_schema["1.00"]:::held
        s2_miss["1.00"]:::held
        s2_drift["1.00"]:::held
        s2_leak["1.00"]:::held
        s2_lin["0.95"]:::weakened
        s2_sam["1.00"]:::held
        s2_dup["1.00"]:::held
        s2_con["1.00"]:::held
    end

    subgraph S3["active_events&lt;br/&gt;(filter)"]
        s3_schema["1.00"]:::held
        s3_miss["0.99"]:::weakened
        s3_drift["1.00"]:::held
        s3_leak["1.00"]:::held
        s3_lin["0.95"]:::held
        s3_sam["0.98"]:::weakened
        s3_dup["1.00"]:::held
        s3_con["1.00"]:::held
    end

    subgraph S4["grouped&lt;br/&gt;(group_by)"]
        s4_schema["1.00"]:::held
        s4_miss["0.99"]:::held
        s4_drift["1.00"]:::held
        s4_leak["1.00"]:::held
        s4_lin["0.95"]:::held
        s4_sam["0.78"]:::weakened
        s4_dup["1.00"]:::held
        s4_con["1.00"]:::held
    end

    subgraph S5["labeled&lt;br/&gt;(with_column)"]
        s5_schema["1.00"]:::held
        s5_miss["0.99"]:::held
        s5_drift["1.00"]:::held
        s5_leak["0.90"]:::weakened
        s5_lin["0.95"]:::held
        s5_sam["0.78"]:::held
        s5_dup["1.00"]:::held
        s5_con["1.00"]:::held
    end

    s1_schema --- s2_schema --- s3_schema --- s4_schema --- s5_schema
    s1_miss   --- s2_miss
    s2_miss   -.-&gt; s3_miss
    s3_miss   --- s4_miss --- s5_miss
    s1_drift  --- s2_drift  --- s3_drift  --- s4_drift  --- s5_drift
    s1_leak   --- s2_leak   --- s3_leak   --- s4_leak
    s4_leak   -.-&gt; s5_leak
    s1_lin    -.-&gt; s2_lin
    s2_lin    --- s3_lin    --- s4_lin    --- s5_lin
    s1_sam    --- s2_sam
    s2_sam    -.-&gt; s3_sam
    s3_sam    -.-&gt; s4_sam
    s4_sam    --- s5_sam
    s1_dup    --- s2_dup    --- s3_dup    --- s4_dup    --- s5_dup
    s1_con    --- s2_con    --- s3_con    --- s4_con    --- s5_con

    classDef held fill:#e8f5e9,stroke:#2E7D32
    classDef weakened fill:#ffebee,stroke:#C62828
</pre>
</div>
<p>Belief degradation across the 4-step pipeline above. Each axis’s value at each stage is shown as a labelled node; the layout reads left-to-right (pipeline stages) and top-to-bottom (axes). Solid edges indicate the value held; dashed edges indicate a transform_factor weakening. Schema, drift, duplication, and constraint hold at 1.00 throughout. Missingness ticked down once. Lineage dropped at ingest and held. Sample dropped twice (filter, group_by). Leakage dropped once (with_column).</p>
</div>
</div>
</div>
<p>The chart makes one specific claim visually: <strong>the dashed edges are the only places confidence got weaker.</strong> Every other axis held flat. A reviewer can pin a downstream finding to the specific transformation that degraded the relevant axis, because the dashed edge is exactly where the audit trail records a <code>transform_factor</code> application.</p>
<p>This is the property that makes the audit trail useful, not just reproducible. Reproducibility says “two runs of the same pipeline match.” Localisability says “when something downstream is wrong, I can point to which step weakened the belief on the affected axis.” Locke gives both.</p>
</section>
<section id="where-the-formal-model-lives-in-code" class="level3">
<h3 class="anchored" data-anchor-id="where-the-formal-model-lives-in-code">Where the formal model lives in code</h3>
<p>If you want to read the actual implementation rather than the prose:</p>
<ul>
<li><code>crates/cjc-locke/src/belief.rs</code> — <code>BeliefScore</code>, <code>BeliefWeights</code>, <code>BeliefPenalty</code> definitions and the <code>meet</code> operator.</li>
<li><code>crates/cjc-locke/src/lineage.rs</code> — <code>LineageGraph</code>, <code>LockeImpression</code>, <code>LockeIdea</code>, edge representations, content-addressed IDs.</li>
<li><code>crates/cjc-locke/src/traced.rs</code> — <code>TracedDataFrame</code> wrapper that applies <code>transform_factor</code> per operation.</li>
<li><code>crates/cjc-locke/src/dispatch.rs</code> — the 22 <code>locke_*</code> builtins that expose the model to <code>.cjcl</code> source.</li>
</ul>
<p>Everything is <code>pub</code> and documented. The composition rules are unit-tested for monotonicity, idempotence, and associativity. The deterministic-update rules are property-tested by <code>proptest</code>. The “shipped vs planned” gaps above each have an issue or an <code>// TODO(v0.2):</code> marker in the source.</p>
</section>
</section>
<section id="install" class="level2">
<h2 class="anchored" data-anchor-id="install">Install</h2>
<div class="sourceCode" id="cb28"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="ex">cargo</span> add cjc-locke</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The crate is at version 0.1.10 on crates.io and works with the matching version of <code>cjc-data</code>, <code>cjc-repro</code>, <code>cjc-runtime</code> from the same workspace release. If you want the CLI:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="ex">cargo</span> install cjc-lang</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="ex">cjcl</span> locke validate your-data.csv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The benchmark code is in the repo at <code>bench/locke_vs_gx/</code>. Anyone with <code>pip install great_expectations pandas</code> can re-run the full comparison.</p>
</section>
<section id="where-v0.2-is-going" class="level2">
<h2 class="anchored" data-anchor-id="where-v0.2-is-going">Where v0.2 is going</h2>
<p>The next release will close the gaps the benchmark exposed:</p>
<ul>
<li>Native Parquet decoder (Thrift + Snappy + PLAIN encoding minimum)</li>
<li>Value-set-membership checks at the validate path (matching GX’s <code>ExpectColumnDistinctValuesToBeInSet</code>)</li>
<li>Multi-class target-leakage AUC (v0.1 supports binary targets only)</li>
<li>HTML output with per-column distribution sparklines via <code>cjc-vizor</code></li>
<li>Optional parallel column-validation via rayon (per-column work is embarrassingly parallel)</li>
<li>JUnit XML and SARIF output for CI integrations</li>
</ul>
<p>If a Locke check you wanted is missing, the issue tracker is open.</p>
</section>
<section id="final-honest-framing" class="level2">
<h2 class="anchored" data-anchor-id="final-honest-framing">Final honest framing</h2>
<p>I built Locke because CJC-Lang needed a data-skepticism layer that preserved the runtime determinism guarantee at the validation boundary. The benchmark against Great Expectations was a calibration exercise — I wanted to know whether the “Locke is competitive” claim I’d been making was actually true.</p>
<p>The answer, on the specific workflows Locke is designed for, is <strong>yes</strong>. Locke matched GX 5 / 5 on every ground-truth fact in a real benchmark, ran 275× faster end-to-end, and fired more checks out of the box for the specific failure modes that break customer-churn pipelines.</p>
<p>That’s not a knock on Great Expectations, dbt, Pandera, or Monte Carlo. Each of those tools is mature, well-staffed, and the right answer at its layer of the stack. Locke doesn’t compete with any of them — it adds an epistemic layer underneath where the audit artifact is the deliverable. If your data lives in Snowflake and your team needs Slack alerting, <strong>use GX or Monte Carlo</strong>. If your pipeline is pandas-native and you want in-process guards, <strong>use Pandera</strong>. If the validation belongs inside dbt’s DAG, <strong>use dbt tests</strong>.</p>
<p>If your data fits in a CSV / JSONL, you need a deterministic CI gate, and you’re tired of validating customer-churn pipelines with spreadsheets and prayer, <strong>use Locke</strong>.</p>
<p>The code is on <a href="https://crates.io/crates/cjc-locke">crates.io</a>. The benchmark is in the repo. The whole thing is MIT-licensed.</p>
<p><code>cjcl locke validate your-data.csv</code> and tell me what breaks.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© 2026 Adam Ezzat. Built with <a href="https://quarto.org/">Quarto</a>.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>