<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adam Ezzat">
<meta name="dcterms.date" content="2026-04-12">
<meta name="description" content="TidyView is CJC-Lang’s data manipulation system. It uses a tidyverse-style API backed by database-engine internals — columnar storage, bitmask filtering, predicate pushdown, and zone maps — to deliver deterministic, auditable data pipelines with zero hidden mutations. Includes worked examples, audit walkthroughs, and a 38-test benchmark suite proving every architectural claim.">

<title>Adam Ezzat - TidyView: A Database Engine in Disguise</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Adam Ezzat</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html" rel="" target="">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../projects.html" rel="" target="">
 <span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../blog/index.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/AdamEzzat1" rel="" target=""><i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://linkedin.com/in/adamezzat" rel="" target=""><i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-problem" id="toc-the-problem" class="nav-link active" data-scroll-target="#the-problem">The Problem</a></li>
  <li><a href="#what-tidyview-is" id="toc-what-tidyview-is" class="nav-link" data-scroll-target="#what-tidyview-is">What TidyView Is</a>
  <ul class="collapse">
  <li><a href="#how-data-flows-through-a-tidyview-pipeline" id="toc-how-data-flows-through-a-tidyview-pipeline" class="nav-link" data-scroll-target="#how-data-flows-through-a-tidyview-pipeline">How Data Flows Through a TidyView Pipeline</a></li>
  </ul></li>
  <li><a href="#the-database-connection" id="toc-the-database-connection" class="nav-link" data-scroll-target="#the-database-connection">The Database Connection</a>
  <ul class="collapse">
  <li><a href="#columnar-storage" id="toc-columnar-storage" class="nav-link" data-scroll-target="#columnar-storage">Columnar Storage</a></li>
  <li><a href="#bitmask-filtering" id="toc-bitmask-filtering" class="nav-link" data-scroll-target="#bitmask-filtering">Bitmask Filtering</a></li>
  <li><a href="#predicate-pushdown" id="toc-predicate-pushdown" class="nav-link" data-scroll-target="#predicate-pushdown">Predicate Pushdown</a></li>
  <li><a href="#zone-maps" id="toc-zone-maps" class="nav-link" data-scroll-target="#zone-maps">Zone Maps</a></li>
  </ul></li>
  <li><a href="#what-this-prevents" id="toc-what-this-prevents" class="nav-link" data-scroll-target="#what-this-prevents">What This Prevents</a>
  <ul class="collapse">
  <li><a href="#the-aliasing-problem" id="toc-the-aliasing-problem" class="nav-link" data-scroll-target="#the-aliasing-problem">The Aliasing Problem</a></li>
  <li><a href="#the-order-dependent-mutation-problem" id="toc-the-order-dependent-mutation-problem" class="nav-link" data-scroll-target="#the-order-dependent-mutation-problem">The Order-Dependent Mutation Problem</a></li>
  <li><a href="#the-hidden-null-problem" id="toc-the-hidden-null-problem" class="nav-link" data-scroll-target="#the-hidden-null-problem">The Hidden Null Problem</a></li>
  <li><a href="#the-floating-point-drift-problem" id="toc-the-floating-point-drift-problem" class="nav-link" data-scroll-target="#the-floating-point-drift-problem">The Floating-Point Drift Problem</a></li>
  </ul></li>
  <li><a href="#how-to-audit-a-tidyview-pipeline" id="toc-how-to-audit-a-tidyview-pipeline" class="nav-link" data-scroll-target="#how-to-audit-a-tidyview-pipeline">How to Audit a TidyView Pipeline</a>
  <ul class="collapse">
  <li><a href="#error-messages-that-point-to-the-problem" id="toc-error-messages-that-point-to-the-problem" class="nav-link" data-scroll-target="#error-messages-that-point-to-the-problem">Error Messages That Point to the Problem</a></li>
  </ul></li>
  <li><a href="#why-not-just-use-polars" id="toc-why-not-just-use-polars" class="nav-link" data-scroll-target="#why-not-just-use-polars">Why Not Just Use Polars?</a></li>
  <li><a href="#tidyview-in-practice" id="toc-tidyview-in-practice" class="nav-link" data-scroll-target="#tidyview-in-practice">TidyView in Practice</a>
  <ul class="collapse">
  <li><a href="#loading-and-filtering" id="toc-loading-and-filtering" class="nav-link" data-scroll-target="#loading-and-filtering">Loading and Filtering</a></li>
  <li><a href="#chaining-operations" id="toc-chaining-operations" class="nav-link" data-scroll-target="#chaining-operations">Chaining Operations</a></li>
  <li><a href="#adding-computed-columns" id="toc-adding-computed-columns" class="nav-link" data-scroll-target="#adding-computed-columns">Adding Computed Columns</a></li>
  <li><a href="#sorting-and-slicing" id="toc-sorting-and-slicing" class="nav-link" data-scroll-target="#sorting-and-slicing">Sorting and Slicing</a></li>
  <li><a href="#joins" id="toc-joins" class="nav-link" data-scroll-target="#joins">Joins</a></li>
  </ul></li>
  <li><a href="#auditing-a-pipeline-a-worked-example" id="toc-auditing-a-pipeline-a-worked-example" class="nav-link" data-scroll-target="#auditing-a-pipeline-a-worked-example">Auditing a Pipeline: A Worked Example</a>
  <ul class="collapse">
  <li><a href="#step-1-which-rows-survived-the-filter" id="toc-step-1-which-rows-survived-the-filter" class="nav-link" data-scroll-target="#step-1-which-rows-survived-the-filter">Step 1: Which rows survived the filter?</a></li>
  <li><a href="#step-2-how-did-the-groups-form" id="toc-step-2-how-did-the-groups-form" class="nav-link" data-scroll-target="#step-2-how-did-the-groups-form">Step 2: How did the groups form?</a></li>
  <li><a href="#step-3-verify-the-aggregation" id="toc-step-3-verify-the-aggregation" class="nav-link" data-scroll-target="#step-3-verify-the-aggregation">Step 3: Verify the aggregation</a></li>
  <li><a href="#step-4-is-the-original-data-intact" id="toc-step-4-is-the-original-data-intact" class="nav-link" data-scroll-target="#step-4-is-the-original-data-intact">Step 4: Is the original data intact?</a></li>
  <li><a href="#catching-mistakes-at-compile-time" id="toc-catching-mistakes-at-compile-time" class="nav-link" data-scroll-target="#catching-mistakes-at-compile-time">Catching Mistakes at Compile Time</a></li>
  </ul></li>
  <li><a href="#benchmark-results" id="toc-benchmark-results" class="nav-link" data-scroll-target="#benchmark-results">Benchmark Results</a>
  <ul class="collapse">
  <li><a href="#a.-filter-microbenchmarks" id="toc-a.-filter-microbenchmarks" class="nav-link" data-scroll-target="#a.-filter-microbenchmarks">A. Filter Microbenchmarks</a></li>
  <li><a href="#b.-chained-filter-composition" id="toc-b.-chained-filter-composition" class="nav-link" data-scroll-target="#b.-chained-filter-composition">B. Chained Filter Composition</a></li>
  <li><a href="#c.-group-by-summarise" id="toc-c.-group-by-summarise" class="nav-link" data-scroll-target="#c.-group-by-summarise">C. Group-By + Summarise</a></li>
  <li><a href="#d.-sorting" id="toc-d.-sorting" class="nav-link" data-scroll-target="#d.-sorting">D. Sorting</a></li>
  <li><a href="#e.-joins" id="toc-e.-joins" class="nav-link" data-scroll-target="#e.-joins">E. Joins</a></li>
  <li><a href="#f.-full-pipeline-benchmarks" id="toc-f.-full-pipeline-benchmarks" class="nav-link" data-scroll-target="#f.-full-pipeline-benchmarks">F. Full Pipeline Benchmarks</a></li>
  <li><a href="#g.-scaling-behavior" id="toc-g.-scaling-behavior" class="nav-link" data-scroll-target="#g.-scaling-behavior">G. Scaling Behavior</a></li>
  <li><a href="#h.-determinism-verification" id="toc-h.-determinism-verification" class="nav-link" data-scroll-target="#h.-determinism-verification">H. Determinism Verification</a></li>
  <li><a href="#i.-memory-budget" id="toc-i.-memory-budget" class="nav-link" data-scroll-target="#i.-memory-budget">I. Memory Budget</a></li>
  <li><a href="#j.-trust-and-audit-trail" id="toc-j.-trust-and-audit-trail" class="nav-link" data-scroll-target="#j.-trust-and-audit-trail">J. Trust and Audit Trail</a></li>
  </ul></li>
  <li><a href="#the-one-sentence-summary" id="toc-the-one-sentence-summary" class="nav-link" data-scroll-target="#the-one-sentence-summary">The One-Sentence Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">TidyView: A Database Engine in Disguise</h1>
<p class="subtitle lead">How CJC-Lang handles data manipulation — and why I couldn’t just use Pandas.</p>
  <div class="quarto-categories">
    <div class="quarto-category">CJC-Lang</div>
    <div class="quarto-category">data</div>
    <div class="quarto-category">databases</div>
    <div class="quarto-category">determinism</div>
    <div class="quarto-category">architecture</div>
    <div class="quarto-category">benchmarks</div>
  </div>
  </div>

<div>
  <div class="description">
    TidyView is CJC-Lang’s data manipulation system. It uses a tidyverse-style API backed by database-engine internals — columnar storage, bitmask filtering, predicate pushdown, and zone maps — to deliver deterministic, auditable data pipelines with zero hidden mutations. Includes worked examples, audit walkthroughs, and a 38-test benchmark suite proving every architectural claim.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Adam Ezzat </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 12, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">April 12, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="reading-time">
🕑 ~30 min read
</div>
<div class="stats-row">
<div class="stat">
<span class="number">3</span><span class="stat-label">layers</span>
</div>
<div class="stat">
<span class="number">40+</span><span class="stat-label">operations</span>
</div>
<div class="stat">
<span class="number">0</span><span class="stat-label">HashMaps</span>
</div>
<div class="stat">
<span class="number">38</span><span class="stat-label">benchmark tests</span>
</div>
</div>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
TL;DR
</div>
</div>
<div class="callout-body-container callout-body">
<p>TidyView is CJC-Lang’s data manipulation system. It looks like R’s dplyr on the surface, but underneath it’s a database engine: columnar storage, lazy evaluation, bitmask filtering, predicate pushdown, and zone maps. The result is a data pipeline where every intermediate state is inspectable, the original data is never mutated, and the same input always produces the same output — down to the last bit.</p>
</div>
</div>
<section id="the-problem" class="level2">
<h2 class="anchored" data-anchor-id="the-problem">The Problem</h2>
<p>When I started building <a href="../../../blog/posts/introducing-cjc/index.html">CJC-Lang</a>, the core promise was simple: <strong>same seed, same output, always.</strong> Every part of the language enforces this — ordered collections, Kahan summation, seeded RNG, no FMA in SIMD kernels.</p>
<p>But then I needed to handle data. Filter a table. Group rows. Compute aggregates. Join two datasets.</p>
<p>The obvious move was to reach for an existing DataFrame library. But when I looked at what’s available, I kept running into the same problems:</p>
<p><strong>Hash-based grouping.</strong> Most DataFrame libraries — including Pandas and Polars — use hash maps to group rows. Hash maps are fast, but their iteration order may depend on internal hash seeds or execution strategy. Depending on the configuration, grouping the same data twice can produce rows in a different order. That makes bit-identical reproducibility difficult to guarantee.</p>
<p><strong>Floating-point reduction order.</strong> Call <code>sum()</code> on a million floats in Pandas. The result depends on the order of accumulation. Add the numbers in a different order and you get different rounding errors. Small differences, but they compound — and they mean “same data, different result” depending on implementation details. (Polars and other libraries may use more sophisticated reduction strategies, but the result can still vary across execution modes or platforms.)</p>
<p><strong>Parallel scheduling.</strong> Libraries that use thread pools for parallel execution (Polars uses Rayon, for example) gain significant throughput. But thread scheduling is inherently non-deterministic, which means parallel aggregation can introduce ordering variation between runs — even with identical input. Whether this matters depends on the workload, but for bit-identical reproducibility it’s a concern.</p>
<p><strong>Aliasing mutations.</strong> Pandas has an entire warning category (<code>SettingWithCopyWarning</code>) dedicated to the fact that modifying a filtered subset might or might not modify the original DataFrame. Whether it does depends on internal memory layout decisions that are invisible to the user.</p>
<p>None of these are bugs. They’re design trade-offs made by libraries that prioritize speed over reproducibility. But they break CJC-Lang’s core contract. So I built something else.</p>
</section>
<section id="what-tidyview-is" class="level2">
<h2 class="anchored" data-anchor-id="what-tidyview-is">What TidyView Is</h2>
<p>TidyView is a three-layer data manipulation system:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Layer</th>
<th>Type</th>
<th>What it does</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Immutable view</strong></td>
<td><code>TidyView</code></td>
<td>Zero-copy lens: bitmask + projection over shared data</td>
</tr>
<tr class="even">
<td><strong>Materialized frame</strong></td>
<td><code>TidyFrame</code></td>
<td>Copy-on-write buffer for mutations</td>
</tr>
<tr class="odd">
<td><strong>Grouped view</strong></td>
<td><code>GroupedTidyView</code></td>
<td>Group index for aggregation</td>
</tr>
</tbody>
</table>
<p>The API surface is modeled on R’s dplyr — <code>filter</code>, <code>select</code>, <code>mutate</code>, <code>group_by</code>, <code>summarise</code>, <code>arrange</code>, <code>join</code>. If you’ve used the tidyverse, you already know the vocabulary.</p>
<p>But the implementation borrows from a different tradition entirely: <strong>analytical databases.</strong></p>
<section id="how-data-flows-through-a-tidyview-pipeline" class="level3">
<h3 class="anchored" data-anchor-id="how-data-flows-through-a-tidyview-pipeline">How Data Flows Through a TidyView Pipeline</h3>
<div class="cell" data-fig-width="7">
<div class="cell-output-display">
<div>
<div>

<pre class="mermaid mermaid-js">flowchart TD
    A["CSV / Data Source"] --&gt; B["Base DataFrame&lt;br/&gt;&lt;i&gt;immutable, Rc-shared&lt;/i&gt;"]
    B --&gt; C["TidyView&lt;br/&gt;&lt;i&gt;zero-copy lens&lt;/i&gt;"]
    C --&gt; D["filter( )&lt;br/&gt;&lt;i&gt;bitmask A — no data copied&lt;/i&gt;"]
    D --&gt; E["filter( )&lt;br/&gt;&lt;i&gt;bitmask B — AND with A&lt;/i&gt;"]
    E --&gt; F["group_by( )&lt;br/&gt;&lt;i&gt;BTreeMap index over visible rows&lt;/i&gt;"]
    F --&gt; G["summarise( )&lt;br/&gt;&lt;i&gt;Kahan reduction per group&lt;/i&gt;"]
    G --&gt; H["Materialized Result&lt;br/&gt;&lt;i&gt;TidyFrame — new data&lt;/i&gt;"]

    style A fill:#f9f9f9,stroke:#333
    style B fill:#e8f4fd,stroke:#2196F3,stroke-width:2px
    style C fill:#e8f4fd,stroke:#2196F3
    style D fill:#fff3e0,stroke:#FF9800
    style E fill:#fff3e0,stroke:#FF9800
    style F fill:#f3e5f5,stroke:#9C27B0
    style G fill:#f3e5f5,stroke:#9C27B0
    style H fill:#e8f5e9,stroke:#4CAF50,stroke-width:2px
</pre>
</div>
</div>
</div>
</div>
<p>Every step from the base DataFrame through the filters shares the same underlying data. New memory is only allocated for bitmasks (orange) and the final materialized result (green). The original data (blue) is never modified.</p>
</section>
</section>
<section id="the-database-connection" class="level2">
<h2 class="anchored" data-anchor-id="the-database-connection">The Database Connection</h2>
<p>I didn’t set out to build a database engine. But the constraints I was working under — determinism, auditability, memory safety — kept pushing me toward the same solutions that database engineers arrived at decades ago.</p>
<section id="columnar-storage" class="level3">
<h3 class="anchored" data-anchor-id="columnar-storage">Columnar Storage</h3>
<p>Data is stored column-major:</p>
<pre><code>// Internally:
columns: [
    ("name",    Str(["Alice", "Bob", "Carol", "Dave"])),
    ("age",     Int([30, 25, 35, 28])),
    ("revenue", Float([150.0, 200.0, 175.0, 225.0])),
]</code></pre>
<p>Each column is a contiguous typed buffer. When you compute <code>sum(revenue)</code>, the runtime scans a single <code>Vec&lt;f64&gt;</code> — no pointer chasing, no skipping over unrelated fields. This is the same storage model used by Apache Arrow, DuckDB, and Parquet.</p>
<p>The alternative — row-major storage — would scatter each <code>revenue</code> value across a row struct alongside <code>name</code> and <code>age</code> data. For a table with 100 columns, computing a single-column aggregate would touch 100x more memory than necessary.</p>
</section>
<section id="bitmask-filtering" class="level3">
<h3 class="anchored" data-anchor-id="bitmask-filtering">Bitmask Filtering</h3>
<p>This is the design choice that makes everything else work. When you filter a TidyView, <strong>no data is copied.</strong> Instead, a bitmask records which rows passed the predicate:</p>
<pre><code>// Original data: 4 rows
base: ["Alice", "Bob", "Carol", "Dave"]  // ages: 30, 25, 35, 28

// After filter(age &gt; 28):
mask: [1, 0, 1, 1]  // Alice (30), Carol (35), Dave (28 fails, hypothetical: &gt; 28)</code></pre>
<p>In practice the mask is packed into 64-bit words — one bit per row. A million-row filter costs 125 KB of bitmask memory. The original data stays exactly where it was, untouched.</p>
<p>Chain three filters together? The bitmasks are ANDed. Still no data copied. Still 125 KB.</p>
<pre><code>let sales: Any = read_csv("sales.csv");
let df: Any = sales
    |&gt; filter(col("region") == "West")
    |&gt; filter(col("revenue") &gt; 1000.0)
    |&gt; filter(col("year") == 2025);</code></pre>
<p>Each <code>filter</code> call returns a new TidyView with a new bitmask. All three views share the same underlying data. The CSV is loaded once. This is the same technique used by bitmap indexes in Oracle and selection vectors in DuckDB.</p>
</section>
<section id="predicate-pushdown" class="level3">
<h3 class="anchored" data-anchor-id="predicate-pushdown">Predicate Pushdown</h3>
<p>TidyView has a lazy evaluation layer where operations build a logical plan tree before executing. The optimizer rewrites this tree using three classic database passes:</p>
<p><strong>Pass 1 — Filter merging.</strong> Consecutive filters are combined into a single filter with an AND predicate.</p>
<p><strong>Pass 2 — Predicate pushdown.</strong> Filters are pushed as close to the data source as possible.</p>
<p><strong>Pass 3 — Redundant select elimination.</strong> Select nodes that project all columns are removed.</p>
<p>Here’s why this matters. Suppose you write:</p>
<pre><code>let result: Any = df
    |&gt; mutate("bonus", col("salary") * 0.1)
    |&gt; filter(col("department") == "Engineering");</code></pre>
<p>Without optimization, this computes <code>bonus</code> for every row, then filters. With predicate pushdown, the optimizer recognizes that <code>department == "Engineering"</code> doesn’t depend on the <code>bonus</code> column, so it pushes the filter <em>below</em> the mutate. Now filtering happens first, and <code>bonus</code> is only computed for engineering rows.</p>
<p>The pushdown rules follow standard relational algebra:</p>
<ul>
<li>Push past <code>select</code> — always safe</li>
<li>Push past <code>arrange</code> — filtering doesn’t affect sort order</li>
<li>Push past <code>mutate</code> — only if the predicate doesn’t reference a mutated column</li>
<li>Push into <code>join</code> branches — if the predicate references only one side</li>
<li>Never past <code>group_by</code> + <code>summarise</code> — aggregation changes row identity</li>
<li>Never past <code>distinct</code> — uniqueness changes row identity</li>
</ul>
<p>These are the same rules taught in database systems textbooks. They apply here because TidyView’s operation set <em>is</em> relational algebra — just with tidyverse names.</p>
</section>
<section id="zone-maps" class="level3">
<h3 class="anchored" data-anchor-id="zone-maps">Zone Maps</h3>
<p>Each column tracks lightweight statistics:</p>
<pre><code>// ColumnStats for the "revenue" column:
min: 150.0
max: 225.0
sorted_ascending: false
n_distinct: 4</code></pre>
<p>When you write <code>filter(col("revenue") &gt; 500.0)</code>, the zone map says: max is 225, so no row can satisfy <code>&gt; 500</code>. The entire filter can be skipped.</p>
<p>When a column is sorted, the system uses binary search instead of a linear scan — O(log N) instead of O(N).</p>
<p>These are the same optimizations that Vertica, Redshift, and Parquet use at the storage layer. In TidyView they operate at the column level because the entire “database” fits in memory.</p>
</section>
</section>
<section id="what-this-prevents" class="level2">
<h2 class="anchored" data-anchor-id="what-this-prevents">What This Prevents</h2>
<p>The architectural choices above aren’t just about performance. They prevent specific classes of bugs that plague traditional DataFrame workflows.</p>
<section id="the-aliasing-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-aliasing-problem">The Aliasing Problem</h3>
<p>In Pandas:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.DataFrame({<span class="st">"x"</span>: [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>], <span class="st">"y"</span>: [<span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>]})</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>subset <span class="op">=</span> df[df.x <span class="op">&gt;</span> <span class="dv">1</span>]</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>subset[<span class="st">"z"</span>] <span class="op">=</span> <span class="dv">99</span>      <span class="co"># Does this modify df? Maybe.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Whether <code>subset["z"] = 99</code> modifies the original <code>df</code> depends on whether Pandas chose to return a view or a copy when you wrote <code>df[df.x &gt; 1]</code>. This is the <code>SettingWithCopyWarning</code> — one of the most common sources of confusion in data science code.</p>
<p>In TidyView, this problem doesn’t exist. The base data lives behind an <code>Rc</code> (reference-counted pointer) and is never modified. When you need to mutate, <code>TidyFrame</code> checks the reference count:</p>
<ul>
<li>If only one reference exists, mutate in place</li>
<li>If multiple references exist, deep-clone first, then mutate the clone</li>
</ul>
<p>The check is deterministic — it’s a simple integer comparison, not a heuristic. The other views are never affected.</p>
</section>
<section id="the-order-dependent-mutation-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-order-dependent-mutation-problem">The Order-Dependent Mutation Problem</h3>
<p>In Pandas:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> df.assign(a <span class="op">=</span> df.x <span class="op">+</span> <span class="dv">1</span>, b <span class="op">=</span> df.a <span class="op">*</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Does <code>df.a</code> in the second expression see the <em>newly computed</em> <code>a</code> or the <em>original</em> <code>a</code>? In Pandas, it sees the new one. The result depends on the order of the assignments. Swap <code>a</code> and <code>b</code> and you get different data.</p>
<p>In TidyView, <code>mutate</code> uses <strong>snapshot semantics</strong>: all column references are validated against the column list frozen <em>before</em> any assignments execute. Every expression sees the data as it was when the <code>mutate</code> call started:</p>
<pre><code>let result: Any = df
    |&gt; mutate("a", col("x") + 1)
    |&gt; mutate("b", col("a") * 2);
// col("a") always reads the ORIGINAL "a" column
// If "a" didn't exist before, this is an error — not a silent dependency</code></pre>
<p>This is the same principle as SQL’s <code>UPDATE SET a = b, b = a</code> — the SET clause reads from a snapshot, so this correctly swaps the values rather than setting both to <code>b</code>.</p>
</section>
<section id="the-hidden-null-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-hidden-null-problem">The Hidden Null Problem</h3>
<p>Pandas DataFrames can have <code>NaN</code> or <code>None</code> in any column at any time. You discover this at runtime, usually when an aggregation silently skips missing values and gives you a number that’s subtly wrong.</p>
<p>In TidyView, the base <code>Column</code> type has <strong>no null representation</strong>:</p>
<pre><code>// Column — always fully populated:
Int(Vec&lt;i64&gt;)
Float(Vec&lt;f64&gt;)
Str(Vec&lt;String&gt;)
Bool(Vec&lt;bool&gt;)</code></pre>
<p>There’s no <code>Option</code> wrapper. No sentinel values. If you have a <code>TidyView</code>, its data is guaranteed null-free by type.</p>
<p>Nulls exist, but they’re quarantined in a separate type called <code>NullCol</code>. You only encounter <code>NullCol</code> through operations that <em>can</em> introduce nulls — left joins (unmatched rows), <code>pivot_wider</code> (missing combinations), full joins. These operations return a <code>NullableFrame</code> instead of a <code>TidyFrame</code>, and the type boundary makes the null-possibility explicit.</p>
<p>The question “does my data have nulls?” is answered by the type, not by scanning every cell.</p>
</section>
<section id="the-floating-point-drift-problem" class="level3">
<h3 class="anchored" data-anchor-id="the-floating-point-drift-problem">The Floating-Point Drift Problem</h3>
<div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pandas</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>pd.Series([<span class="fl">1e16</span>, <span class="fl">1.0</span>, <span class="op">-</span><span class="fl">1e16</span>]).<span class="bu">sum</span>()  <span class="co"># → 0.0 (wrong)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The mathematically correct answer is <code>1.0</code>. Pandas gives <code>0.0</code> because it uses naive left-to-right summation: <code>1e16 + 1.0</code> rounds to <code>1e16</code> (the <code>1.0</code> is lost to floating-point precision), then <code>1e16 - 1e16 = 0.0</code>.</p>
<p>TidyView uses Kahan compensated summation for every floating-point reduction — <code>sum</code>, <code>mean</code>, <code>variance</code>, <code>sd</code>, all of them. Kahan summation tracks a correction term that captures the rounding error:</p>
<pre><code>// Kahan summation:
//   sum = 0, c = 0
//   y = 1e16 - 0 = 1e16;    t = 0 + 1e16 = 1e16;    c = (1e16 - 1e16) - 1e16 = 0
//   y = 1.0 - 0 = 1.0;      t = 1e16 + 1.0 = 1e16;   c = (1e16 - 1e16) - 1.0 = -1.0
//   y = -1e16 - (-1.0);      ...compensates the lost 1.0
//   Result: 1.0 (correct)</code></pre>
<p>Same input, same result, every time. Not approximately correct — exactly correct within the limits of double precision.</p>
</section>
</section>
<section id="how-to-audit-a-tidyview-pipeline" class="level2">
<h2 class="anchored" data-anchor-id="how-to-audit-a-tidyview-pipeline">How to Audit a TidyView Pipeline</h2>
<p>This is where the architecture pays off in practice. When something goes wrong in a data pipeline, the question is always: <em>where did the data go wrong?</em></p>
<p>In TidyView, every intermediate step is inspectable because the original data is never modified. Every <code>filter</code> produces a bitmask you can inspect — count the set bits, iterate them to see which rows survived, AND two masks to see which rows passed both filters. Every <code>group_by</code> produces a group index with key values and row indices. And the original data stays intact behind a shared reference, so you can always go back and check it.</p>
<p>This is fundamentally different from a system where <code>df = df[df.region == "West"]</code> discards the filtered-out rows. In that system, if the filter was wrong, the evidence is gone. In TidyView, the evidence is the bitmask, and the original data is still there to check against. (A full worked example with concrete row indices is in the <a href="#auditing-a-pipeline-a-worked-example">Auditing a Pipeline</a> section below.)</p>
<section id="error-messages-that-point-to-the-problem" class="level3">
<h3 class="anchored" data-anchor-id="error-messages-that-point-to-the-problem">Error Messages That Point to the Problem</h3>
<p>When something goes wrong, TidyView’s error types name the exact issue:</p>
<pre><code>ColumnNotFound("revnue")       // Typo — you meant "revenue"
DuplicateColumn("total")       // Two columns with the same name in select
PredicateNotBool { got: "Int" } // filter predicate returned Int, not Bool
TypeMismatch { expected: "Float", got: "Str" }  // arithmetic on a string column
LengthMismatch { expected: 1000, got: 500 }     // broadcast size mismatch
EmptyGroup                     // first() or last() called on a group with zero rows
CapacityExceeded { limit: 65535, got: 70000 }   // too many distinct levels for a categorical column</code></pre>
<p>Every error variant names the specific column, type, or value that caused the problem. You know what went wrong and where, not just that something failed.</p>
<p><code>EmptyGroup</code> catches a subtle bug: if an aggressive filter removes all rows from a group and you then call <code>first()</code> or <code>last()</code> in your summarise, you get a clear error instead of a silent null or a crash. <code>CapacityExceeded</code> guards the categorical column type — CJC-Lang’s factor columns use <code>u16</code> codes (max 65,535 distinct levels) for cache efficiency, and this error tells you exactly when your data exceeds that budget.</p>
</section>
</section>
<section id="why-not-just-use-polars" class="level2">
<h2 class="anchored" data-anchor-id="why-not-just-use-polars">Why Not Just Use Polars?</h2>
<p>Polars is a good library. It’s fast, it has a lazy API, and it uses Arrow-backed columnar storage. If I were building a Python application, I’d probably use it.</p>
<p>But Polars makes different trade-offs than TidyView:</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Polars</th>
<th>TidyView</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Grouping</strong></td>
<td>Hash-based (fast; order may vary by execution mode)</td>
<td>BTreeMap (deterministic first-occurrence order)</td>
</tr>
<tr class="even">
<td><strong>Summation</strong></td>
<td>Optimized reduction (fast; may vary across platforms)</td>
<td>Kahan compensated (deterministic, bit-identical)</td>
</tr>
<tr class="odd">
<td><strong>Parallelism</strong></td>
<td>Rayon thread pool (high throughput)</td>
<td>Single-threaded (deterministic, no scheduling variance)</td>
</tr>
<tr class="even">
<td><strong>Null model</strong></td>
<td>Nullable everywhere (Arrow validity bitmaps)</td>
<td>Null-free by default, <code>NullCol</code> only where needed</td>
</tr>
<tr class="odd">
<td><strong>Sampling</strong></td>
<td>System RNG</td>
<td>Seeded LCG-based Fisher-Yates</td>
</tr>
</tbody>
</table>
<p>None of Polars’ trade-offs are wrong — and Polars is significantly faster for most workloads. It’s a production-grade library optimized for throughput. TidyView is optimizing for a different property: <strong>reproducibility</strong> — the guarantee that the same pipeline on the same data always produces the same result, bit for bit, on any machine. TidyView will be slower than Polars on almost any benchmark. That’s the expected cost of determinism.</p>
<p>When your work requires an audit trail — when a regulator, a reviewer, or future-you needs to verify that a result is correct — that guarantee can matter more than raw speed.</p>
</section>
<section id="tidyview-in-practice" class="level2">
<h2 class="anchored" data-anchor-id="tidyview-in-practice">TidyView in Practice</h2>
<p>The architecture above is interesting in the abstract, but what does it actually look like when you write code? Here’s a walkthrough of real CJC-Lang programs using TidyView.</p>
<section id="loading-and-filtering" class="level3">
<h3 class="anchored" data-anchor-id="loading-and-filtering">Loading and Filtering</h3>
<pre><code>let csv = "name,age,city\nAlice,30,NYC\nBob,25,LA\nCharlie,35,NYC\nDiana,28,LA\n";
let df = Csv.parse(csv);
let view = df.view();

// filter: age &gt; 28 (keeps Alice=30, Charlie=35)
let older = view.filter(dexpr_binop("&gt;", col("age"), 28));
print(older.nrows());   // → 2</code></pre>
<p><code>Csv.parse()</code> returns a DataFrame. <code>.view()</code> wraps it in a TidyView — a zero-copy lens over the data. The <code>filter</code> call doesn’t copy any rows. It creates a new bitmask: <code>[1, 0, 1, 0]</code>. The original four rows are still sitting in the same memory, untouched.</p>
</section>
<section id="chaining-operations" class="level3">
<h3 class="anchored" data-anchor-id="chaining-operations">Chaining Operations</h3>
<pre><code>let csv = "dept,name,salary\nEng,Alice,100\nEng,Bob,120\nSales,Carol,80\nSales,Dave,90\nEng,Eve,110\n";
let df = Csv.parse(csv);
let view = df.view();

let result = view
    .filter(dexpr_binop("&gt;", col("salary"), 85))
    .group_by(["dept"])
    .summarise("n", tidy_count(), "avg", tidy_mean("salary"));
print(result.nrows());   // → 2 (Eng and Sales groups)</code></pre>
<p>This is a three-step pipeline: filter rows where salary exceeds 85, group surviving rows by department, then compute count and mean per group. The filter produces a bitmask; the group-by reads through it to build its index; the summarise collapses each group into one row.</p>
</section>
<section id="adding-computed-columns" class="level3">
<h3 class="anchored" data-anchor-id="adding-computed-columns">Adding Computed Columns</h3>
<pre><code>let mutated = view.mutate("bonus", dexpr_binop("*", col("salary"), 10));
print(mutated.ncols());   // → 4 (dept, name, salary, bonus)</code></pre>
<p><code>mutate</code> returns a <code>TidyFrame</code> — a materialized copy with the new column appended. The original <code>view</code> still has three columns. This is the copy-on-write boundary: reads are free, writes trigger a copy.</p>
</section>
<section id="sorting-and-slicing" class="level3">
<h3 class="anchored" data-anchor-id="sorting-and-slicing">Sorting and Slicing</h3>
<pre><code>let csv = "name,score\nAlice,85\nBob,92\nCharlie,78\nDiana,95\n";
let df = Csv.parse(csv);
let sorted = df.view().arrange([desc("score")]);
let top2 = sorted.slice_head(2);
print(top2.nrows());   // → 2 (Diana=95, Bob=92)</code></pre>
<p><code>arrange</code> materializes the data in sorted order (sorting can’t be lazy — it needs to compare every element). <code>slice_head</code> takes the first N rows from the result.</p>
</section>
<section id="joins" class="level3">
<h3 class="anchored" data-anchor-id="joins">Joins</h3>
<pre><code>let left = Csv.parse("id,name\n10,Alice\n20,Bob\n30,Charlie\n").view();
let right = Csv.parse("id,dept\n10,Eng\n30,Sales\n40,HR\n").view();

let joined = left.inner_join(right, "id", "id");
print(joined.nrows());   // → 2 (id=10 and id=30 match)</code></pre>
<p>Inner join keeps only rows where the key exists in both tables. Alice (id=10) matches Eng, Charlie (id=30) matches Sales. Bob (id=20) and HR (id=40) are dropped.</p>
</section>
</section>
<section id="auditing-a-pipeline-a-worked-example" class="level2">
<h2 class="anchored" data-anchor-id="auditing-a-pipeline-a-worked-example">Auditing a Pipeline: A Worked Example</h2>
<p>Suppose you’re analyzing quarterly sales data and you get a result that looks wrong. In a traditional DataFrame library, you’d re-run the pipeline with print statements and hope to catch the problem. In TidyView, you can inspect every intermediate state because nothing was destroyed.</p>
<p>Here’s a concrete scenario. You have eight sales records and you want total revenue by product in the West region:</p>
<pre><code>let sales = Csv.parse("product,region,revenue\nWidget,West,150\nGadget,West,200\nWidget,East,175\nGadget,East,225\nWidget,West,300\nGizmo,East,50\nGadget,West,180\nGizmo,East,75\n");
let view = sales.view();

let west = view.filter(dexpr_binop("==", col("region"), "West"));
let grouped = west.group_by(["product"]);
let summary = grouped.summarise("total_rev", tidy_sum("revenue"));</code></pre>
<p>The summary shows Widget: 450, Gadget: 380. Is that right? Let’s audit backward.</p>
<section id="step-1-which-rows-survived-the-filter" class="level3">
<h3 class="anchored" data-anchor-id="step-1-which-rows-survived-the-filter">Step 1: Which rows survived the filter?</h3>
<p>The bitmask after <code>filter(region == "West")</code> has bits set at positions <code>[0, 1, 4, 6]</code>. That’s four rows out of eight. You can verify: row 0 is Widget/West/150, row 1 is Gadget/West/200, row 4 is Widget/West/300, row 6 is Gadget/West/180. All West. None of the East rows slipped through.</p>
</section>
<section id="step-2-how-did-the-groups-form" class="level3">
<h3 class="anchored" data-anchor-id="step-2-how-did-the-groups-form">Step 2: How did the groups form?</h3>
<p>The group index shows two groups in <strong>first-occurrence order</strong>:</p>
<ul>
<li>Group “Widget” → base-frame rows [0, 4]</li>
<li>Group “Gadget” → base-frame rows [1, 6]</li>
</ul>
<p>Notice: Gizmo isn’t here. Both Gizmo rows were East, so they were filtered out before grouping. If you expected Gizmo to appear, the bitmask tells you exactly why it didn’t — rows 5 and 7 have their bits cleared.</p>
</section>
<section id="step-3-verify-the-aggregation" class="level3">
<h3 class="anchored" data-anchor-id="step-3-verify-the-aggregation">Step 3: Verify the aggregation</h3>
<p>Widget revenue: row 0 (150) + row 4 (300) = 450. Gadget revenue: row 1 (200) + row 6 (180) = 380. Both use Kahan compensated summation, so even with millions of rows the result would be bit-identical across runs.</p>
</section>
<section id="step-4-is-the-original-data-intact" class="level3">
<h3 class="anchored" data-anchor-id="step-4-is-the-original-data-intact">Step 4: Is the original data intact?</h3>
<p>Yes. <code>view.nrows()</code> still returns 8. You can re-filter, re-group, or inspect any column at any time. If the final number is wrong, you trace backward through bitmasks and group indices until you find where your understanding diverged from reality.</p>
</section>
<section id="catching-mistakes-at-compile-time" class="level3">
<h3 class="anchored" data-anchor-id="catching-mistakes-at-compile-time">Catching Mistakes at Compile Time</h3>
<p>TidyView’s type system and error reporting catch common mistakes before they become wrong numbers:</p>
<p><strong>Typo in a column name:</strong></p>
<pre><code>view.filter(dexpr_binop("&gt;", col("revnue"), 100));
// → Error: column `revnue` not found</code></pre>
<p><strong>Self-referencing mutate:</strong></p>
<pre><code>view.mutate("bonus", dexpr_binop("*", col("salary"), 0.1))
    .mutate("double_bonus", dexpr_binop("*", col("bonus"), 2));</code></pre>
<p>The second <code>mutate</code> sees <code>bonus</code> because it’s a separate call on the result of the first. But if you tried to reference a column in the same mutate call that creates it:</p>
<pre><code>view.mutate("a", dexpr_binop("+", col("x"), 1),
            "b", dexpr_binop("*", col("a"), 2));
// → Error: column `a` not found</code></pre>
<p>This is snapshot semantics — all column references are validated against the column list frozen <em>before</em> any assignments. You can’t accidentally create an order-dependent pipeline within a single operation.</p>
<p><strong>Type mismatch:</strong></p>
<pre><code>view.filter(dexpr_binop("+", col("name"), 1));
// → Error: type mismatch — expected Bool predicate, got Int</code></pre>
<p>The filter predicate must evaluate to Bool. Arithmetic on a string column, or a predicate that returns a number instead of true/false, is caught immediately with an error that names the exact types involved.</p>
</section>
</section>
<section id="benchmark-results" class="level2">
<h2 class="anchored" data-anchor-id="benchmark-results">Benchmark Results</h2>
<p>The claims above — bitmask filtering is cheap, chained filters don’t copy data, determinism holds across runs — are testable. I wrote a 38-test benchmark suite that measures TidyView’s performance and verifies its architectural guarantees. Here are the results, run on my machine in release mode.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>A note on context.</strong> These benchmarks measure TidyView against itself — lazy vs.&nbsp;eager, scaling behavior, determinism proofs. They are <em>not</em> comparative benchmarks against Polars, DuckDB, or Pandas. TidyView is single-threaded and prioritizes determinism over throughput; it will be slower than production-optimized libraries on raw performance. The goal here is to verify that TidyView’s architectural claims hold, not to claim speed parity with tools that make different trade-offs.</p>
</div>
</div>
</div>
<section id="a.-filter-microbenchmarks" class="level3">
<h3 class="anchored" data-anchor-id="a.-filter-microbenchmarks">A. Filter Microbenchmarks</h3>
<table class="table">
<thead>
<tr class="header">
<th>Test</th>
<th>Lazy (µs)</th>
<th>Eager (µs)</th>
<th>Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Int filter, 100K rows</td>
<td>80</td>
<td>6,459</td>
<td><strong>80×</strong></td>
</tr>
<tr class="even">
<td>Float filter, 100K rows</td>
<td>94</td>
<td>6,322</td>
<td><strong>67×</strong></td>
</tr>
<tr class="odd">
<td>String filter, 100K rows</td>
<td>9,821</td>
<td>13,496</td>
<td>1.4×</td>
</tr>
<tr class="even">
<td>Int filter, 1M rows</td>
<td>971</td>
<td>63,605</td>
<td><strong>66×</strong></td>
</tr>
</tbody>
</table>
<p><strong>What this proves:</strong> Lazy bitmask filtering is 65–80× faster than eager materialization for numeric columns. The filter itself just scans one column and sets bits — no row copying, no allocation beyond the bitmask. String filters are slower because string comparison is inherently more expensive than integer comparison, but the lazy/eager gap still exists.</p>
<p>The 1M-row int filter takes under 1 ms to produce a bitmask. Materializing — actually copying the surviving rows into a new DataFrame — takes 64 ms. If you’re chaining multiple filters, you save that materialization cost at every step.</p>
</section>
<section id="b.-chained-filter-composition" class="level3">
<h3 class="anchored" data-anchor-id="b.-chained-filter-composition">B. Chained Filter Composition</h3>
<table class="table">
<thead>
<tr class="header">
<th>Test</th>
<th>Time (µs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Single int filter, 100K</td>
<td>96</td>
</tr>
<tr class="even">
<td>Two chained int filters, 100K</td>
<td>175</td>
</tr>
<tr class="odd">
<td>Int + string chain, 100K</td>
<td>7,210</td>
</tr>
<tr class="even">
<td>Two string filters, 100K</td>
<td>12,821</td>
</tr>
</tbody>
</table>
<p><strong>What this proves:</strong> Chaining two filters costs roughly the sum of the individual filters, not more. The second filter reads through the first filter’s bitmask — it only examines rows where the bit is set. No intermediate DataFrame is created. The cost of the chain is dominated by the most expensive predicate type (string comparison).</p>
</section>
<section id="c.-group-by-summarise" class="level3">
<h3 class="anchored" data-anchor-id="c.-group-by-summarise">C. Group-By + Summarise</h3>
<table class="table">
<thead>
<tr class="header">
<th>Test</th>
<th>Groups</th>
<th>Time (µs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Count, 4 groups, 100K</td>
<td>4</td>
<td>11,473</td>
</tr>
<tr class="even">
<td>Mixed agg (5 stats), 4 groups, 100K</td>
<td>4</td>
<td>13,042</td>
</tr>
<tr class="odd">
<td>Count + Sum, 100 groups, 100K</td>
<td>100</td>
<td>18,073</td>
</tr>
<tr class="even">
<td>Count, 10K groups, 100K</td>
<td>10,000</td>
<td>35,930</td>
</tr>
<tr class="odd">
<td>Count + Sum + Mean, 10K groups, 100K</td>
<td>10,000</td>
<td>39,823</td>
</tr>
</tbody>
</table>
<p><strong>What this proves:</strong> Group-by cost scales with the number of distinct groups, not just row count. With 4 groups (the region column), grouping 100K rows takes about 11 ms. With 10K groups, it takes 36 ms. This is the cost of the BTreeMap-based index — O(N log G) where G is the number of groups. Adding more aggregation functions (from Count alone to Count + Sum + Mean + Sd + Median) adds relatively little overhead; the dominant cost is building the group index, not computing the aggregates.</p>
</section>
<section id="d.-sorting" class="level3">
<h3 class="anchored" data-anchor-id="d.-sorting">D. Sorting</h3>
<table class="table">
<thead>
<tr class="header">
<th>Test</th>
<th>Time (µs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Float descending, 100K</td>
<td>32,972</td>
</tr>
<tr class="even">
<td>Int ascending, 100K</td>
<td>37,072</td>
</tr>
<tr class="odd">
<td>String ascending, 100K</td>
<td>66,787</td>
</tr>
<tr class="even">
<td>Multi-key (string + float), 100K</td>
<td>89,806</td>
</tr>
</tbody>
</table>
<p><strong>What this proves:</strong> Sorting is the most expensive single operation because it must materialize the result (you can’t lazily represent a sort). String sorting is roughly 2× more expensive than numeric sorting due to comparison cost. Multi-key sorting adds the cost of a secondary comparator. All sorts use Rust’s stable sort (<code>sort_by</code>), which preserves the relative order of equal elements — important for determinism.</p>
</section>
<section id="e.-joins" class="level3">
<h3 class="anchored" data-anchor-id="e.-joins">E. Joins</h3>
<table class="table">
<thead>
<tr class="header">
<th>Test</th>
<th>Time (µs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Inner join, 100K × 100</td>
<td>34,063</td>
</tr>
<tr class="even">
<td>Inner join, 100K × 1K</td>
<td>38,998</td>
</tr>
<tr class="odd">
<td>Left join, 100K × 100</td>
<td>30,813</td>
</tr>
</tbody>
</table>
<p><strong>What this proves:</strong> Join performance is dominated by the left table size. Increasing the right table from 100 to 1,000 rows adds only ~14% to the join time, because the right table is indexed and lookups are fast. Left joins are slightly faster than inner joins in this case because the left join doesn’t need to check for unmatched right-side rows.</p>
</section>
<section id="f.-full-pipeline-benchmarks" class="level3">
<h3 class="anchored" data-anchor-id="f.-full-pipeline-benchmarks">F. Full Pipeline Benchmarks</h3>
<table class="table">
<thead>
<tr class="header">
<th>Pipeline</th>
<th>Time (µs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>filter → group → summarise → arrange, 100K</td>
<td>12,739</td>
</tr>
<tr class="even">
<td>filter → mutate → group → summarise, 100K</td>
<td>23,819</td>
</tr>
<tr class="odd">
<td>join → filter → group → summarise, 100K</td>
<td>48,316</td>
</tr>
</tbody>
</table>
<p><strong>What this proves:</strong> Realistic multi-step pipelines compose predictably. The filter-group-summarise-arrange pipeline (12.7 ms) is faster than the sum of its parts because the filter reduces the number of rows that downstream operations process. The join-based pipeline is slowest because joins are the most expensive operation and produce a new materialized DataFrame.</p>
</section>
<section id="g.-scaling-behavior" class="level3">
<h3 class="anchored" data-anchor-id="g.-scaling-behavior">G. Scaling Behavior</h3>
<p><strong>Row scaling (filter):</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Rows</th>
<th>Filter Time (µs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10K</td>
<td>9</td>
</tr>
<tr class="even">
<td>100K</td>
<td>94</td>
</tr>
<tr class="odd">
<td>1M</td>
<td>1,064</td>
</tr>
</tbody>
</table>
<p>Filter time scales linearly with row count — exactly what you’d expect from a single-pass scan. 10× more rows ≈ 10× more time.</p>
<p><strong>Row scaling (group-by + summarise):</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Rows</th>
<th>Time (µs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10K</td>
<td>1,035</td>
</tr>
<tr class="even">
<td>100K</td>
<td>11,778</td>
</tr>
<tr class="odd">
<td>1M</td>
<td>159,033</td>
</tr>
</tbody>
</table>
<p>Group-by also scales linearly, but with a higher constant factor due to the BTreeMap insertions.</p>
<p><strong>Column width scaling (100K rows):</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Columns</th>
<th>Filter (µs)</th>
<th>Materialize (µs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>3</td>
<td>154</td>
<td>542</td>
</tr>
<tr class="even">
<td>11</td>
<td>201</td>
<td>1,185</td>
</tr>
<tr class="odd">
<td>51</td>
<td>161</td>
<td>10,653</td>
</tr>
<tr class="even">
<td>101</td>
<td>211</td>
<td>19,263</td>
</tr>
</tbody>
</table>
<p><strong>What this proves:</strong> Filter time is nearly constant regardless of table width — because filtering only touches the predicate column, not the others. Materialization scales linearly with column count because it has to copy every column. This is the columnar storage payoff: a table with 101 columns filters as fast as a table with 3 columns.</p>
<p><strong>Group cardinality scaling (100K rows):</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Groups</th>
<th>Time (µs)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>4</td>
<td>15,676</td>
</tr>
<tr class="even">
<td>100</td>
<td>21,305</td>
</tr>
<tr class="odd">
<td>1,000</td>
<td>26,297</td>
</tr>
<tr class="even">
<td>10,000</td>
<td>43,172</td>
</tr>
<tr class="odd">
<td>50,000</td>
<td>73,041</td>
</tr>
</tbody>
</table>
<p>Going from 4 groups to 50,000 groups increases time by about 4.7×. The BTreeMap index is O(N log G), so the cost grows sub-linearly with group count.</p>
</section>
<section id="h.-determinism-verification" class="level3">
<h3 class="anchored" data-anchor-id="h.-determinism-verification">H. Determinism Verification</h3>
<table class="table">
<thead>
<tr class="header">
<th>Test</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pipeline (sum + mean + sd + median), 10 runs</td>
<td><strong>Bit-identical</strong></td>
</tr>
<tr class="even">
<td>Sort stability (equal keys preserve insertion order)</td>
<td><strong>Stable</strong></td>
</tr>
<tr class="odd">
<td>Group order (first-occurrence across 5 runs)</td>
<td><strong>Deterministic</strong></td>
</tr>
</tbody>
</table>
<p><strong>What this proves:</strong> The determinism guarantee isn’t aspirational — it’s measured. Ten runs of the same pipeline produce identical floating-point results down to the last bit. The sort is stable (equal elements preserve their original order), and groups always appear in first-occurrence order.</p>
</section>
<section id="i.-memory-budget" class="level3">
<h3 class="anchored" data-anchor-id="i.-memory-budget">I. Memory Budget</h3>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1M-row bitmask</td>
<td><strong>122 KB</strong> (vs 15,625 KB data = <strong>128× smaller</strong>)</td>
</tr>
<tr class="even">
<td>3 chained filters, 100K rows</td>
<td>Each mask: 1,563 words. Rows: 74,999 → 49,999 → 24,999</td>
</tr>
</tbody>
</table>
<p><strong>What this proves:</strong> A bitmask for 1 million rows costs 122 KB — one bit per row, packed into 64-bit words. The data itself (just the <code>id</code> and <code>value</code> columns) occupies 15.6 MB. The bitmask is 128× smaller than the data it describes. Three chained filters create three separate bitmasks, each 1,563 words (12.5 KB), while the underlying data is shared. The row counts shrink progressively (75K → 50K → 25K) as each filter narrows the result, but no data is copied until you explicitly materialize.</p>
</section>
<section id="j.-trust-and-audit-trail" class="level3">
<h3 class="anchored" data-anchor-id="j.-trust-and-audit-trail">J. Trust and Audit Trail</h3>
<p>These are not performance benchmarks — they’re correctness proofs that verify TidyView’s architectural claims.</p>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Test</th>
<th>What it verifies</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Filter traceability</strong></td>
<td>After two filters on a 10-row dataset, the bitmask contains exactly <code>[0, 4, 8]</code>. You can name every surviving row by index.</td>
</tr>
<tr class="even">
<td><strong>Group membership</strong></td>
<td>Groups appear in first-occurrence order (Eng, Sales, HR — not alphabetical). Each group’s row indices are inspectable: Eng = [0, 2], Sales = [1, 4], HR = [3, 5].</td>
</tr>
<tr class="odd">
<td><strong>Snapshot semantics</strong></td>
<td><code>mutate("a", ..., "b", col("a") * 2)</code> fails with <code>column 'a' not found</code> — you can’t reference a column created in the same mutate call.</td>
</tr>
<tr class="even">
<td><strong>Copy-on-write isolation</strong></td>
<td>Clone a frame, mutate the clone — the original has 2 columns, the clone has 3. They’re independent.</td>
</tr>
<tr class="odd">
<td><strong>Full pipeline trace</strong></td>
<td>Filter → group → summarise on 8 rows: west_rows = [0, 1, 4, 6], Widget total = 450, Gadget total = 380. Original still has 8 rows.</td>
</tr>
<tr class="even">
<td><strong>Deterministic sampling</strong></td>
<td><code>slice_sample(100, seed=42)</code> selects the same 100 rows across 5 runs.</td>
</tr>
<tr class="odd">
<td><strong>Projection inspection</strong></td>
<td><code>select(["b", "d"])</code> on a 4-column table sets projection indices to [1, 3]. Original table still reports 4 columns.</td>
</tr>
</tbody>
</table>
<p><strong>What this proves:</strong> Every architectural claim made earlier in this post — bitmask traceability, group ordering, snapshot semantics, copy-on-write isolation, deterministic sampling — is verified by a concrete test with concrete numbers.</p>
</section>
</section>
<section id="the-one-sentence-summary" class="level2">
<h2 class="anchored" data-anchor-id="the-one-sentence-summary">The One-Sentence Summary</h2>
<p>TidyView is a database engine wearing a tidyverse costume, designed so that <strong>same data + same code = same result</strong> on every machine, every run, every time.</p>
<p>It combines familiar dplyr verbs (<code>filter</code>, <code>select</code>, <code>mutate</code>, <code>group_by</code>, <code>summarise</code>) with database-engine internals (columnar storage, bitmask filtering, predicate pushdown, zone maps) to deliver data pipelines that are deterministic by construction, auditable by design, and memory-safe without runtime surprises.</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>CJC-Lang is open source and available on <a href="https://crates.io/crates/cjc-lang">crates.io</a>. The TidyView implementation lives in <code>crates/cjc-data/</code> — about 11,000 lines of Rust with zero external dependencies. The full benchmark suite (38 tests, 10 categories) is in <code>tests/tidyview_benchmarks.rs</code>.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">© 2026 Adam Ezzat. Built with <a href="https://quarto.org/">Quarto</a>.</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>



<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>